'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export interface LanguagePack {
  code: string;
  name: string;
  flag: string;
}

export const initialAvailableLanguages: LanguagePack[] = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
];

export type Language = string;

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  availableLanguages: LanguagePack[];
  setAvailableLanguages: (packs: LanguagePack[]) => void;
  translations: Record<string, Record<string, string>>;
  setTranslations: (trans: Record<string, Record<string, string>>) => void;
}

const initialTranslations: Record<string, Record<string, string>> = {
  en: {
    'nav.deals': "Today's Deals",
    'nav.sell': 'Sell on Mercora',
    'nav.hello': 'Hello, Sign in',
    'nav.account': 'Account & Lists',
    'nav.orders': 'Returns & Orders',
    'nav.cart': 'Cart',
    'nav.search_placeholder': "Search products globally: 'Handmade WATCH'...",
    'nav.all_categories': 'All Categories',
    'nav.deliver_to': 'Deliver to',
    'nav.my_account': 'My Account',
    'nav.login_or_sign_up': 'Login or Sign Up',
    'nav.cart_count': 'Cart',
    'nav.favorite': 'My Favorites',
    'nav.orders_list': 'My Orders',
    'nav.home_page': 'Home',
    'nav.categories_nav': 'Categories',
    'nav.switch_dark': 'Switch to Dark Mode',
    'nav.switch_light': 'Switch to Light Mode',
    'nav.seller_hub': 'Seller Hub',
    'nav.admin_hub': 'Admin Hub',
    'nav.logged_in_as': 'Signed in as',
    'nav.login_google': 'Sign In with Google',
    'nav.logout': 'Sign Out',
    'nav.location_default': 'Istanbul, Kadikoy',
    'product.buy_now': 'Buy Now',
    'product.add_cart': 'Add to Cart',
    'product.description': 'Description',
    'product.specifications': 'Specifications',
    'product.reviews': 'Reviews',
    'product.you_might_also_like': 'You might also like',
    'product.inStock': 'In Stock',
    'product.outOfStock': 'Out of Stock',
    'product.addToCart': 'Add to Cart',
    'product.added': 'Added!',
    'product.freeShipping': 'Free Shipping',
    'product.questions_answers': 'Q&A',
    'product.verified_purchase': 'Verified Purchase',
    'product.useful': 'Helpful',
    'product.rec.interest.title': 'You Might Also Like',
    'product.rec.interest.sub': 'Other items viewed by customers who viewed this',
    'product.rec.bakanAldi.title': 'Also Bought by Viewers',
    'product.rec.bakanAldi.sub': 'Other items bought by customers who viewed this',
    'product.rec.birlikte.title': 'Frequently Bought Together',
    'product.rec.birlikte.sub': 'Items often bought together with this product',
    'product.rec.populer.title': 'Everyone is Looking at These',
    'product.rec.populer.sub': 'Most popular items in this category',
    'product.rec.secilmis.title': 'Curated Popular Products',
    'product.rec.secilmis.sub': 'Popular items curated for you',
    'product.rec.searches.title': 'Popular Searches',
    'home.best_sellers': 'Best Sellers',
    'home.for_everyone': 'Products for Everyone',
    'home.new_arrivals': 'New Arrivals',
    'home.popular_products': 'Popular Products',
    'home.special_for_you': 'Special For You',
    'global.discover': 'Discover the World Market',
    'global.see_all': 'See All',
    'global.show_more': 'Show More',
    'category.all': 'All Categories',
    'category.electronics': 'Electronics',
    'category.fashion': 'Fashion',
    'category.home': 'Home & Living',
    'category.supermarket': 'Supermarket',
    'category.beauty': 'Personal Care',
    'category.sport': 'Sports & Outdoor',
    'search.products': 'Matching Products',
    'search.popular': 'Popular Searches',
    'footer.corporate': 'Corporate',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.support': 'Support',
    'footer.help': 'Help Center',
    'footer.privacy_policy': 'Privacy Policy',
    'footer.terms_of_service': 'Terms of Service',
    'cart.empty': 'Your cart is empty',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.remove': 'Remove',
    'checkout.shipping': 'Shipping',
    'checkout.payment': 'Payment',
    'checkout.place_order': 'Place Order',
    'cart.summary': 'Order Summary',
    'checkout.shipping_info': 'Shipping Information',
    'wishlist.empty_title': 'Your Wishlist is Empty',
    'wishlist.empty_desc': 'Save your favorite products to your wishlist.',
    'nav.wishlist': 'My Favorites',
    'seller.dashboard': 'Dashboard',
    'seller.inventory': 'Inventory',
    'seller.orders': 'Orders',
    'seller.finance': 'Finance',
    'seller.pricing': 'Pricing',
    'seller.analytics': 'Analytics',
    'seller.import': 'Import',
    'seller.certificates': 'Certificates',
    'seller.settings': 'Settings',
    'auth.error.generic': 'An error occurred. Please try again.',
    'badge.free_shipping': 'Free Shipping',
    'badge.tomorrow_at_door': 'Tomorrow At Door',
    'trust.safe_payment': 'Secure Payment',
    'trust.easy_return': 'Easy Returns',
    'trust.original': '100% Original',
    'filter.categories': 'Categories',
    'filter.priceRange': 'Price Range',
    'filter.minRating': 'Minimum Rating',
    'filter.clearAll': 'Clear All',
    'flash.deals': 'Flash Deals',
    'flash.view': 'View All',
    'nav.checkout': 'Checkout',
    'cart.currency': 'Currency',
    'search.page': 'Page',
    'search.no_results': 'No results found',
    'search.try_different': 'Try different keywords',
    'search.browse': 'Browse Categories',
    'footer.tagline': 'Global Artisan Marketplace',
    'footer.rights_reserved': 'All rights reserved.',
    'settings.title': 'Settings',
  },
  tr: {
    'nav.deals': "Günün Fırsatları",
    'nav.sell': 'Mercora\'da Sat',
    'nav.hello': 'Merhaba, Giriş yap',
    'nav.account': 'Hesap ve Listeler',
    'nav.orders': 'İadeler ve Siparişler',
    'nav.cart': 'Sepet',
    'nav.search_placeholder': "Küresel ürün ara: 'El yapımı SAAT'...",
    'nav.all_categories': 'Tüm Kategoriler',
    'nav.deliver_to': 'Gönderim',
    'nav.my_account': 'Hesabım',
    'nav.login_or_sign_up': 'Giriş yap veya üye ol',
    'nav.cart_count': 'Sepetim',
    'nav.favorite': 'Favorilerim',
    'nav.orders_list': 'Siparişlerim',
    'nav.home_page': 'Ana Sayfa',
    'nav.categories_nav': 'Kategoriler',
    'nav.switch_dark': 'Karanlık Moda Geç',
    'nav.switch_light': 'Aydınlık Moda Geç',
    'nav.seller_hub': 'Satıcı Paneli',
    'nav.admin_hub': 'Yönetici Paneli',
    'nav.logged_in_as': 'Olarak giriş yapıldı',
    'nav.login_google': 'Google ile Giriş Yap',
    'nav.logout': 'Çıkış Yap',
    'nav.location_default': 'İstanbul, Kadıköy',
    'product.buy_now': 'Hemen Al',
    'product.add_cart': 'Sepete Ekle',
    'product.description': 'Ürün Açıklaması',
    'product.specifications': 'Ürün Özellikleri',
    'product.reviews': 'Değerlendirmeler',
    'product.you_might_also_like': 'Bunlar da ilginizi çekebilir',
    'product.inStock': 'Stokta Var',
    'product.outOfStock': 'Stokta Yok',
    'product.addToCart': 'Sepete Ekle',
    'product.added': 'Eklendi!',
    'product.freeShipping': 'Ücretsiz Kargo',
    'product.questions_answers': 'Soru & Cevap',
    'product.verified_purchase': 'Onaylanmış Alışveriş',
    'product.useful': 'Faydalı',
    'product.rec.interest.title': 'Bunlar da İlgini Çekebilir',
    'product.rec.interest.sub': 'Ürünü inceleyenlerin baktığı diğer ürünler',
    'product.rec.bakanAldi.title': 'Buna Bakanların Aldıkları',
    'product.rec.bakanAldi.sub': 'Ürünü inceleyenlerin aldığı diğer ürünler',
    'product.rec.birlikte.title': 'Birlikte Alınanlar',
    'product.rec.birlikte.sub': 'Beraber alınan ürünler',
    'product.rec.populer.title': 'Herkes Bunlara Bakıyor',
    'product.rec.populer.sub': 'Kategorinin en popüler ürünleri',
    'product.rec.secilmis.title': 'Popüler Ürünlerden Seçtik',
    'product.rec.secilmis.sub': 'Sizin için seçilen popüler ürünler',
    'product.rec.searches.title': 'Popüler Aramalar',
    'home.best_sellers': 'En Çok Satanlar',
    'home.for_everyone': 'Bu Ürünler Herkese Göre',
    'home.new_arrivals': 'Yeni Gelenler',
    'home.popular_products': 'Popüler Ürünler',
    'home.special_for_you': 'Size Özel Seçtiklerimiz',
    'global.discover': 'Dünya Pazarını Keşfet',
    'global.see_all': 'Tümünü Gör',
    'global.show_more': 'Daha Fazla Gör',
    'category.all': 'Tüm Kategoriler',
    'category.electronics': 'Elektronik',
    'category.fashion': 'Moda Dünyası',
    'category.home': 'Ev & Yaşam',
    'category.supermarket': 'Süpermarket',
    'category.beauty': 'Kişisel Bakım',
    'category.sport': 'Spor & Outdoor',
    'search.products': 'Eşleşen Ürünler',
    'search.popular': 'Popüler Aramalar',
    'footer.corporate': 'Kurumsal',
    'footer.about': 'Hakkımızda',
    'footer.careers': 'Kariyer',
    'footer.support': 'Destek',
    'footer.help': 'Yardım Merkezi',
    'footer.privacy_policy': 'Gizlilik Politikası',
    'footer.terms_of_service': 'Kullanım Koşulları',
    'cart.empty': 'Sepetiniz boş',
    'cart.total': 'Toplam',
    'cart.checkout': 'Ödemeye Geç',
    'cart.remove': 'Kaldır',
    'checkout.shipping': 'Kargo',
    'checkout.payment': 'Ödeme',
    'checkout.place_order': 'Siparişi Tamamla',
    'cart.summary': 'Sipariş Özeti',
    'checkout.shipping_info': 'Teslimat Bilgileri',
    'wishlist.empty_title': 'Favori Listeniz Boş',
    'wishlist.empty_desc': 'Sevdiğiniz ürünleri favorilerinize ekleyin.',
    'nav.wishlist': 'Favorilerim',
    'seller.dashboard': 'Panel',
    'seller.inventory': 'Envanter',
    'seller.orders': 'Siparişler',
    'seller.finance': 'Finans',
    'seller.pricing': 'Fiyatlandırma',
    'seller.analytics': 'Analitik',
    'seller.import': 'İçe Aktar',
    'seller.certificates': 'Sertifikalar',
    'seller.settings': 'Ayarlar',
    'auth.error.generic': 'Bir hata oluştu. Lütfen tekrar deneyin.',
    'badge.free_shipping': 'Kargo Bedava',
    'badge.tomorrow_at_door': 'Yarın Kapında',
    'trust.safe_payment': 'Güvenli Ödeme',
    'trust.easy_return': 'Kolay İade',
    'trust.original': '%100 Orijinal',
    'filter.categories': 'Kategoriler',
    'filter.priceRange': 'Fiyat Aralığı',
    'filter.minRating': 'Minimum Puan',
    'filter.clearAll': 'Tümünü Temizle',
    'flash.deals': 'Flaş Fırsatlar',
    'flash.view': 'Tümünü Gör',
    'nav.checkout': 'Ödeme',
    'cart.currency': 'Para Birimi',
    'search.page': 'Sayfa',
    'search.no_results': 'Sonuç bulunamadı',
    'search.try_different': 'Farklı kelimeler deneyin',
    'search.browse': 'Kategorilere Göz At',
    'footer.tagline': 'Global Artisan Marketplace',
    'footer.rights_reserved': 'Tüm hakları saklıdır.',
    'settings.title': 'Ayarlar',
  },
  de: {
    'nav.deals': 'Tagesangebote',
    'nav.sell': 'Auf Mercora verkaufen',
    'nav.hello': 'Hallo, Anmelden',
    'nav.account': 'Konto & Listen',
    'nav.orders': 'Retouren & Bestellungen',
    'nav.cart': 'Einkaufswagen',
    'nav.search_placeholder': 'Produkte weltweit suchen...',
    'nav.all_categories': 'Alle Kategorien',
    'nav.deliver_to': 'Liefern nach',
    'nav.my_account': 'Mein Konto',
    'nav.login_or_sign_up': 'Anmelden oder Registrieren',
    'nav.cart_count': 'Warenkorb',
    'nav.favorite': 'Meine Favoriten',
    'nav.orders_list': 'Meine Bestellungen',
    'nav.home_page': 'Startseite',
    'nav.categories_nav': 'Kategorien',
    'nav.switch_dark': 'Zum Dunkelmodus wechseln',
    'nav.switch_light': 'Zum Hellmodus wechseln',
    'nav.seller_hub': 'Verkäuferbereich',
    'nav.admin_hub': 'Adminbereich',
    'nav.logged_in_as': 'Angemeldet als',
    'nav.login_google': 'Mit Google anmelden',
    'nav.logout': 'Abmelden',
    'nav.location_default': 'Istanbul, Kadiköy',
    'product.buy_now': 'Jetzt kaufen',
    'product.add_cart': 'In den Warenkorb',
    'product.description': 'Beschreibung',
    'product.specifications': 'Spezifikationen',
    'product.reviews': 'Bewertungen',
    'product.you_might_also_like': 'Das könnte Ihnen auch gefallen',
    'product.inStock': 'Auf Lager',
    'product.outOfStock': 'Ausverkauft',
    'product.addToCart': 'In den Warenkorb',
    'product.added': 'Hinzugefügt!',
    'product.freeShipping': 'Kostenloser Versand',
    'product.questions_answers': 'Fragen & Antworten',
    'product.verified_purchase': 'Verifizierter Kauf',
    'product.useful': 'Nützlich',
    'product.rec.interest.title': 'Das könnte Ihnen gefallen',
    'product.rec.interest.sub': 'Andere Produkte, die von Käufern dieses Artikels angesehen wurden',
    'product.rec.bakanAldi.title': 'Auch von Betrachtern gekauft',
    'product.rec.bakanAldi.sub': 'Andere Produkte, die von Käufern dieses Artikels gekauft wurden',
    'product.rec.birlikte.title': 'Wird oft zusammen gekauft',
    'product.rec.birlikte.sub': 'Zusammen gekaufte Produkte mit diesem Artikel',
    'product.rec.populer.title': 'Alle schauen sich das an',
    'product.rec.populer.sub': 'Beliebteste Produkte in dieser Kategorie',
    'product.rec.secilmis.title': 'Beliebte Artikel für Sie',
    'product.rec.secilmis.sub': 'Beliebte Artikel für Sie ausgewählt',
    'product.rec.searches.title': 'Beliebte Suchen',
    'home.best_sellers': 'Bestseller',
    'home.for_everyone': 'Produkte für jeden',
    'home.new_arrivals': 'Neu eingetroffen',
    'home.popular_products': 'Beliebte Produkte',
    'home.special_for_you': 'Speziell für Sie',
    'global.discover': 'Entdecken Sie den Weltmarkt',
    'global.see_all': 'Alle ansehen',
    'global.show_more': 'Mehr anzeigen',
    'category.all': 'Alle Kategorien',
    'category.electronics': 'Elektronik',
    'category.fashion': 'Mode',
    'category.home': 'Haus & Garten',
    'category.supermarket': 'Supermarkt',
    'category.beauty': 'Schönheitspflege',
    'category.sport': 'Sport & Outdoor',
    'search.products': 'Passende Produkte',
    'search.popular': 'Beliebte Suchanfragen',
    'footer.corporate': 'Unternehmen',
    'footer.about': 'Über uns',
    'footer.careers': 'Karriere',
    'footer.support': 'Support',
    'footer.help': 'Hilfezentrum',
    'footer.privacy_policy': 'Datenschutzrichtlinie',
    'footer.terms_of_service': 'Nutzungsbedingungen',
    'cart.empty': 'Ihr Warenkorb ist leer',
    'cart.total': 'Gesamt',
    'cart.checkout': 'Zur Kasse',
    'cart.remove': 'Entfernen',
    'checkout.shipping': 'Versand',
    'checkout.payment': 'Zahlung',
    'checkout.place_order': 'Bestellung aufgeben',
    'cart.summary': 'Bestellübersicht',
    'checkout.shipping_info': 'Versandinformationen',
    'wishlist.empty_title': 'Ihre Wunschliste ist leer',
    'wishlist.empty_desc': 'Speichern Sie Ihre Lieblingsprodukte auf der Wunschliste.',
    'nav.wishlist': 'Meine Favoriten',
    'seller.dashboard': 'Dashboard',
    'seller.inventory': 'Lagerbestand',
    'seller.orders': 'Bestellungen',
    'seller.finance': 'Finanzen',
    'seller.pricing': 'Preisgestaltung',
    'seller.analytics': 'Analysen',
    'seller.import': 'Importieren',
    'seller.certificates': 'Zertifikate',
    'seller.settings': 'Einstellungen',
    'auth.error.generic': 'Ein Fehler ist aufgetreten. Bitte erneut versuchen.',
    'badge.free_shipping': 'Kostenloser Versand',
    'badge.tomorrow_at_door': 'Morgen an der Tür',
    'trust.safe_payment': 'Sichere Zahlung',
    'trust.easy_return': 'Einfache Rückgabe',
    'trust.original': '100% Original',
    'filter.categories': 'Kategorien',
    'filter.priceRange': 'Preisspanne',
    'filter.minRating': 'Mindestbewertung',
    'filter.clearAll': 'Alle löschen',
    'flash.deals': 'Blitzangebote',
    'flash.view': 'Alle anzeigen',
    'nav.checkout': 'Zur Kasse',
    'cart.currency': 'Währung',
    'search.page': 'Seite',
    'search.no_results': 'Keine Ergebnisse gefunden',
    'search.try_different': 'Versuchen Sie andere Suchbegriffe',
    'search.browse': 'Kategorien durchsuchen',
    'footer.tagline': 'Globaler Kunsthandwerks-Marktplatz',
    'footer.rights_reserved': 'Alle Rechte vorbehalten.',
    'settings.title': 'Einstellungen',
  },
  ar: {
    'nav.deals': 'عروض اليوم',
    'nav.sell': 'البيع على ميركورا',
    'nav.hello': 'مرحباً، تسجيل الدخول',
    'nav.account': 'الحساب والقوائم',
    'nav.orders': 'المرتجعات والطلبات',
    'nav.cart': 'عربة التسوق',
    'nav.search_placeholder': 'ابحث عن المنتجات عالمياً...',
    'nav.all_categories': 'كل الفئات',
    'nav.deliver_to': 'التوصيل إلى',
    'nav.my_account': 'حسابي',
    'nav.login_or_sign_up': 'تسجيل الدخول أو الاشتراك',
    'nav.cart_count': 'عربة التسوق',
    'nav.favorite': 'المفضلة',
    'nav.orders_list': 'طلباتي',
    'nav.home_page': 'الصفحة الرئيسية',
    'nav.categories_nav': 'الفئات',
    'nav.switch_dark': 'التبديل إلى الوضع الداكن',
    'nav.switch_light': 'التبديل إلى الوضع الفاتح',
    'nav.seller_hub': 'لوحة البائع',
    'nav.admin_hub': 'لوحة الإدارة',
    'nav.logged_in_as': 'تم تسجيل الدخول باسم',
    'nav.login_google': 'تسجيل الدخول عبر Google',
    'nav.logout': 'تسجيل الخروج',
    'nav.location_default': 'إسطنبول، كاديكوي',
    'product.buy_now': 'اشتر الآن',
    'product.add_cart': 'أضف إلى السلة',
    'product.description': 'الوصف',
    'product.specifications': 'المواصفات',
    'product.reviews': 'التقييمات',
    'product.you_might_also_like': 'قد يعجبك أيضاً',
    'product.inStock': 'متوفر',
    'product.outOfStock': 'نفدت الكمية',
    'product.addToCart': 'أضف للسلة',
    'product.added': 'تمت الإضافة!',
    'product.freeShipping': 'شحن مجاني',
    'product.questions_answers': 'الأسئلة والأجوبة',
    'product.verified_purchase': 'شراء مؤكد',
    'product.useful': 'مفيد',
    'product.rec.interest.title': 'قد يعجبك أيضاً',
    'product.rec.interest.sub': 'منتجات أخرى شاهدها زوار هذه السلعة',
    'product.rec.bakanAldi.title': 'اشتراها أيضاً من شاهدوها',
    'product.rec.bakanAldi.sub': 'منتجات أخرى اشتراها زوار هذه السلعة',
    'product.rec.birlikte.title': 'يُشترى معاً في الغالب',
    'product.rec.birlikte.sub': 'منتجات تُشترى معاً مع هذه السلعة',
    'product.rec.populer.title': 'الجميع يتصفح هذا',
    'product.rec.populer.sub': 'المنتجات الأكثر شعبية in هذه الفئة',
    'product.rec.secilmis.title': 'منتجات شائعة مختارة لك',
    'product.rec.secilmis.sub': 'منتجات شائعة مختارة لك',
    'product.rec.searches.title': 'عمليات البحث الشائعة',
    'home.best_sellers': 'الأكثر مبيعاً',
    'home.for_everyone': 'منتجات للجميع',
    'home.new_arrivals': 'وصل حديثاً',
    'home.popular_products': 'المنتجات الشائعة',
    'home.special_for_you': 'خاصة بك',
    'global.discover': 'اكتشف السوق العالمي',
    'global.see_all': 'عرض الكل',
    'global.show_more': 'عرض المزيد',
    'category.all': 'جميع الفئات',
    'category.electronics': 'الإلكترونيات',
    'category.fashion': 'الأزياء',
    'category.home': 'المنزل والحديقة',
    'category.supermarket': 'سوبرماركت',
    'category.beauty': 'العناية الشخصية',
    'category.sport': 'الرياضة والهواء الطلق',
    'search.products': 'المنتجات المطابقة',
    'search.popular': 'البحوث الشائعة',
    'footer.corporate': 'الشركة',
    'footer.about': 'من نحن',
    'footer.careers': 'الوظائف',
    'footer.support': 'الدعم',
    'footer.help': 'مركز المساعدة',
    'footer.privacy_policy': 'سياسة الخصوصية',
    'footer.terms_of_service': 'شروط الخدمة',
    'cart.empty': 'سلة التسوق فارغة',
    'cart.total': 'المجموع',
    'cart.checkout': 'إتمام الشراء',
    'cart.remove': 'إزالة',
    'checkout.shipping': 'الشحن',
    'checkout.payment': 'الدفع',
    'checkout.place_order': 'تقديم الطلب',
    'cart.summary': 'ملخص الطلب',
    'checkout.shipping_info': 'معلومات الشحن',
    'wishlist.empty_title': 'قائمة المفضلة فارغة',
    'wishlist.empty_desc': 'احفظ منتجاتك المفضلة في قائمة المفضلة.',
    'nav.wishlist': 'المفضلة',
    'seller.dashboard': 'لوحة التحكم',
    'seller.inventory': 'المخزون',
    'seller.orders': 'الطلبات',
    'seller.finance': 'المالية',
    'seller.pricing': 'التسعير',
    'seller.analytics': 'التحليلات',
    'seller.import': 'استيراد',
    'seller.certificates': 'الشهادات',
    'seller.settings': 'الإعدادات',
    'auth.error.generic': 'حدث خطأ. يرجى المحاولة مرة أخرى.',
    'badge.free_shipping': 'شحن مجاني',
    'badge.tomorrow_at_door': 'غداً على الباب',
    'trust.safe_payment': 'دفع آمن',
    'trust.easy_return': 'إرجاع سهل',
    'trust.original': 'أصلي 100%',
    'filter.categories': 'الفئات',
    'filter.priceRange': 'نطاق السعر',
    'filter.minRating': 'الحد الأدنى للتقييم',
    'filter.clearAll': 'مسح الكل',
    'flash.deals': 'صفقات اليوم',
    'flash.view': 'عرض الكل',
    'nav.checkout': 'إتمام الشراء',
    'cart.currency': 'العملة',
    'search.page': 'الصفحة',
    'search.no_results': 'لم يتم العثور على نتائج',
    'search.try_different': 'جرب كلمات بحث مختلفة',
    'search.browse': 'تصفح الفئات',
    'footer.tagline': 'سوق الحرف اليدوية العالمي',
    'footer.rights_reserved': 'جميع الحقوق محفوظة.',
    'settings.title': 'الإعدادات',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('tr');
  const [availableLanguages, setAvailableLanguages] = useState<LanguagePack[]>(initialAvailableLanguages);
  const [translations, setTranslations] = useState<Record<string, Record<string, string>>>(initialTranslations);

  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = lang;
      document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    }
  }, [lang]);

  const t = (key: string) => {
    return translations[lang]?.[key] || initialTranslations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, availableLanguages, setAvailableLanguages, translations, setTranslations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
