'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

export interface LanguagePack {
  code: string;
  name: string;
  flag: string;
}

export const initialAvailableLanguages: LanguagePack[] = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
];

export type Language = string;

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  availableLanguages: LanguagePack[];
  setAvailableLanguages: (packs: LanguagePack[]) => void;
  translations: Record<string, Record<string, string>>;
  setTranslations: (trans: Record<string, Record<string, string>>) => void;
}

const initialTranslations: Record<string, Record<string, string>> = {
  en: {
    'nav.deals': "Today's Deals",
    'nav.sell': 'Sell on Mercora',
    'nav.hello': 'Hello, Sign in',
    'nav.account': 'Account & Lists',
    'nav.orders': 'Returns & Orders',
    'nav.cart': 'Cart',
    'nav.search_placeholder': "Search products globally: 'Handmade WATCH'...",
    'nav.all_categories': 'All Categories',
    'nav.deliver_to': 'Deliver to',
    'nav.my_account': 'My Account',
    'nav.login_or_sign_up': 'Login or Sign Up',
    'nav.cart_count': 'Cart',
    'nav.favorite': 'My Favorites',
    'nav.orders_list': 'My Orders',
    'nav.home_page': 'Home',
    'nav.categories_nav': 'Categories',
    'nav.switch_dark': 'Switch to Dark Mode',
    'nav.switch_light': 'Switch to Light Mode',
    'nav.seller_hub': 'Seller Hub',
    'nav.admin_hub': 'Admin Hub',
    'nav.logged_in_as': 'Signed in as',
    'nav.login_google': 'Sign In with Google',
    'nav.logout': 'Sign Out',
    'nav.location_default': 'Istanbul, Kadikoy',
    'product.buy_now': 'Buy Now',
    'product.add_cart': 'Add to Cart',
    'product.description': 'Description',
    'product.specifications': 'Specifications',
    'product.reviews': 'Reviews',
    'product.you_might_also_like': 'You might also like',
    'product.inStock': 'In Stock',
    'product.outOfStock': 'Out of Stock',
    'product.addToCart': 'Add to Cart',
    'product.added': 'Added!',
    'product.freeShipping': 'Free Shipping',
    'home.best_sellers': 'Best Sellers',
    'home.for_everyone': 'Products for Everyone',
    'home.new_arrivals': 'New Arrivals',
    'home.popular_products': 'Popular Products',
    'home.special_for_you': 'Special For You',
    'global.discover': 'Discover the World Market',
    'global.see_all': 'See All',
    'global.show_more': 'Show More',
    'category.all': 'All Categories',
    'category.electronics': 'Electronics',
    'category.fashion': 'Fashion',
    'category.home': 'Home & Living',
    'category.supermarket': 'Supermarket',
    'category.beauty': 'Personal Care',
    'category.sport': 'Sports & Outdoor',
    'search.products': 'Matching Products',
    'search.popular': 'Popular Searches',
    'footer.corporate': 'Corporate',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.support': 'Support',
    'footer.help': 'Help Center',
    'footer.privacy_policy': 'Privacy Policy',
    'footer.terms_of_service': 'Terms of Service',
    'cart.empty': 'Your cart is empty',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.remove': 'Remove',
    'checkout.shipping': 'Shipping',
    'checkout.payment': 'Payment',
    'checkout.place_order': 'Place Order',
    'cart.summary': 'Order Summary',
    'checkout.shipping_info': 'Shipping Information',
    'wishlist.empty_title': 'Your Wishlist is Empty',
    'wishlist.empty_desc': 'Save your favorite products to your wishlist.',
    'nav.wishlist': 'My Favorites',
    'seller.dashboard': 'Dashboard',
    'seller.inventory': 'Inventory',
    'seller.orders': 'Orders',
    'seller.finance': 'Finance',
    'seller.pricing': 'Pricing',
    'seller.analytics': 'Analytics',
    'seller.import': 'Import',
    'seller.certificates': 'Certificates',
    'seller.settings': 'Settings',
    'auth.error.generic': 'An error occurred. Please try again.',
    'badge.free_shipping': 'Free Shipping',
    'badge.tomorrow_at_door': 'Tomorrow At Door',
    'trust.safe_payment': 'Secure Payment',
    'trust.easy_return': 'Easy Returns',
    'trust.original': '100% Original',
    'filter.categories': 'Categories',
    'filter.priceRange': 'Price Range',
    'filter.minRating': 'Minimum Rating',
    'filter.clearAll': 'Clear All',
  },
  tr: {
    'nav.deals': "Günün Fırsatları",
    'nav.sell': 'Mercora\'da Sat',
    'nav.hello': 'Merhaba, Giriş yap',
    'nav.account': 'Hesap ve Listeler',
    'nav.orders': 'İadeler ve Siparişler',
    'nav.cart': 'Sepet',
    'nav.search_placeholder': "Küresel ürün ara: 'El yapımı SAAT'...",
    'nav.all_categories': 'Tüm Kategoriler',
    'nav.deliver_to': 'Gönderim',
    'nav.my_account': 'Hesabım',
    'nav.login_or_sign_up': 'Giriş yap veya üye ol',
    'nav.cart_count': 'Sepetim',
    'nav.favorite': 'Favorilerim',
    'nav.orders_list': 'Siparişlerim',
    'nav.home_page': 'Ana Sayfa',
    'nav.categories_nav': 'Kategoriler',
    'nav.switch_dark': 'Karanlık Moda Geç',
    'nav.switch_light': 'Aydınlık Moda Geç',
    'nav.seller_hub': 'Satıcı Paneli',
    'nav.admin_hub': 'Yönetici Paneli',
    'nav.logged_in_as': 'Olarak giriş yapıldı',
    'nav.login_google': 'Google ile Giriş Yap',
    'nav.logout': 'Çıkış Yap',
    'nav.location_default': 'İstanbul, Kadıköy',
    'product.buy_now': 'Hemen Al',
    'product.add_cart': 'Sepete Ekle',
    'product.description': 'Ürün Açıklaması',
    'product.specifications': 'Ürün Özellikleri',
    'product.reviews': 'Değerlendirmeler',
    'product.you_might_also_like': 'Bunlar da ilginizi çekebilir',
    'product.inStock': 'Stokta Var',
    'product.outOfStock': 'Stokta Yok',
    'product.addToCart': 'Sepete Ekle',
    'product.added': 'Eklendi!',
    'product.freeShipping': 'Ücretsiz Kargo',
    'home.best_sellers': 'En Çok Satanlar',
    'home.for_everyone': 'Bu Ürünler Herkese Göre',
    'home.new_arrivals': 'Yeni Gelenler',
    'home.popular_products': 'Popüler Ürünler',
    'home.special_for_you': 'Size Özel Seçtiklerimiz',
    'global.discover': 'Dünya Pazarını Keşfet',
    'global.see_all': 'Tümünü Gör',
    'global.show_more': 'Daha Fazla Gör',
    'category.all': 'Tüm Kategoriler',
    'category.electronics': 'Elektronik',
    'category.fashion': 'Moda Dünyası',
    'category.home': 'Ev & Yaşam',
    'category.supermarket': 'Süpermarket',
    'category.beauty': 'Kişisel Bakım',
    'category.sport': 'Spor & Outdoor',
    'search.products': 'Eşleşen Ürünler',
    'search.popular': 'Popüler Aramalar',
    'footer.corporate': 'Kurumsal',
    'footer.about': 'Hakkımızda',
    'footer.careers': 'Kariyer',
    'footer.support': 'Destek',
    'footer.help': 'Yardım Merkezi',
    'footer.privacy_policy': 'Gizlilik Politikası',
    'footer.terms_of_service': 'Kullanım Koşulları',
    'cart.empty': 'Sepetiniz boş',
    'cart.total': 'Toplam',
    'cart.checkout': 'Ödemeye Geç',
    'cart.remove': 'Kaldır',
    'checkout.shipping': 'Kargo',
    'checkout.payment': 'Ödeme',
    'checkout.place_order': 'Siparişi Tamamla',
    'cart.summary': 'Sipariş Özeti',
    'checkout.shipping_info': 'Teslimat Bilgileri',
    'wishlist.empty_title': 'Favori Listeniz Boş',
    'wishlist.empty_desc': 'Sevdiğiniz ürünleri favorilerinize ekleyin.',
    'nav.wishlist': 'Favorilerim',
    'seller.dashboard': 'Panel',
    'seller.inventory': 'Envanter',
    'seller.orders': 'Siparişler',
    'seller.finance': 'Finans',
    'seller.pricing': 'Fiyatlandırma',
    'seller.analytics': 'Analitik',
    'seller.import': 'İçe Aktar',
    'seller.certificates': 'Sertifikalar',
    'seller.settings': 'Ayarlar',
    'auth.error.generic': 'Bir hata oluştu. Lütfen tekrar deneyin.',
    'badge.free_shipping': 'Kargo Bedava',
    'badge.tomorrow_at_door': 'Yarın Kapında',
    'trust.safe_payment': 'Güvenli Ödeme',
    'trust.easy_return': 'Kolay İade',
    'trust.original': '%100 Orijinal',
    'filter.categories': 'Kategoriler',
    'filter.priceRange': 'Fiyat Aralığı',
    'filter.minRating': 'Minimum Puan',
    'filter.clearAll': 'Tümünü Temizle',
  },
  de: {
    'nav.deals': "Tagesangebote",
    'nav.sell': 'Auf Mercora verkaufen',
    'nav.hello': 'Hallo, Anmelden',
    'nav.account': 'Konto & Listen',
    'nav.orders': 'Retouren & Bestellungen',
    'nav.cart': 'Einkaufswagen',
    'nav.search_placeholder': "Produkte weltweit suchen...",
    'nav.all_categories': 'Alle Kategorien',
    'nav.home_page': 'Startseite',
    'nav.logout': 'Abmelden',
    'product.buy_now': 'Jetzt kaufen',
    'product.inStock': 'Auf Lager',
    'product.outOfStock': 'Ausverkauft',
    'product.addToCart': 'In den Warenkorb',
    'home.best_sellers': 'Bestseller',
    'global.see_all': 'Alle ansehen',
    'global.discover': 'Entdecken',
    'footer.corporate': 'Unternehmen',
    'footer.about': 'Über uns',
    'footer.careers': 'Karriere',
    'footer.support': 'Support',
    'footer.help': 'Hilfezentrum',
    'footer.privacy_policy': 'Datenschutzrichtlinie',
    'footer.terms_of_service': 'Nutzungsbedingungen',
    'category.all': 'Alle Kategorien',
    'category.electronics': 'Elektronik',
    'category.fashion': 'Mode',
    'category.home': 'Haus & Garten',
    'category.supermarket': 'Supermarkt',
    'category.beauty': 'Schönheitspflege',
    'category.sport': 'Sport & Outdoor',
    'cart.empty': 'Ihr Warenkorb ist leer',
    'cart.total': 'Gesamt',
    'cart.checkout': 'Zur Kasse',
    'auth.error.generic': 'Ein Fehler ist aufgetreten. Bitte erneut versuchen.',
    'badge.free_shipping': 'Kostenloser Versand',
  },
  ar: {
    'nav.deals': "عروض اليوم",
    'nav.sell': 'البيع على ميركورا',
    'nav.hello': 'مرحباً، تسجيل الدخول',
    'nav.account': 'الحساب والقوائم',
    'nav.orders': 'المرتجعات والطلبات',
    'nav.cart': 'عربة التسوق',
    'nav.search_placeholder': "ابحث عن المنتجات عالمياً...",
    'nav.all_categories': 'كل الفئات',
    'nav.home_page': 'الصفحة الرئيسية',
    'nav.logout': 'تسجيل الخروج',
    'product.buy_now': 'اشتر الآن',
    'product.inStock': 'متوفر',
    'product.outOfStock': 'نفدت الكمية',
    'product.addToCart': 'أضف للسلة',
    'home.best_sellers': 'الأكثر مبيعاً',
    'global.see_all': 'عرض الكل',
    'global.discover': 'اكتشف',
    'footer.corporate': 'الشركة',
    'footer.about': 'من نحن',
    'footer.careers': 'الوظائف',
    'footer.support': 'الدعم',
    'footer.help': 'مركز المساعدة',
    'category.all': 'جميع الفئات',
    'category.electronics': 'الإلكترونيات',
    'category.fashion': 'الأزياء',
    'category.home': 'المنزل والحديقة',
    'category.supermarket': 'سوبرماركت',
    'category.beauty': 'العناية الشخصية',
    'category.sport': 'الرياضة والهواء الطلق',
    'cart.empty': 'سلة التسوق فارغة',
    'cart.total': 'المجموع',
    'cart.checkout': 'إتمام الشراء',
    'auth.error.generic': 'حدث خطأ. يرجى المحاولة مرة أخرى.',
    'badge.free_shipping': 'شحن مجاني',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('tr');
  const [availableLanguages, setAvailableLanguages] = useState<LanguagePack[]>(initialAvailableLanguages);
  const [translations, setTranslations] = useState<Record<string, Record<string, string>>>(initialTranslations);

  const t = (key: string) => {
    return translations[lang]?.[key] || initialTranslations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, availableLanguages, setAvailableLanguages, translations, setTranslations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
