import React, { createContext, useContext, useState, ReactNode } from 'react';

export interface LanguagePack {
  code: string;
  name: string;
  flag: string;
}

export const initialAvailableLanguages: LanguagePack[] = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
];

export type Language = string;

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
  availableLanguages: LanguagePack[];
  setAvailableLanguages: (packs: LanguagePack[]) => void;
  translations: Record<string, Record<string, string>>;
  setTranslations: (trans: Record<string, Record<string, string>>) => void;
}

const initialTranslations: Record<string, Record<string, string>> = {
  en: {
    'nav.deals': "Today's Deals",
    'nav.customerservice': 'Customer Service',
    'nav.registry': 'Registry',
    'nav.giftcards': 'Gift Cards',
    'nav.sell': 'Sell on Benim Olan',
    'nav.hello': 'Hello, Sign in',
    'nav.account': 'Account & Lists',
    'nav.orders': 'Returns & Orders',
    'nav.cart': 'Cart',
    'nav.search_placeholder': "Search products globally: 'Handmade WATCH'...",
    'nav.all_categories': 'All Categories',
    'nav.departments': 'Departments',
    'nav.deliver_to': 'Deliver to',
    'hero.badge': '2026 Season Deals',
    'hero.title': 'Electronic Artifacts',
    'hero.subtitle': 'Discover the Future',
    'hero.desc': 'Handpicked artisan technology collection from London and Istanbul warehouses, all customs duties included.',
    'hero.cta': 'Browse Collection',
    'hero.watch': 'Watch Promo',
    'hero.spotlight1.title': 'Global Fulfillment',
    'hero.spotlight1.desc': 'Flat £12.00 flat rate shipping to EU and UK Hubs.',
    'product.origin': 'Origin',
    'product.delivery': 'Delivery Terms',
    'product.buy_now': 'Buy Now',
    'product.add_cart': 'Add to Cart',
    'home.best_sellers': 'Best Sellers',
    'home.for_everyone': 'Products for Everyone',
    'home.new_arrivals': 'New Arrivals',
    'global.discover': 'Discover the World Market',
    'global.see_all': 'See All',
    'market.insight': 'Market Insights',
    'market.trending': 'Bullish Demand',
    'market.scarcity': 'Scarcity Alert',
    'market.opportunity': 'Global Opportunity',
    'logistics.timeline': 'Fulfillment Strategy',
    'logistics.hub_processing': 'Hub Processing',
    'logistics.customs_clearance': 'Customs Authorization',
    'logistics.last_mile': 'Last Mile Delivery',
    'nav.location_select': 'Select Location',
    'nav.location_default': 'Istanbul, Kadikoy',
    'nav.my_account': 'My Account',
    'nav.login_or_sign_up': 'Login or Sign Up',
    'nav.cart_count': 'Cart',
    'nav.favorite': 'My Favorites',
    'nav.orders_list': 'My Orders',
    'nav.home_page': 'Home',
    'nav.categories_nav': 'Categories',
    'badge.free_shipping': 'Free Shipping',
    'badge.tomorrow_at_door': 'Tomorrow At Door',
    'home.popular_products': 'Popular Products',
    'home.special_for_you': 'Special For You',
    'category.all': 'All Categories',
    'hero.deals_every_day': 'Deals Every Day',
    'hero.fearsome_deals': 'Fearsome Deals',
    'hero.featured_campaign': 'FEATURED CAMPAIGN',
    'hero.slide1.title': 'TECHNOLOGY',
    'hero.slide1.subtitle': 'GIANT DEALS',
    'hero.slide1.desc': 'Extra 20% off on latest technology from leading brands.',
    'hero.slide2.title': 'HOME & LIFE',
    'hero.slide2.subtitle': 'NEW SEASON',
    'hero.slide2.desc': 'Super prices on elegant designs and furniture to transform your home.',
    'hero.slide3.title': 'OUTDOOR',
    'hero.slide3.subtitle': 'ADVENTURE BEGINS',
    'hero.slide3.desc': 'Don\'t miss the spring campaign on camping and nature sports products.',
    'mega.best_sellers': 'Best Sellers of the Season',
    'mega.regional_deal': 'Regional Deal',
    'mega.check_now': 'Check Now',
    'mega.select_category': 'Select a category to explore',
    'mega.no_subgroups': 'No subgroups defined in this category.',
    'home.promo_fashion_title': 'NEW SEASON OPPORTUNITIES!',
    'home.promo_sport_title': 'ADVENTURE AWAITS YOU!',
    'home.hero_promo_discover': 'Discover Campaign Products',
    'global.show_more': 'Show More',
    'trust.today_at_door': 'Today at Your Door',
    'trust.safe_payment': 'Secure Payment',
    'trust.easy_return': 'Easy Returns',
    'trust.original': '100% Original',
    'trust.today_at_door_desc': 'Until 14:00',
    'trust.safe_payment_desc': 'Secure Shopping',
    'trust.easy_return_desc': 'Within 14 days',
    'trust.original_desc': 'Benim Olan Assurance',
    'category.camping': 'Camping & Outdoor',
    'category.makeup': 'Makeup Products',
    'category.sportswear': 'Sportswear',
    'category.accessories': 'Accessories',
    'category.living_room': 'Living Room',
    'category.kitchen': 'Kitchen & Dining',
    'footer.corporate': 'Corporate',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.support': 'Support',
    'footer.help': 'Help Center',
    'category.electronics': 'Electronics',
    'category.fashion': 'Fashion',
    'category.home': 'Home & Living',
    'category.supermarket': 'Supermarket',
    'category.beauty': 'Personal Care',
    'category.baby': 'Baby & Mother',
    'category.pet': 'Pet Shop',
    'category.pets': 'Pet Shop',
    'category.auto': 'Auto Parts',
    'category.books': 'Books & Music',
    'category.toys': 'Toys & Hobbies',
    'category.sport': 'Sports & Outdoor',
    'flash.deals': 'Limitless Opportunities',
    'flash.view': 'View Deals',
    'flash.remaining': 'Ends in',
    'nav.hub_active': 'Hub: Active',
    'nav.market_index': 'Market Index',
    'nav.tax_id': 'Tax ID',
    'nav.global_support': 'Global Support',
    'nav.switch_dark': 'Switch to Dark Mode',
    'nav.switch_light': 'Switch to Light Mode',
    'nav.market_dashboard': 'Market Dashboard',
    'nav.my_lists': 'My Lists',
    'nav.watchlist': 'Watchlist',
    'nav.saved_items': 'Saved Items',
    'nav.wallet': 'Global Wallet',
    'nav.seller_hub': 'Seller Hub',
    'nav.admin_hub': 'Admin Hub',
    'nav.logged_in_as': 'Signed in as',
    'nav.login_google': 'Sign In with Google',
    'nav.logout': 'Sign Out',
    'nav.mom_day': 'Mother\'s Day',
    'nav.super_price': 'Super Prices',
    'admin.promotions': 'Sales & Promotions',
    'admin.add_to_list': 'Add to Collection',
    'admin.featured': 'Featured Products',
    'admin.flash_deals': 'Flash Deals',
    'admin.low_stock': 'Low Stock Alerts',
    'admin.curate': 'Curate Catalog',
    'seller.inventory_mgmt': 'Inventory Control',
    'seller.request_feature': 'Promote Product',
    'location.select_title': 'Select Delivery Location',
    'location.city': 'City',
    'location.district': 'District',
    'location.confirm': 'Confirm Location',
    'search.popular': 'Popular Searches',
    'search.products': 'Matching Products',
    'search.featured_category': 'Featured Category',
    'nav.popular_brands': 'Popular Brands',
    'footer.tagline': 'The next-generation global commerce ecosystem connecting artisans to the world via AI-driven compliance and logistics.',
    'footer.commercial_intelligence': 'Commercial Intelligence',
    'footer.tax_avg': 'Global Tax Avg',
    'footer.fixed': 'Fixed',
    'footer.artisan_hub': 'Artisan Hub',
    'footer.fulfillment': 'Fulfillment by Benim Olan',
    'footer.global_taxes': 'Global Taxes',
    'footer.success_stories': 'Success Stories',
    'footer.trust_safety': 'Trust & Safety',
    'footer.escrow_protection': 'Escrow Protection',
    'footer.privacy_policy': 'Privacy Policy',
    'footer.cookie_policy': 'Cookie Policy',
    'footer.terms_of_service': 'Terms of Service',
    'footer.dispute_resolution': 'Dispute Resolution',
    'footer.rights_reserved': 'All rights reserved.',
    'product.description': 'Description',
    'product.specifications': 'Specifications',
    'product.reviews': 'Reviews',
    'product.recently_viewed': 'Recently Viewed',
    'product.you_might_also_like': 'You might also like',
    'product.bought_together': 'Frequently bought together',
    'product.everyone_looking': 'Everyone is looking at these',
    'product.seller_other_products': 'Other products from this seller',
    'product.most_compared': 'Most compared with this product',
    'product.questions_answers': 'Questions & Answers',
    'product.user_reviews': 'User Reviews',
    'product.verified_purchase': 'Verified Purchase',
    'product.useful': 'Useful',
    'auth.error.nameRequired': 'Name is required.',
    'auth.error.invalidCredentials': 'Incorrect email or password.',
    'auth.error.emailInUse': 'This email is already registered.',
    'auth.error.weakPassword': 'Password must be at least 6 characters.',
    'auth.error.generic': 'An error occurred. Please try again.',
    'seller.inventory.bulkStatusUpdated': 'products updated to status',
    'seller.inventory.productUpdated': 'Product updated successfully!',
    'seller.inventory.confirmDelete': 'Are you sure you want to delete this product?',
    'admin.cms.title': 'CMS / Menu Management',
    'admin.cms.saveFailed': 'Error saving category.',
    'admin.cms.deleteFailed': 'Failed to delete category.',
    'admin.languages.title': 'Language Management',
    'admin.languages.subtitle': 'Multi-language settings and translation studio',
    'admin.languages.saved': 'Translations saved successfully.',
    'profile.settings': 'Settings',
    'profile.photo': 'Profile Photo',
    'profile.addresses': 'My Delivery Addresses',
    'profile.followedStores': 'Followed Stores',
    'profile.noFollowedStores': 'No followed stores yet.',
    'profile.unfollow': 'Unfollow',
    'profile.visitStore': 'Visit Store',
    'profile.security': 'Security',
    'profile.notifications': 'Notifications',
    'profile.address.add': 'Add New Address',
    'profile.address.label': 'Label',
    'profile.address.fullName': 'Full Name',
    'profile.address.line1': 'Address Line 1',
    'profile.address.line2': 'Address Line 2 (optional)',
    'profile.address.city': 'City',
    'profile.address.state': 'State / Region',
    'profile.address.postalCode': 'Postal Code',
    'profile.address.country': 'Country',
    'profile.address.phone': 'Phone',
    'profile.address.setDefault': 'Set as default',
    'profile.address.makeDefault': 'Set as Default',
    'profile.address.edit': 'Edit',
    'profile.address.delete': 'Delete',
    'profile.address.default': 'DEFAULT',
    'profile.address.saved': 'addresses saved',
    'profile.address.confirmDelete': 'Remove this address?',
    'profile.changePhoto': 'Change photo',
    'profile.saveChanges': 'Save Changes',
    'profile.sendResetEmail': 'Send Password Reset Email',
    'profile.resetEmailSent': 'Reset email sent! Check your inbox.',
    'form.fullname': 'Full Name',
    'form.email': 'Email Address',
    'form.password': 'Password',
    'form.phone': 'Phone Number',
    'system.order_status.delivered': 'Delivered',
    'system.order_status.in_transit': 'In Transit',
    'system.order_status.preparing': 'Preparing',
    'system.order_status.cancelled': 'Cancelled/Return',
    'system.last_week': 'Last Week',
    'system.last_month': 'Last Month',
    'system.top_selling': 'Top Selling Products',
    'admin.products_tab': 'Product Catalog',
    'admin.sellers_tab': 'Seller Partners',
    'admin.returns_tab': 'Returns',
    'admin.campaigns_tab': 'Campaigns',
    'admin.coupons_tab': 'Coupons & Discounts',
    'admin.finance_tab': 'Finance Tracking',
    'admin.reports_tab': 'Sales Reports',
    'admin.reviews_tab': 'Product Reviews',
    'admin.support_tab': 'Live Support',
    'admin.settings_tab': 'Site Settings',
    'admin.integrations_tab': 'Integrations',
    'admin.ai_tab': 'AI Analysis',
    'coupon.code': 'Coupon Code',
    'coupon.apply': 'Apply',
    'coupon.invalid': 'Invalid or expired coupon',
    'coupon.applied': 'Coupon applied',
    'coupon.discount': 'Discount',
    'coupon.min_order': 'Minimum order amount not met',
    'return.reason': 'Return Reason',
    'return.approve': 'Approve Return',
    'return.reject': 'Reject Return',
    'review.approve': 'Approve',
    'review.reject': 'Reject',
    'homepage.sections': 'Homepage Sections',
    'homepage.hero_slides': 'Hero Banners',
    'homepage.flash_deals': 'Flash Deals',
    'homepage.featured': 'Featured Products',
    'settings.site_name': 'Site Name',
    'settings.maintenance': 'Maintenance Mode',
    'settings.save': 'Save Settings',
    'filter.quickFilters': 'Quick Filters',
    'filter.advantageous': 'Advantageous Products',
    'filter.freeShipping': 'Free Shipping',
    'filter.categories': 'Categories',
    'filter.priceRange': 'Price Range',
    'filter.minRating': 'Minimum Rating',
    'filter.clearAll': 'Clear All',
    'filter.andAbove': '& above',
    'filter.showMore': 'Show more',
    'filter.showLess': 'Show less',
    'filter.search': 'Search',
    'product.inStock': 'In Stock',
    'product.outOfStock': 'Out of Stock',
    'product.addToCart': 'Add to Cart',
    'product.added': 'Added!',
    'product.quickView': 'Quick View',
    'product.freeShipping': 'Free Shipping',
    'profile.overview': 'Overview',
    'profile.orders': 'My Orders',
    'profile.favorites': 'Favorites',
    'profile.noOrders': 'No orders yet',
    'profile.startShopping': 'Start Shopping',
    'profile.totalSpent': 'Total Spent',
    'profile.activeOrders': 'Active Orders',
    'profile.savedItems': 'Saved Items',
    'profile.rewardPoints': 'Reward Points',
    'profile.priceAlerts': 'Price Alerts',
    'profile.noPriceAlerts': 'No price alerts set.',
    'profile.originalPrice': 'Original Price',
    'profile.currentPrice': 'Current Price',
    'profile.removeTrack': 'Stop Tracking',
    'profile.priceDropped': 'Price Dropped!',
    'product.rec.interest.title': 'You Might Also Like',
    'product.rec.interest.sub': 'Other products viewed by shoppers of this item',
    'product.rec.bakanAldi.title': 'Also Bought by Viewers',
    'product.rec.bakanAldi.sub': 'Other products bought by shoppers of this item',
    'product.rec.birlikte.title': 'Frequently Bought Together',
    'product.rec.birlikte.sub': 'Products bought together with this item',
    'product.rec.populer.title': 'Everyone is Looking at These',
    'product.rec.populer.sub': 'Most popular products in this category',
    'product.rec.secilmis.title': 'Curated Popular Items',
    'product.rec.secilmis.sub': 'Popular items curated for you',
    'product.rec.searches.title': 'Popular Searches',
    'seller.guard.applicationRequired': 'Seller Application Required',
    'seller.guard.applicationRequiredDesc': 'You need to apply and get admin approval to access the seller panel.',
    'seller.guard.applyNow': 'Apply as Seller',
    'seller.guard.pending': 'Application Under Review',
    'seller.guard.pendingDesc': 'Your application is being reviewed by our admin team. You can access the seller panel after approval.',
    'seller.guard.rejected': 'Application Rejected',
    'seller.guard.rejectedDesc': 'Your application was not approved. You can reapply with updated information.',
    'seller.guard.reapply': 'Reapply',
    'seller.guard.goHome': 'Go to Home',
    'seller.orders.pendingDispatch': 'Pending Dispatch',
    'seller.orders.inTransit': 'In Transit',
    'seller.orders.ship': 'Ship Order',
    'seller.orders.trackingNumber': 'Tracking Number',
    'seller.orders.carrier': 'Carrier',
    'seller.orders.shippedAt': 'Shipped At',
    'seller.orders.noOrders': 'No orders yet.',
    'cart.empty': 'Your cart is empty',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.remove': 'Remove',
    'cart.continue_shopping': 'Continue Shopping',
    'checkout.shipping': 'Shipping',
    'checkout.payment': 'Payment',
    'checkout.order_summary': 'Order Summary',
    'checkout.place_order': 'Place Order',
    'checkout.subtotal': 'Subtotal',
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.no_results': 'No results found',
    'common.apply': 'Apply',
    'common.back': 'Back',
    'common.next': 'Next',
    'product.out_of_stock': 'Out of Stock',
    'product.in_stock': 'In Stock',
    'product.add_to_cart': 'Add to Cart',
    'product.view_details': 'View Details',
  },
  tr: {
    'nav.deals': "Günün Fırsatları",
    'nav.customerservice': 'Müşteri Hizmetleri',
    'nav.registry': 'Liste',
    'nav.giftcards': 'Hediye Kartları',
    'nav.sell': 'Benim Olan\'da Sat',
    'nav.hello': 'Merhaba, Giriş yap',
    'nav.account': 'Hesap ve Listeler',
    'nav.orders': 'İadeler ve Siparişler',
    'nav.cart': 'Sepet',
    'nav.search_placeholder': "Küresel ürün ara: 'El yapımı SAAT'...",
    'nav.all_categories': 'Tüm Kategoriler',
    'nav.departments': 'Bölümler',
    'nav.deliver_to': 'Gönderim',
    'hero.badge': '2026 Sezon Fırsatları',
    'hero.title': 'Elektronik Artifacts',
    'hero.subtitle': 'Geleceği Keşfet',
    'hero.desc': 'Londra ve İstanbul depo çıkışlı, gümrük masrafları dahil artisan teknoloji koleksiyonu Benim Olan\'da.',
    'hero.cta': 'Hemen İncele',
    'hero.watch': 'Tanıtım İzle',
    'hero.spotlight1.title': 'Küresel Gönderim',
    'hero.spotlight1.desc': 'AB ve BK merkezlerine sabit £12.00 kargo ücreti.',
    'hero.spotlight2.title': 'Artisan Doğrulamalı',
    'hero.spotlight2.desc': 'Her eser küratörlerimiz tarafından denetlenir.',
    'product.origin': 'Menşei',
    'product.delivery': 'Teslimat Şartları',
    'product.buy_now': 'Hemen Al',
    'product.add_cart': 'Sepete Ekle',
    'home.best_sellers': 'En Çok Satanlar',
    'home.for_everyone': 'Bu Ürünler Herkese Göre',
    'home.new_arrivals': 'Yeni Gelenler',
    'global.discover': 'Dünya Pazarını Keşfet',
    'global.see_all': 'Tümünü Gör',
    'market.insight': 'Pazar Analizi',
    'market.trending': 'Yüksek Talep',
    'market.scarcity': 'Stok Alarmı',
    'market.opportunity': 'Küresel Fırsat',
    'logistics.timeline': 'Lojistik Stratejisi',
    'logistics.hub_processing': 'Merkez İşleme',
    'logistics.customs_clearance': 'Gümrük Onayı',
    'logistics.last_mile': 'Son Teslimat',
    'nav.location_select': 'Konum Seç',
    'nav.location_default': 'İstanbul, Kadıköy',
    'nav.my_account': 'Hesabım',
    'nav.login_or_sign_up': 'Giriş yap veya üye ol',
    'nav.cart_count': 'Sepetim',
    'nav.favorite': 'Favorilerim',
    'nav.orders_list': 'Siparişlerim',
    'nav.home_page': 'Ana Sayfa',
    'nav.categories_nav': 'Kategoriler',
    'badge.free_shipping': 'Kargo Bedava',
    'badge.tomorrow_at_door': 'Yarın Kapında',
    'home.popular_products': 'Popüler Ürünler',
    'home.special_for_you': 'Size Özel Seçtiklerimiz',
    'category.all': 'Tüm Kategoriler',
    'hero.deals_every_day': 'Her Gün Yenilenen',
    'hero.fearsome_deals': 'Fırsatlar',
    'hero.featured_campaign': 'ÖNE ÇIKAN KAMPANYA',
    'hero.slide1.title': 'TEKNOLOJİ',
    'hero.slide1.subtitle': 'DEV FIRSATLAR',
    'hero.slide1.desc': 'Lider markaların en yeni teknoloji ürünlerinde sepette ek %20 indirim.',
    'hero.slide2.title': 'EV & YAŞAM',
    'hero.slide2.subtitle': 'YENİ SEZON',
    'hero.slide2.desc': 'Evinizin havasını değiştirecek şık tasarımlar ve mobilyalarda süper fiyatlar.',
    'hero.slide3.title': 'OUTDOOR',
    'hero.slide3.subtitle': 'MACERA BAŞLIYOR',
    'hero.slide3.desc': 'Kamp ve doğa sporları ürünlerinde bahar kampanyasını kaçırma.',
    'mega.best_sellers': 'Sezonun En Çok Satanları',
    'mega.regional_deal': 'Bölgesel Fırsat',
    'mega.check_now': 'Şimdi İncele',
    'mega.select_category': 'Keşfetmek için bir kategori seçin',
    'mega.no_subgroups': 'Bu kategoride henüz alt grup tanımlanmadı.',
    'home.promo_fashion_title': 'YENİ SEZON FIRSATLARI!',
    'home.promo_sport_title': 'MACERA SENİ BEKLİYOR!',
    'home.hero_promo_discover': 'Kampanyalı Ürünleri Keşfet',
    'global.show_more': 'Daha Fazla Gör',
    'trust.today_at_door': 'Bugün Kapında',
    'trust.safe_payment': 'Güvenli Ödeme',
    'trust.easy_return': 'Kolay İade',
    'trust.original': '%100 Orijinal',
    'trust.today_at_door_desc': 'Saat 14:00\'e kadar',
    'trust.safe_payment_desc': 'Güvenli Alışveriş',
    'trust.easy_return_desc': '14 gün içinde',
    'trust.original_desc': 'Benim Olan Güvencesi',
    'category.electronics': 'Elektronik',
    'category.fashion': 'Moda Dünyası',
    'category.home': 'Ev & Yaşam',
    'category.supermarket': 'Süpermarket',
    'category.beauty': 'Kişisel Bakım',
    'category.baby': 'Anne & Bebek',
    'category.pet': 'Pet Shop',
    'category.pets': 'Pet Shop',
    'category.sport': 'Spor & Outdoor',
    'footer.corporate': 'Kurumsal',
    'footer.about': 'Hakkımızda',
    'footer.careers': 'Kariyer',
    'footer.support': 'Destek',
    'footer.help': 'Yardım Merkezi',
    'flash.deals': 'Limitli Süre',
    'flash.view': 'Fırsatları Gör',
    'flash.remaining': 'Sona Ermesine',
    'nav.hub_active': 'Merkezi: Aktif',
    'nav.market_index': 'Pazar Endeksi',
    'nav.tax_id': 'Vergi Kimlik No',
    'nav.global_support': 'Global Destek',
    'nav.switch_dark': 'Karanlık Moda Geç',
    'nav.switch_light': 'Aydınlık Moda Geç',
    'nav.market_dashboard': 'Pazar Paneli',
    'nav.my_lists': 'Listelerim',
    'nav.watchlist': 'Takip Listesi',
    'nav.saved_items': 'Kaydedilenler',
    'nav.wallet': 'Cüzdanım',
    'nav.seller_hub': 'Satıcı Paneli',
    'nav.admin_hub': 'Yönetici Paneli',
    'nav.logged_in_as': 'Olarak giriş yapıldı',
    'nav.login_google': 'Google ile Giriş Yap',
    'nav.logout': 'Çıkış Yap',
    'nav.mom_day': 'Anneler Günü',
    'nav.super_price': 'Süper Fiyatlar',
    'category.auto': 'Oto Aksesuar',
    'category.books': 'Kitap & Müzik',
    'category.toys': 'Oyuncak & Hobi',
    'admin.promotions': 'Satış ve Kampanyalar',
    'admin.add_to_list': 'Listeye Ekle',
    'admin.featured': 'Öne Çıkan Ürünler',
    'admin.flash_deals': 'Flaş Fırsatlar',
    'admin.low_stock': 'Düşük Stok Uyarıları',
    'admin.curate': 'Kataloğu Yönet',
    'seller.inventory_mgmt': 'Envanter Kontrolü',
    'seller.request_feature': 'Ürünü Öne Çıkar',
    'location.select_title': 'Teslimat Konumu Seçin',
    'location.city': 'Şehir',
    'location.district': 'İlçe',
    'location.confirm': 'Konumu Onayla',
    'search.popular': 'Popüler Aramalar',
    'search.products': 'Eşleşen Ürünler',
    'search.featured_category': 'Öne Çıkan Kategori',
    'nav.popular_brands': 'Popüler Markalar',
    'footer.tagline': 'Zanaatkarları yapay zeka destekli uyumluluk ve lojistik yoluyla dünyaya bağlayan yeni nesil küresel ticaret ekosistemi.',
    'footer.commercial_intelligence': 'Ticari Zeka',
    'footer.tax_avg': 'Küresel Vergi Ort.',
    'footer.fixed': 'Sabit',
    'footer.artisan_hub': 'Zanaatkar Merkezi',
    'footer.fulfillment': 'Benim Olan Lojistik',
    'footer.global_taxes': 'Küresel Vergiler',
    'footer.success_stories': 'Başarı Hikayeleri',
    'footer.trust_safety': 'Güven ve Güvenlik',
    'footer.escrow_protection': 'Emanet Koruması',
    'footer.privacy_policy': 'Gizlilik Politikası',
    'footer.cookie_policy': 'Çerez Politikası',
    'footer.terms_of_service': 'Kullanım Koşulları',
    'footer.dispute_resolution': 'Uyuşmazlık Çözümü',
    'footer.rights_reserved': 'Tüm hakları saklıdır.',
    'product.description': 'Ürün Açıklaması',
    'product.specifications': 'Ürün Özellikleri',
    'product.reviews': 'Değerlendirmeler',
    'product.recently_viewed': 'Son Gezdikleriniz',
    'product.you_might_also_like': 'Bunlar da ilginizi çekebilir',
    'product.bought_together': 'Birlikte alınan ürünler',
    'product.everyone_looking': 'Herkes bunlara bakıyor',
    'product.seller_other_products': 'Bu satıcının diğer ürünleri',
    'product.most_compared': 'En çok karşılaştırılanlar',
    'product.questions_answers': 'Soru & Cevap',
    'product.user_reviews': 'Kullanıcı Yorumları',
    'product.verified_purchase': 'Onaylanmış Alışveriş',
    'product.useful': 'Faydalı',
    'auth.error.nameRequired': 'İsim zorunludur.',
    'auth.error.invalidCredentials': 'E-posta veya şifre hatalı.',
    'auth.error.emailInUse': 'Bu e-posta zaten kayıtlı.',
    'auth.error.weakPassword': 'Şifre en az 6 karakter olmalı.',
    'auth.error.generic': 'Bir hata oluştu. Lütfen tekrar deneyin.',
    'seller.inventory.bulkStatusUpdated': 'ürün güncellendi — durum:',
    'seller.inventory.productUpdated': 'Ürün başarıyla güncellendi!',
    'seller.inventory.confirmDelete': 'Bu ürünü silmek istediğinizden emin misiniz?',
    'admin.cms.title': 'CMS / Menü Yönetimi',
    'admin.cms.saveFailed': 'Kategori kaydedilirken hata oluştu.',
    'admin.cms.deleteFailed': 'Kategori silinemedi.',
    'admin.languages.title': 'Dil Yönetimi',
    'admin.languages.subtitle': 'Çoklu dil seçeneği ayarları ve çeviri stüdyosu',
    'admin.languages.saved': 'Çeviriler başarıyla kaydedildi.',
    'profile.settings': 'Ayarlar',
    'profile.photo': 'Profil Fotoğrafı',
    'profile.addresses': 'Teslimat Adreslerim',
    'profile.followedStores': 'Takip Ettiğim Mağazalar',
    'profile.noFollowedStores': 'Henüz takip ettiğiniz bir mağaza bulunmuyor.',
    'profile.unfollow': 'Takibi Bırak',
    'profile.visitStore': 'Mağazayı Gör',
    'profile.security': 'Güvenlik',
    'profile.notifications': 'Bildirimler',
    'profile.address.add': 'Yeni Adres Ekle',
    'profile.address.label': 'Etiket',
    'profile.address.fullName': 'Ad Soyad',
    'profile.address.line1': 'Adres Satırı 1',
    'profile.address.line2': 'Adres Satırı 2 (opsiyonel)',
    'profile.address.city': 'Şehir',
    'profile.address.state': 'İlçe / Bölge',
    'profile.address.postalCode': 'Posta Kodu',
    'profile.address.country': 'Ülke',
    'profile.address.phone': 'Telefon',
    'profile.address.setDefault': 'Varsayılan yap',
    'profile.address.makeDefault': 'Varsayılan Yap',
    'profile.address.edit': 'Düzenle',
    'profile.address.delete': 'Sil',
    'profile.address.default': 'VARSAYILAN',
    'profile.address.saved': 'adres kayıtlı',
    'profile.address.confirmDelete': 'Bu adres silinsin mi?',
    'profile.changePhoto': 'Fotoğrafı değiştir',
    'profile.saveChanges': 'Değişiklikleri Kaydet',
    'profile.sendResetEmail': 'Şifre Sıfırlama E-postası Gönder',
    'profile.resetEmailSent': 'Sıfırlama e-postası gönderildi! Gelen kutunuzu kontrol edin.',
    'category.camping': 'Kamp & Outdoor',
    'category.makeup': 'Makyaj Ürünleri',
    'category.sportswear': 'Spor Giyim',
    'category.accessories': 'Aksesuar',
    'category.living_room': 'Oturma Odası',
    'category.kitchen': 'Mutfak & Sofra',
    'form.fullname': 'Ad Soyad',
    'form.email': 'E-posta adresi',
    'form.password': 'Şifre',
    'form.phone': 'Telefon Numarası',
    'system.order_status.delivered': 'Teslim Edildi',
    'system.order_status.in_transit': 'Kargoda',
    'system.order_status.preparing': 'Hazırlanıyor',
    'system.order_status.cancelled': 'İptal/İade',
    'system.last_week': 'Geçen Hafta',
    'system.last_month': 'Geçen Ay',
    'system.top_selling': 'En Çok Satan Ürünler',
    'admin.products_tab': 'Ürün Kataloğu',
    'admin.sellers_tab': 'Satıcı Ortakları',
    'admin.returns_tab': 'İadeler',
    'admin.campaigns_tab': 'Kampanyalar',
    'admin.coupons_tab': 'Kupon & İndirim',
    'admin.finance_tab': 'Finans Takibi',
    'admin.reports_tab': 'Satış Raporları',
    'admin.reviews_tab': 'Ürün Değerlendirme',
    'admin.support_tab': 'Canlı Destek',
    'admin.settings_tab': 'Site Ayarları',
    'admin.integrations_tab': 'Entegrasyonlar',
    'admin.ai_tab': 'Yapay Zeka Analizi',
    'coupon.code': 'Kupon Kodu',
    'coupon.apply': 'Uygula',
    'coupon.invalid': 'Geçersiz veya süresi dolmuş kupon',
    'coupon.applied': 'Kupon uygulandı',
    'coupon.discount': 'İndirim',
    'coupon.min_order': 'Minimum sipariş tutarı karşılanmıyor',
    'return.reason': 'İade Sebebi',
    'return.approve': 'İadeyi Onayla',
    'return.reject': 'İadeyi Reddet',
    'review.approve': 'Onayla',
    'review.reject': 'Reddet',
    'homepage.sections': 'Anasayfa Bölümleri',
    'homepage.hero_slides': 'Hero Bannerları',
    'homepage.flash_deals': 'Flaş Fırsatlar',
    'homepage.featured': 'Öne Çıkan Ürünler',
    'settings.site_name': 'Site Adı',
    'settings.maintenance': 'Bakım Modu',
    'settings.save': 'Ayarları Kaydet',
    'filter.quickFilters': 'Hızlı Filtreler',
    'filter.advantageous': 'Avantajlı Ürünler',
    'filter.freeShipping': 'Kargo Bedava',
    'filter.categories': 'Kategoriler',
    'filter.priceRange': 'Fiyat Aralığı',
    'filter.minRating': 'Minimum Puan',
    'filter.clearAll': 'Tümünü Temizle',
    'filter.andAbove': '& üzeri',
    'filter.showMore': 'Daha fazla göster',
    'filter.showLess': 'Daha az göster',
    'filter.search': 'Ara',
    'product.inStock': 'Stokta Var',
    'product.outOfStock': 'Stokta Yok',
    'product.addToCart': 'Sepete Ekle',
    'product.added': 'Eklendi!',
    'product.quickView': 'Hızlı Gözat',
    'product.freeShipping': 'Ücretsiz Kargo',
    'profile.overview': 'Genel Bakış',
    'profile.orders': 'Siparişlerim',
    'profile.favorites': 'Favorilerim',
    'profile.noOrders': 'Henüz sipariş yok',
    'profile.startShopping': 'Alışverişe Başla',
    'profile.totalSpent': 'Toplam Harcama',
    'profile.activeOrders': 'Aktif Siparişler',
    'profile.savedItems': 'Kaydedilenler',
    'profile.rewardPoints': 'Puan',
    'profile.priceAlerts': 'Fiyat Takibi',
    'profile.noPriceAlerts': 'Fiyat takibi yapılan ürün bulunmuyor.',
    'profile.originalPrice': 'İlk Fiyat',
    'profile.currentPrice': 'Güncel Fiyat',
    'profile.removeTrack': 'Takibi Bırak',
    'profile.priceDropped': 'Fiyatı Düştü!',
    'product.rec.interest.title': 'Bunlar da İlgini Çekebilir',
    'product.rec.interest.sub': 'Ürünü inceleyenlerin baktığı diğer ürünler',
    'product.rec.bakanAldi.title': 'Buna Bakanların Aldıkları',
    'product.rec.bakanAldi.sub': 'Ürünü inceleyenlerin aldığı diğer ürünler',
    'product.rec.birlikte.title': 'Birlikte Alınanlar',
    'product.rec.birlikte.sub': 'Beraber alınan ürünler',
    'product.rec.populer.title': 'Herkes Bunlara Bakıyor',
    'product.rec.populer.sub': 'Kategorinin en popüler ürünleri',
    'product.rec.secilmis.title': 'Popüler Ürünlerden Seçtik',
    'product.rec.secilmis.sub': 'Sizin için seçilen popüler ürünler',
    'product.rec.searches.title': 'Popüler Aramalar',
    'seller.guard.applicationRequired': 'Satıcı Başvurusu Gerekli',
    'seller.guard.applicationRequiredDesc': 'Satıcı paneline erişmek için önce başvuru yapmanız ve admin onayı almanız gerekiyor.',
    'seller.guard.applyNow': 'Satıcı Başvurusu Yap',
    'seller.guard.pending': 'Başvurunuz İnceleniyor',
    'seller.guard.pendingDesc': 'Başvurunuz admin ekibimiz tarafından incelenmektedir. Onay sonrası satıcı panelinize erişebileceksiniz.',
    'seller.guard.rejected': 'Başvurunuz Reddedildi',
    'seller.guard.rejectedDesc': 'Başvurunuz onaylanmadı. Bilgilerinizi güncelleyerek yeniden başvurabilirsiniz.',
    'seller.guard.reapply': 'Yeniden Başvur',
    'seller.guard.goHome': 'Ana Sayfaya Dön',
    'seller.orders.pendingDispatch': 'Bekleyen Gönderim',
    'seller.orders.inTransit': 'Kargoda',
    'seller.orders.ship': 'Kargoya Ver',
    'seller.orders.trackingNumber': 'Takip Numarası',
    'seller.orders.carrier': 'Kargo Firması',
    'seller.orders.shippedAt': 'Kargoya Verildi',
    'seller.orders.noOrders': 'Henüz sipariş bulunmuyor.',
    'cart.empty': 'Sepetiniz boş',
    'cart.total': 'Toplam',
    'cart.checkout': 'Ödemeye Geç',
    'cart.remove': 'Kaldır',
    'cart.continue_shopping': 'Alışverişe Devam',
    'checkout.shipping': 'Kargo',
    'checkout.payment': 'Ödeme',
    'checkout.order_summary': 'Sipariş Özeti',
    'checkout.place_order': 'Siparişi Tamamla',
    'checkout.subtotal': 'Ara Toplam',
    'common.loading': 'Yükleniyor...',
    'common.save': 'Kaydet',
    'common.cancel': 'İptal',
    'common.close': 'Kapat',
    'common.search': 'Ara',
    'common.no_results': 'Sonuç bulunamadı',
    'common.apply': 'Uygula',
    'common.back': 'Geri',
    'common.next': 'İleri',
    'product.out_of_stock': 'Stokta Yok',
    'product.in_stock': 'Stokta Var',
    'product.add_to_cart': 'Sepete Ekle',
    'product.view_details': 'Detayları Gör',
  },
  de: {
    'nav.deals': "Tagesangebote",
    'nav.customerservice': 'Kundenservice',
    'nav.registry': 'Liste',
    'nav.giftcards': 'Geschenkkarten',
    'nav.sell': 'Auf Benim Olan verkaufen',
    'nav.hello': 'Hallo, Anmelden',
    'nav.account': 'Konto & Listen',
    'nav.orders': 'Retouren & Bestellungen',
    'nav.cart': 'Einkaufswagen',
    'nav.search_placeholder': "Produkte weltweit suchen...",
    'nav.all_categories': 'Alle Kategorien',
    'hero.badge': '2026 Saisonangebote',
    'hero.title': 'Elektronische Artefakte',
    'hero.cta': 'Entdecken',
    'home.best_sellers': 'Bestseller',
    'auth.error.nameRequired': 'Name ist erforderlich.',
    'auth.error.invalidCredentials': 'E-Mail oder Passwort falsch.',
    'auth.error.emailInUse': 'Diese E-Mail ist bereits registriert.',
    'auth.error.weakPassword': 'Passwort muss mindestens 6 Zeichen haben.',
    'auth.error.generic': 'Ein Fehler ist aufgetreten. Bitte erneut versuchen.',
    'seller.inventory.bulkStatusUpdated': 'Produkte aktualisiert auf Status',
    'seller.inventory.productUpdated': 'Produkt erfolgreich aktualisiert!',
    'seller.inventory.confirmDelete': 'Möchten Sie dieses Produkt wirklich löschen?',
    'admin.cms.title': 'CMS / Menü-Verwaltung',
    'admin.cms.saveFailed': 'Fehler beim Speichern der Kategorie.',
    'admin.cms.deleteFailed': 'Kategorie konnte nicht gelöscht werden.',
    'admin.languages.title': 'Sprachverwaltung',
    'admin.languages.subtitle': 'Mehrsprachige Einstellungen und Übersetzungsstudio',
    'admin.languages.saved': 'Übersetzungen erfolgreich gespeichert.',
    'profile.settings': 'Einstellungen',
    'profile.photo': 'Profilfoto',
    'profile.addresses': 'Lieferadressen',
    'profile.followedStores': 'Gefolgte Geschäfte',
    'profile.noFollowedStores': 'Noch keine gefolgten Geschäfte.',
    'profile.unfollow': 'Entfolgen',
    'profile.visitStore': 'Geschäft besuchen',
    'profile.security': 'Sicherheit',
    'profile.notifications': 'Benachrichtigungen',
    'profile.address.add': 'Neue Adresse hinzufügen',
    'profile.address.label': 'Bezeichnung',
    'profile.address.fullName': 'Vollständiger Name',
    'profile.address.line1': 'Adresszeile 1',
    'profile.address.line2': 'Adresszeile 2 (optional)',
    'profile.address.city': 'Stadt',
    'profile.address.state': 'Bundesland / Region',
    'profile.address.postalCode': 'Postleitzahl',
    'profile.address.country': 'Land',
    'profile.address.phone': 'Telefon',
    'profile.address.setDefault': 'Als Standard festlegen',
    'profile.address.makeDefault': 'Als Standard festlegen',
    'profile.address.edit': 'Bearbeiten',
    'profile.address.delete': 'Löschen',
    'profile.address.default': 'STANDARD',
    'profile.address.saved': 'Adressen gespeichert',
    'profile.address.confirmDelete': 'Diese Adresse entfernen?',
    'profile.changePhoto': 'Foto ändern',
    'profile.saveChanges': 'Änderungen speichern',
    'profile.sendResetEmail': 'Passwort-Reset-E-Mail senden',
    'profile.resetEmailSent': 'Reset-E-Mail gesendet! Posteingang prüfen.',
    'category.camping': 'Camping & Outdoor',
    'category.makeup': 'Make-up-Produkte',
    'category.sportswear': 'Sportbekleidung',
    'category.accessories': 'Zubehör',
    'category.living_room': 'Wohnzimmer',
    'category.kitchen': 'Küche & Esszimmer',
    'form.fullname': 'Vollständiger Name',
    'form.email': 'E-Mail-Adresse',
    'form.password': 'Passwort',
    'form.phone': 'Telefonnummer',
    'coupon.code': 'Gutscheincode',
    'coupon.apply': 'Anwenden',
    'coupon.invalid': 'Ungültiger oder abgelaufener Gutschein',
    'coupon.applied': 'Gutschein angewendet',
    'coupon.min_order': 'Mindestbestellbetrag nicht erreicht',
    'product.buy_now': 'Jetzt kaufen',
    'product.add_to_cart': 'In den Warenkorb',
    'global.see_all': 'Alle ansehen',
    'global.discover': 'Entdecken',
    'system.order_status.delivered': 'Geliefert',
    'system.order_status.in_transit': 'Unterwegs',
    'system.order_status.preparing': 'In Vorbereitung',
    'system.order_status.cancelled': 'Storniert/Rücksendung',
    'settings.site_name': 'Websitename',
    'settings.maintenance': 'Wartungsmodus',
    'settings.save': 'Einstellungen speichern',
    'review.approve': 'Genehmigen',
    'review.reject': 'Ablehnen',
    'return.approve': 'Rücksendung genehmigen',
    'return.reject': 'Rücksendung ablehnen',
    'nav.home_page': 'Startseite',
    'auth.signin': 'Anmelden',
    'auth.signup': 'Registrieren',
    'auth.signout': 'Abmelden',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.name': 'Name',
    'auth.register': 'Registrieren',
    'auth.signin_with_google': 'Mit Google anmelden',
    'hero.featured_campaign': 'Ausgewählte Kampagne',
    'nav.departments': 'Abteilungen',
    'nav.deliver_to': 'Liefern nach',
    'nav.location_select': 'Standort auswählen',
    'nav.location_default': 'Istanbul, Kadikoy',
    'nav.my_account': 'Mein Konto',
    'nav.login_or_sign_up': 'Anmelden oder Registrieren',
    'nav.cart_count': 'Warenkorb',
    'nav.favorite': 'Favoriten',
    'nav.orders_list': 'Meine Bestellungen',
    'nav.categories_nav': 'Kategorien',
    'nav.hub_active': 'Hub: Aktiv',
    'nav.market_index': 'Marktindex',
    'nav.tax_id': 'Steuer-ID',
    'nav.global_support': 'Globaler Support',
    'nav.switch_dark': 'Dunkelmodus aktivieren',
    'nav.switch_light': 'Hellmodus aktivieren',
    'nav.market_dashboard': 'Markt-Dashboard',
    'nav.my_lists': 'Meine Listen',
    'nav.watchlist': 'Beobachtungsliste',
    'nav.saved_items': 'Gespeicherte Artikel',
    'nav.wallet': 'Globale Geldbörse',
    'nav.seller_hub': 'Verkäufer-Hub',
    'nav.admin_hub': 'Admin-Hub',
    'nav.logged_in_as': 'Angemeldet als',
    'nav.login_google': 'Mit Google anmelden',
    'nav.logout': 'Abmelden',
    'nav.mom_day': 'Muttertag',
    'nav.super_price': 'Superpreise',
    'nav.popular_brands': 'Beliebte Marken',
    'hero.subtitle': 'Die Zukunft entdecken',
    'hero.desc': 'Handverlesene Handwerker-Technologiekollektion aus Londoner und Istanbuler Lagern, alle Zollgebühren inklusive.',
    'hero.watch': 'Promo ansehen',
    'hero.spotlight1.title': 'Globaler Versand',
    'hero.spotlight1.desc': 'Pauschalpreis £12,00 in EU- und UK-Hubs.',
    'hero.deals_every_day': 'Täglich Angebote',
    'hero.fearsome_deals': 'Unschlagbare Deals',
    'hero.slide1.title': 'TECHNOLOGIE',
    'hero.slide1.subtitle': 'RIESENRABATTE',
    'hero.slide1.desc': 'Extra 20% Rabatt auf neueste Technik führender Marken.',
    'hero.slide2.title': 'ZUHAUSE & LEBEN',
    'hero.slide2.subtitle': 'NEUE SAISON',
    'hero.slide2.desc': 'Superpreise auf elegante Designs und Möbel für Ihr Zuhause.',
    'hero.slide3.title': 'OUTDOOR',
    'hero.slide3.subtitle': 'ABENTEUER BEGINNT',
    'hero.slide3.desc': 'Die Frühlingsaktion für Camping- und Natursportprodukte nicht verpassen.',
    'product.origin': 'Herkunft',
    'product.delivery': 'Lieferbedingungen',
    'product.add_cart': 'In den Warenkorb',
    'product.description': 'Beschreibung',
    'product.specifications': 'Spezifikationen',
    'product.reviews': 'Bewertungen',
    'product.recently_viewed': 'Kürzlich Angesehen',
    'product.you_might_also_like': 'Das könnte Ihnen gefallen',
    'product.bought_together': 'Wird oft zusammen gekauft',
    'product.everyone_looking': 'Alle schauen sich das an',
    'product.seller_other_products': 'Andere Produkte dieses Verkäufers',
    'product.most_compared': 'Am häufigsten verglichen',
    'product.questions_answers': 'Fragen & Antworten',
    'product.user_reviews': 'Nutzerbewertungen',
    'product.verified_purchase': 'Verifizierter Kauf',
    'product.useful': 'Hilfreich',
    'home.for_everyone': 'Produkte für alle',
    'home.new_arrivals': 'Neuankömmlinge',
    'home.popular_products': 'Beliebte Produkte',
    'home.special_for_you': 'Speziell für Sie',
    'home.promo_fashion_title': 'NEUE SAISON ANGEBOTE!',
    'home.promo_sport_title': 'ABENTEUER WARTET!',
    'home.hero_promo_discover': 'Aktionsprodukte entdecken',
    'mega.best_sellers': 'Bestseller der Saison',
    'mega.regional_deal': 'Regionales Angebot',
    'mega.check_now': 'Jetzt ansehen',
    'mega.select_category': 'Kategorie zum Erkunden auswählen',
    'mega.no_subgroups': 'Keine Untergruppen definiert.',
    'global.show_more': 'Mehr anzeigen',
    'trust.today_at_door': 'Heute bei Ihnen',
    'trust.safe_payment': 'Sicheres Bezahlen',
    'trust.easy_return': 'Einfache Rückgabe',
    'trust.original': '100% Original',
    'trust.today_at_door_desc': 'Bis 14:00 Uhr',
    'trust.safe_payment_desc': 'Sicheres Einkaufen',
    'trust.easy_return_desc': 'Innerhalb von 14 Tagen',
    'trust.original_desc': 'Benim Olan Garantie',
    'category.all': 'Alle Kategorien',
    'category.electronics': 'Elektronik',
    'category.fashion': 'Mode',
    'category.home': 'Haus & Garten',
    'category.supermarket': 'Supermarkt',
    'category.beauty': 'Schönheitspflege',
    'category.baby': 'Baby & Mutter',
    'category.pet': 'Tiershop',
    'category.pets': 'Tiershop',
    'category.auto': 'Autoteile',
    'category.books': 'Bücher & Musik',
    'category.toys': 'Spielzeug & Hobbys',
    'category.sport': 'Sport & Outdoor',
    'badge.free_shipping': 'Kostenloser Versand',
    'badge.tomorrow_at_door': 'Morgen an der Tür',
    'market.insight': 'Markteinblicke',
    'market.trending': 'Hohe Nachfrage',
    'market.scarcity': 'Lagerwarnung',
    'market.opportunity': 'Globale Chance',
    'logistics.timeline': 'Logistikstrategie',
    'logistics.hub_processing': 'Hub-Verarbeitung',
    'logistics.customs_clearance': 'Zollfreigabe',
    'logistics.last_mile': 'Letzte Meile',
    'flash.deals': 'Grenzenlose Angebote',
    'flash.view': 'Angebote ansehen',
    'flash.remaining': 'Endet in',
    'admin.promotions': 'Verkauf & Aktionen',
    'admin.add_to_list': 'Zur Sammlung hinzufügen',
    'admin.featured': 'Ausgewählte Produkte',
    'admin.flash_deals': 'Flash Deals',
    'admin.low_stock': 'Niedrige Lagerbestände',
    'admin.curate': 'Katalog kuratieren',
    'admin.products_tab': 'Produktkatalog',
    'admin.sellers_tab': 'Händlerpartner',
    'admin.returns_tab': 'Rücksendungen',
    'admin.campaigns_tab': 'Kampagnen',
    'admin.coupons_tab': 'Gutscheine & Rabatte',
    'admin.finance_tab': 'Finanzverfolgung',
    'admin.reports_tab': 'Verkaufsberichte',
    'admin.reviews_tab': 'Produktbewertungen',
    'admin.support_tab': 'Live-Support',
    'admin.settings_tab': 'Websiteeinstellungen',
    'admin.integrations_tab': 'Integrationen',
    'admin.ai_tab': 'KI-Analyse',
    'seller.inventory_mgmt': 'Bestandsverwaltung',
    'seller.request_feature': 'Produkt bewerben',
    'seller.dashboard': 'Händler-Dashboard',
    'seller.inventory': 'Lager',
    'seller.orders': 'Bestellungen',
    'seller.revenue': 'Umsatz',
    'seller.products': 'Produkte',
    'location.select_title': 'Lieferort auswählen',
    'location.city': 'Stadt',
    'location.district': 'Bezirk',
    'location.confirm': 'Standort bestätigen',
    'search.popular': 'Beliebte Suchen',
    'search.products': 'Passende Produkte',
    'search.featured_category': 'Ausgewählte Kategorie',
    'footer.corporate': 'Unternehmen',
    'footer.about': 'Über uns',
    'footer.careers': 'Karriere',
    'footer.support': 'Support',
    'footer.help': 'Hilfezentrum',
    'footer.tagline': 'Das Ökosystem der nächsten Generation für den globalen Handel.',
    'footer.commercial_intelligence': 'Handelsintelligenz',
    'footer.tax_avg': 'Globaler Steuerdurchschnitt',
    'footer.fixed': 'Fest',
    'footer.artisan_hub': 'Handwerker-Hub',
    'footer.fulfillment': 'Fulfillment by Benim Olan',
    'footer.global_taxes': 'Globale Steuern',
    'footer.success_stories': 'Erfolgsgeschichten',
    'footer.trust_safety': 'Vertrauen & Sicherheit',
    'footer.escrow_protection': 'Treuhandschutz',
    'footer.privacy_policy': 'Datenschutzrichtlinie',
    'footer.cookie_policy': 'Cookie-Richtlinie',
    'footer.terms_of_service': 'Nutzungsbedingungen',
    'footer.dispute_resolution': 'Streitbeilegung',
    'footer.rights_reserved': 'Alle Rechte vorbehalten.',
    'coupon.discount': 'Rabatt',
    'return.reason': 'Rückgabegrund',
    'homepage.sections': 'Homepage-Abschnitte',
    'homepage.hero_slides': 'Hero-Banner',
    'homepage.flash_deals': 'Flash Deals',
    'homepage.featured': 'Ausgewählte Produkte',
    'system.last_week': 'Letzte Woche',
    'system.last_month': 'Letzter Monat',
    'system.top_selling': 'Meistverkaufte Produkte',
    'auth.forgot_password': 'Passwort vergessen',
    'auth.no_account': 'Kein Konto? Registrieren',
    'auth.have_account': 'Bereits ein Konto? Anmelden',
    'auth.continue_with_google': 'Mit Google fortfahren',
    'auth.or': 'oder',
    'auth.confirm_password': 'Passwort bestätigen',
    'cart.empty': 'Ihr Warenkorb ist leer',
    'cart.total': 'Gesamt',
    'cart.checkout': 'Zur Kasse',
    'cart.remove': 'Entfernen',
    'checkout.shipping': 'Versand',
    'checkout.payment': 'Zahlung',
    'checkout.order_summary': 'Bestellübersicht',
    'checkout.place_order': 'Bestellung aufgeben',
    'wishlist.title': 'Meine Wunschliste',
    'wishlist.empty': 'Keine Produkte in der Wunschliste',
    'wishlist.add': 'Zur Wunschliste hinzufügen',
    'wishlist.remove': 'Von der Wunschliste entfernen',
    'order.tracking': 'Bestellverfolgung',
    'order.placed': 'Bestellt',
    'order.confirmed': 'Bestätigt',
    'order.preparing': 'In Vorbereitung',
    'order.shipped': 'Versendet',
    'order.delivered': 'Geliefert',
    'order.cancelled': 'Storniert',
    'filter.quickFilters': 'Schnellfilter',
    'filter.advantageous': 'Vorteilhafte Produkte',
    'filter.freeShipping': 'Kostenloser Versand',
    'filter.categories': 'Kategorien',
    'filter.priceRange': 'Preisbereich',
    'filter.minRating': 'Mindestbewertung',
    'filter.clearAll': 'Alle löschen',
    'filter.andAbove': '& darüber',
    'filter.showMore': 'Mehr anzeigen',
    'filter.showLess': 'Weniger anzeigen',
    'filter.search': 'Suche',
    'product.inStock': 'Auf Lager',
    'product.outOfStock': 'Ausverkauft',
    'product.addToCart': 'In den Warenkorb',
    'product.added': 'Hinzugefügt!',
    'product.quickView': 'Schnellansicht',
    'product.freeShipping': 'Kostenloser Versand',
    'profile.overview': 'Übersicht',
    'profile.orders': 'Meine Bestellungen',
    'profile.favorites': 'Favoriten',
    'profile.noOrders': 'Noch keine Bestellungen',
    'profile.startShopping': 'Jetzt einkaufen',
    'profile.totalSpent': 'Gesamtausgaben',
    'profile.activeOrders': 'Aktive Bestellungen',
    'profile.savedItems': 'Gespeicherte Artikel',
    'profile.rewardPoints': 'Punkte',
    'profile.priceAlerts': 'Preisalarme',
    'profile.noPriceAlerts': 'Keine Preisalarme eingerichtet.',
    'profile.originalPrice': 'Originalpreis',
    'profile.currentPrice': 'Aktueller Preis',
    'profile.removeTrack': 'Verfolgung beenden',
    'profile.priceDropped': 'Preis gesunken!',
    'product.rec.interest.title': 'Das könnte Ihnen gefallen',
    'product.rec.interest.sub': 'Andere Produkte, die von Käufern dieses Artikels angesehen wurden',
    'product.rec.bakanAldi.title': 'Auch von Betrachtern gekauft',
    'product.rec.bakanAldi.sub': 'Andere Produkte, die von Käufern dieses Artikels gekauft wurden',
    'product.rec.birlikte.title': 'Wird oft zusammen gekauft',
    'product.rec.birlikte.sub': 'Zusammen gekaufte Produkte mit diesem Artikel',
    'product.rec.populer.title': 'Alle schauen sich das an',
    'product.rec.populer.sub': 'Beliebteste Produkte in dieser Kategorie',
    'product.rec.secilmis.title': 'Beliebte Artikel für Sie',
    'product.rec.secilmis.sub': 'Beliebte Artikel für Sie ausgewählt',
    'product.rec.searches.title': 'Beliebte Suchen',
  },
  ar: {
    'nav.deals': "عروض اليوم",
    'nav.customerservice': 'خدمة العملاء',
    'nav.registry': 'قائمة السجل',
    'nav.giftcards': 'بطاقات هدايا',
    'nav.sell': 'البيع على ميركورا',
    'nav.hello': 'مرحباً، تسجيل الدخول',
    'nav.account': 'الحساب والقوائم',
    'nav.orders': 'المرتجعات والطلبات',
    'nav.cart': 'عربة التسوق',
    'nav.search_placeholder': "ابحث عن المنتجات عالمياً...",
    'nav.all_categories': 'كل الفئات',
    'hero.badge': 'عروض موسم 2026',
    'hero.title': 'تحف إلكترونية',
    'hero.cta': 'اكتشف',
    'home.best_sellers': 'الأكثر مبيعاً',
    'auth.error.nameRequired': 'الاسم مطلوب.',
    'auth.error.invalidCredentials': 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
    'auth.error.emailInUse': 'هذا البريد الإلكتروني مسجل بالفعل.',
    'auth.error.weakPassword': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل.',
    'auth.error.generic': 'حدث خطأ. يرجى المحاولة مرة أخرى.',
    'seller.inventory.bulkStatusUpdated': 'تم تحديث المنتجات',
    'seller.inventory.productUpdated': 'تم تحديث المنتج بنجاح!',
    'seller.inventory.confirmDelete': 'هل أنت متأكد من حذف هذا المنتج؟',
    'admin.cms.title': 'إدارة المحتوى',
    'admin.cms.saveFailed': 'خطأ في حفظ الفئة.',
    'admin.cms.deleteFailed': 'فشل حذف الفئة.',
    'admin.languages.title': 'إدارة اللغات',
    'admin.languages.subtitle': 'إعدادات متعددة اللغات واستوديو الترجمة',
    'admin.languages.saved': 'تم حفظ الترجمات بنجاح.',
    'profile.settings': 'الإعدادات',
    'profile.photo': 'صورة الملف الشخصي',
    'profile.addresses': 'عناوين التوصيل',
    'profile.followedStores': 'المتاجر المتابعة',
    'profile.noFollowedStores': 'لا توجد متاجر متابعة بعد.',
    'profile.unfollow': 'إلغاء المتابعة',
    'profile.visitStore': 'زيارة المتجر',
    'profile.security': 'الأمان',
    'profile.notifications': 'الإشعارات',
    'profile.address.add': 'إضافة عنوان جديد',
    'profile.address.label': 'التسمية',
    'profile.address.fullName': 'الاسم الكامل',
    'profile.address.line1': 'سطر العنوان 1',
    'profile.address.line2': 'سطر العنوان 2 (اختياري)',
    'profile.address.city': 'المدينة',
    'profile.address.state': 'المنطقة',
    'profile.address.postalCode': 'الرمز البريدي',
    'profile.address.country': 'البلد',
    'profile.address.phone': 'الهاتف',
    'profile.address.setDefault': 'تعيين كافتراضي',
    'profile.address.makeDefault': 'تعيين كافتراضي',
    'profile.address.edit': 'تعديل',
    'profile.address.delete': 'حذف',
    'profile.address.default': 'الافتراضي',
    'profile.address.saved': 'عناوين محفوظة',
    'profile.address.confirmDelete': 'إزالة هذا العنوان؟',
    'profile.changePhoto': 'تغيير الصورة',
    'profile.saveChanges': 'حفظ التغييرات',
    'profile.sendResetEmail': 'إرسال بريد إعادة تعيين كلمة المرور',
    'profile.resetEmailSent': 'تم إرسال البريد الإلكتروني! تحقق من صندوق الوارد.',
    'category.camping': 'التخييم والهواء الطلق',
    'category.makeup': 'منتجات المكياج',
    'category.sportswear': 'الملابس الرياضية',
    'category.accessories': 'الإكسسوارات',
    'category.living_room': 'غرفة المعيشة',
    'category.kitchen': 'المطبخ وغرفة الطعام',
    'form.fullname': 'الاسم الكامل',
    'form.email': 'البريد الإلكتروني',
    'form.password': 'كلمة المرور',
    'form.phone': 'رقم الهاتف',
    'coupon.code': 'رمز القسيمة',
    'coupon.apply': 'تطبيق',
    'coupon.invalid': 'قسيمة غير صالحة أو منتهية الصلاحية',
    'coupon.applied': 'تم تطبيق القسيمة',
    'coupon.min_order': 'لم يتم استيفاء الحد الأدنى للطلب',
    'product.buy_now': 'اشتر الآن',
    'product.add_to_cart': 'أضف إلى السلة',
    'global.see_all': 'عرض الكل',
    'global.discover': 'اكتشف',
    'system.order_status.delivered': 'تم التسليم',
    'system.order_status.in_transit': 'في الطريق',
    'system.order_status.preparing': 'قيد التحضير',
    'system.order_status.cancelled': 'ملغي/مسترد',
    'settings.site_name': 'اسم الموقع',
    'settings.maintenance': 'وضع الصيانة',
    'settings.save': 'حفظ الإعدادات',
    'review.approve': 'موافقة',
    'review.reject': 'رفض',
    'return.approve': 'الموافقة على الإرجاع',
    'return.reject': 'رفض الإرجاع',
    'nav.home_page': 'الصفحة الرئيسية',
    'auth.signin': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.signout': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.name': 'الاسم',
    'auth.register': 'تسجيل',
    'auth.signin_with_google': 'الدخول بجوجل',
    'hero.featured_campaign': 'حملة مميزة',
    'nav.departments': 'الأقسام',
    'nav.deliver_to': 'التوصيل إلى',
    'nav.location_select': 'اختر الموقع',
    'nav.location_default': 'إسطنبول، كاديكوي',
    'nav.my_account': 'حسابي',
    'nav.login_or_sign_up': 'تسجيل الدخول أو إنشاء حساب',
    'nav.cart_count': 'السلة',
    'nav.favorite': 'المفضلة',
    'nav.orders_list': 'طلباتي',
    'nav.categories_nav': 'الفئات',
    'nav.hub_active': 'المحور: نشط',
    'nav.market_index': 'مؤشر السوق',
    'nav.tax_id': 'الرقم الضريبي',
    'nav.global_support': 'الدعم العالمي',
    'nav.switch_dark': 'تفعيل الوضع الداكن',
    'nav.switch_light': 'تفعيل الوضع الفاتح',
    'nav.market_dashboard': 'لوحة السوق',
    'nav.my_lists': 'قوائمي',
    'nav.watchlist': 'قائمة المراقبة',
    'nav.saved_items': 'العناصر المحفوظة',
    'nav.wallet': 'المحفظة العالمية',
    'nav.seller_hub': 'مركز البائع',
    'nav.admin_hub': 'مركز الإدارة',
    'nav.logged_in_as': 'مسجل الدخول بـ',
    'nav.login_google': 'تسجيل الدخول بـ Google',
    'nav.logout': 'تسجيل الخروج',
    'nav.mom_day': 'عيد الأم',
    'nav.super_price': 'أسعار خارقة',
    'nav.popular_brands': 'الماركات الشهيرة',
    'hero.subtitle': 'اكتشف المستقبل',
    'hero.desc': 'مجموعة تقنية حرفية منتقاة من مستودعات لندن وإسطنبول، رسوم الجمارك مشمولة.',
    'hero.watch': 'مشاهدة العرض الترويجي',
    'hero.spotlight1.title': 'شحن عالمي',
    'hero.spotlight1.desc': 'سعر ثابت £12.00 إلى مراكز الاتحاد الأوروبي والمملكة المتحدة.',
    'hero.deals_every_day': 'عروض يومية',
    'hero.fearsome_deals': 'صفقات لا تُضاهى',
    'hero.slide1.title': 'التكنولوجيا',
    'hero.slide1.subtitle': 'تخفيضات ضخمة',
    'hero.slide1.desc': 'خصم 20% إضافي على أحدث التقنيات من كبرى الماركات.',
    'hero.slide2.title': 'المنزل والحياة',
    'hero.slide2.subtitle': 'موسم جديد',
    'hero.slide2.desc': 'أسعار رائعة على تصاميم أنيقة وأثاث لتحويل منزلك.',
    'hero.slide3.title': 'الهواء الطلق',
    'hero.slide3.subtitle': 'المغامرة تبدأ',
    'hero.slide3.desc': 'لا تفوّت حملة الربيع على منتجات التخييم والرياضة.',
    'product.origin': 'المنشأ',
    'product.delivery': 'شروط التسليم',
    'product.add_cart': 'أضف إلى السلة',
    'product.description': 'الوصف',
    'product.specifications': 'المواصفات',
    'product.reviews': 'التقييمات',
    'product.recently_viewed': 'المنتجات التي تم عرضها مؤخراً',
    'product.you_might_also_like': 'قد يعجبك أيضاً',
    'product.bought_together': 'يُشترى معاً في الغالب',
    'product.everyone_looking': 'الجميع يتصفح هذا',
    'product.seller_other_products': 'منتجات أخرى من هذا البائع',
    'product.most_compared': 'الأكثر مقارنة',
    'product.questions_answers': 'الأسئلة والأجوبة',
    'product.user_reviews': 'تقييمات المستخدمين',
    'product.verified_purchase': 'شراء موثق',
    'product.useful': 'مفيد',
    'home.for_everyone': 'منتجات للجميع',
    'home.new_arrivals': 'وصل حديثاً',
    'home.popular_products': 'المنتجات الشائعة',
    'home.special_for_you': 'مخصص لك',
    'home.promo_fashion_title': 'عروض الموسم الجديد!',
    'home.promo_sport_title': 'المغامرة في انتظارك!',
    'home.hero_promo_discover': 'اكتشف منتجات الحملة',
    'mega.best_sellers': 'أكثر المبيعات في الموسم',
    'mega.regional_deal': 'عرض إقليمي',
    'mega.check_now': 'تحقق الآن',
    'mega.select_category': 'اختر فئة للاستكشاف',
    'mega.no_subgroups': 'لا توجد مجموعات فرعية في هذه الفئة.',
    'global.show_more': 'عرض المزيد',
    'trust.today_at_door': 'اليوم على بابك',
    'trust.safe_payment': 'دفع آمن',
    'trust.easy_return': 'إرجاع سهل',
    'trust.original': '100% أصلي',
    'trust.today_at_door_desc': 'حتى الساعة 14:00',
    'trust.safe_payment_desc': 'تسوق آمن',
    'trust.easy_return_desc': 'خلال 14 يوماً',
    'trust.original_desc': 'ضمان ميركورا',
    'category.all': 'جميع الفئات',
    'category.electronics': 'الإلكترونيات',
    'category.fashion': 'الأزياء',
    'category.home': 'المنزل والحديقة',
    'category.supermarket': 'سوبرماركت',
    'category.beauty': 'العناية الشخصية',
    'category.baby': 'الأطفال والأم',
    'category.pet': 'متجر الحيوانات',
    'category.pets': 'متجر الحيوانات',
    'category.auto': 'قطع السيارات',
    'category.books': 'الكتب والموسيقى',
    'category.toys': 'الألعاب والهوايات',
    'category.sport': 'الرياضة والهواء الطلق',
    'badge.free_shipping': 'شحن مجاني',
    'badge.tomorrow_at_door': 'غداً على بابك',
    'market.insight': 'رؤى السوق',
    'market.trending': 'طلب مرتفع',
    'market.scarcity': 'تنبيه المخزون',
    'market.opportunity': 'فرصة عالمية',
    'logistics.timeline': 'استراتيجية اللوجستيات',
    'logistics.hub_processing': 'معالجة المركز',
    'logistics.customs_clearance': 'التخليص الجمركي',
    'logistics.last_mile': 'الميل الأخير',
    'flash.deals': 'فرص بلا حدود',
    'flash.view': 'عرض العروض',
    'flash.remaining': 'ينتهي في',
    'admin.promotions': 'المبيعات والعروض',
    'admin.add_to_list': 'إضافة إلى المجموعة',
    'admin.featured': 'المنتجات المميزة',
    'admin.flash_deals': 'فلاش ديلز',
    'admin.low_stock': 'تنبيهات المخزون المنخفض',
    'admin.curate': 'تنظيم الكتالوج',
    'admin.products_tab': 'كتالوج المنتجات',
    'admin.sellers_tab': 'شركاء البائعين',
    'admin.returns_tab': 'المرتجعات',
    'admin.campaigns_tab': 'الحملات',
    'admin.coupons_tab': 'القسائم والخصومات',
    'admin.finance_tab': 'المتابعة المالية',
    'admin.reports_tab': 'تقارير المبيعات',
    'admin.reviews_tab': 'مراجعات المنتجات',
    'admin.support_tab': 'الدعم المباشر',
    'admin.settings_tab': 'إعدادات الموقع',
    'admin.integrations_tab': 'التكاملات',
    'admin.ai_tab': 'تحليل الذكاء الاصطناعي',
    'seller.inventory_mgmt': 'إدارة المخزون',
    'seller.request_feature': 'الترويج للمنتج',
    'seller.dashboard': 'لوحة تحكم البائع',
    'seller.inventory': 'المخزون',
    'seller.orders': 'الطلبات',
    'seller.revenue': 'الإيرادات',
    'seller.products': 'المنتجات',
    'location.select_title': 'اختر موقع التسليم',
    'location.city': 'المدينة',
    'location.district': 'الحي',
    'location.confirm': 'تأكيد الموقع',
    'search.popular': 'عمليات البحث الشائعة',
    'search.products': 'المنتجات المطابقة',
    'search.featured_category': 'الفئة المميزة',
    'footer.corporate': 'الشركة',
    'footer.about': 'من نحن',
    'footer.careers': 'الوظائف',
    'footer.support': 'الدعم',
    'footer.help': 'مركز المساعدة',
    'footer.tagline': 'منظومة التجارة العالمية من الجيل القادم.',
    'footer.commercial_intelligence': 'الذكاء التجاري',
    'footer.tax_avg': 'متوسط الضريبة العالمية',
    'footer.fixed': 'ثابت',
    'footer.artisan_hub': 'مركز الحرفيين',
    'footer.fulfillment': 'التنفيذ بواسطة ميركورا',
    'footer.global_taxes': 'الضرائب العالمية',
    'footer.success_stories': 'قصص النجاح',
    'footer.trust_safety': 'الثقة والأمان',
    'footer.escrow_protection': 'حماية الضمان',
    'footer.privacy_policy': 'سياسة الخصوصية',
    'footer.cookie_policy': 'سياسة ملفات تعريف الارتباط',
    'footer.terms_of_service': 'شروط الخدمة',
    'footer.dispute_resolution': 'تسوية النزاعات',
    'footer.rights_reserved': 'جميع الحقوق محفوظة.',
    'coupon.discount': 'الخصم',
    'return.reason': 'سبب الإرجاع',
    'homepage.sections': 'أقسام الصفحة الرئيسية',
    'homepage.hero_slides': 'لافتات Hero',
    'homepage.flash_deals': 'صفقات فلاش',
    'homepage.featured': 'منتجات مميزة',
    'system.last_week': 'الأسبوع الماضي',
    'system.last_month': 'الشهر الماضي',
    'system.top_selling': 'الأكثر مبيعاً',
    'auth.forgot_password': 'نسيت كلمة المرور',
    'auth.no_account': 'ليس لديك حساب؟ سجّل',
    'auth.have_account': 'لديك حساب؟ سجّل الدخول',
    'auth.continue_with_google': 'المتابعة مع Google',
    'auth.or': 'أو',
    'auth.confirm_password': 'تأكيد كلمة المرور',
    'cart.empty': 'سلة التسوق فارغة',
    'cart.total': 'المجموع',
    'cart.checkout': 'إتمام الشراء',
    'cart.remove': 'إزالة',
    'checkout.shipping': 'الشحن',
    'checkout.payment': 'الدفع',
    'checkout.order_summary': 'ملخص الطلب',
    'checkout.place_order': 'تأكيد الطلب',
    'wishlist.title': 'قائمة أمنياتي',
    'wishlist.empty': 'لا توجد منتجات في القائمة',
    'wishlist.add': 'أضف إلى القائمة',
    'wishlist.remove': 'إزالة من القائمة',
    'order.tracking': 'تتبع الطلب',
    'order.placed': 'تم الطلب',
    'order.confirmed': 'تم التأكيد',
    'order.preparing': 'جاري التحضير',
    'order.shipped': 'تم الشحن',
    'order.delivered': 'تم التسليم',
    'order.cancelled': 'ملغي',
    'filter.quickFilters': 'فلاتر سريعة',
    'filter.advantageous': 'منتجات مميزة',
    'filter.freeShipping': 'شحن مجاني',
    'filter.categories': 'الفئات',
    'filter.priceRange': 'نطاق السعر',
    'filter.minRating': 'أدنى تقييم',
    'filter.clearAll': 'مسح الكل',
    'filter.andAbove': 'وأعلى',
    'filter.showMore': 'عرض المزيد',
    'filter.showLess': 'عرض أقل',
    'filter.search': 'بحث',
    'product.inStock': 'متوفر',
    'product.outOfStock': 'نفدت الكمية',
    'product.addToCart': 'أضف للسلة',
    'product.added': 'تمت الإضافة!',
    'product.quickView': 'عرض سريع',
    'product.freeShipping': 'شحن مجاني',
    'profile.overview': 'نظرة عامة',
    'profile.orders': 'طلباتي',
    'profile.favorites': 'المفضلة',
    'profile.noOrders': 'لا توجد طلبات بعد',
    'profile.startShopping': 'ابدأ التسوق',
    'profile.totalSpent': 'إجمالي الإنفاق',
    'profile.activeOrders': 'الطلبات النشطة',
    'profile.savedItems': 'المحفوظات',
    'profile.rewardPoints': 'النقاط',
    'profile.priceAlerts': 'تنبيهات الأسعار',
    'profile.noPriceAlerts': 'لا توجد تنبيهات أسعار محددة.',
    'profile.originalPrice': 'السعر الأصلي',
    'profile.currentPrice': 'السعر الحالي',
    'profile.removeTrack': 'إلغاء التتبع',
    'profile.priceDropped': 'انخفض السعر!',
    'product.rec.interest.title': 'قد يعجبك أيضاً',
    'product.rec.interest.sub': 'منتجات أخرى شاهدها زوار هذه السلعة',
    'product.rec.bakanAldi.title': 'اشتراها أيضاً من شاهدوها',
    'product.rec.bakanAldi.sub': 'منتجات أخرى اشتراها زوار هذه السلعة',
    'product.rec.birlikte.title': 'يُشترى معاً في الغالب',
    'product.rec.birlikte.sub': 'منتجات تُشترى معاً مع هذه السلعة',
    'product.rec.populer.title': 'الجميع يتصفح هذا',
    'product.rec.populer.sub': 'المنتجات الأكثر شعبية في هذه الفئة',
    'product.rec.secilmis.title': 'منتجات شائعة مختارة لك',
    'product.rec.secilmis.sub': 'منتجات شائعة مختارة لك',
    'product.rec.searches.title': 'عمليات البحث الشائعة',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('tr');
  const [availableLanguages, setAvailableLanguages] = useState<LanguagePack[]>(initialAvailableLanguages);
  const [translations, setTranslations] = useState<Record<string, Record<string, string>>>(initialTranslations);

  const t = (key: string, fallback?: string) => {
    return translations[lang]?.[key] || initialTranslations['en']?.[key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, availableLanguages, setAvailableLanguages, translations, setTranslations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
