import React, { createContext, useContext, useState, ReactNode } from 'react';

export interface LanguagePack {
  code: string;
  name: string;
  flag: string;
}

export const initialAvailableLanguages: LanguagePack[] = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
];

export type Language = string;

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  availableLanguages: LanguagePack[];
  setAvailableLanguages: (packs: LanguagePack[]) => void;
  translations: Record<string, Record<string, string>>;
  setTranslations: (trans: Record<string, Record<string, string>>) => void;
}

const initialTranslations: Record<string, Record<string, string>> = {
  en: {
    'nav.deals': "Today's Deals",
    'nav.customerservice': 'Customer Service',
    'nav.registry': 'Registry',
    'nav.giftcards': 'Gift Cards',
    'nav.sell': 'Sell on Mercora',
    'nav.hello': 'Hello, Sign in',
    'nav.account': 'Account & Lists',
    'nav.orders': 'Returns & Orders',
    'nav.cart': 'Cart',
    'nav.search_placeholder': "Search products globally: 'Handmade WATCH'...",
    'nav.all_categories': 'All Categories',
    'nav.departments': 'Departments',
    'nav.deliver_to': 'Deliver to',
    'hero.badge': '2026 Season Deals',
    'hero.title': 'Electronic Artifacts',
    'hero.subtitle': 'Discover the Future',
    'hero.desc': 'Handpicked artisan technology collection from London and Istanbul warehouses, all customs duties included.',
    'hero.cta': 'Browse Collection',
    'hero.watch': 'Watch Promo',
    'hero.spotlight1.title': 'Global Fulfillment',
    'hero.spotlight1.desc': 'Flat £12.00 flat rate shipping to EU and UK Hubs.',
    'product.origin': 'Origin',
    'product.delivery': 'Delivery Terms',
    'product.buy_now': 'Buy Now',
    'product.add_cart': 'Add to Cart',
    'home.best_sellers': 'Best Sellers',
    'home.for_everyone': 'Products for Everyone',
    'home.new_arrivals': 'New Arrivals',
    'global.discover': 'Discover the World Market',
    'global.see_all': 'See All',
    'market.insight': 'Market Insights',
    'market.trending': 'Bullish Demand',
    'market.scarcity': 'Scarcity Alert',
    'market.opportunity': 'Global Opportunity',
    'logistics.timeline': 'Fulfillment Strategy',
    'logistics.hub_processing': 'Hub Processing',
    'logistics.customs_clearance': 'Customs Authorization',
    'logistics.last_mile': 'Last Mile Delivery',
    'nav.location_select': 'Select Location',
    'nav.location_default': 'Istanbul, Kadikoy',
    'nav.my_account': 'My Account',
    'nav.login_or_sign_up': 'Login or Sign Up',
    'nav.cart_count': 'Cart',
    'nav.favorite': 'My Favorites',
    'nav.orders_list': 'My Orders',
    'nav.home_page': 'Home',
    'nav.categories_nav': 'Categories',
    'badge.free_shipping': 'Free Shipping',
    'badge.tomorrow_at_door': 'Tomorrow At Door',
    'home.popular_products': 'Popular Products',
    'home.special_for_you': 'Special For You',
    'category.all': 'All Categories',
    'hero.deals_every_day': 'Deals Every Day',
    'hero.fearsome_deals': 'Fearsome Deals',
    'hero.featured_campaign': 'FEATURED CAMPAIGN',
    'hero.slide1.title': 'TECHNOLOGY',
    'hero.slide1.subtitle': 'GIANT DEALS',
    'hero.slide1.desc': 'Extra 20% off on latest technology from leading brands.',
    'hero.slide2.title': 'HOME & LIFE',
    'hero.slide2.subtitle': 'NEW SEASON',
    'hero.slide2.desc': 'Super prices on elegant designs and furniture to transform your home.',
    'hero.slide3.title': 'OUTDOOR',
    'hero.slide3.subtitle': 'ADVENTURE BEGINS',
    'hero.slide3.desc': 'Don\'t miss the spring campaign on camping and nature sports products.',
    'mega.best_sellers': 'Best Sellers of the Season',
    'mega.regional_deal': 'Regional Deal',
    'mega.check_now': 'Check Now',
    'mega.select_category': 'Select a category to explore',
    'mega.no_subgroups': 'No subgroups defined in this category.',
    'home.promo_fashion_title': 'NEW SEASON OPPORTUNITIES!',
    'home.promo_sport_title': 'ADVENTURE AWAITS YOU!',
    'home.hero_promo_discover': 'Discover Campaign Products',
    'global.show_more': 'Show More',
    'trust.today_at_door': 'Today at Your Door',
    'trust.safe_payment': 'Secure Payment',
    'trust.easy_return': 'Easy Returns',
    'trust.original': '100% Original',
    'trust.today_at_door_desc': 'Until 14:00',
    'trust.safe_payment_desc': 'Secure Shopping',
    'trust.easy_return_desc': 'Within 14 days',
    'trust.original_desc': 'Mercora Assurance',
    'category.camping': 'Camping & Outdoor',
    'category.makeup': 'Makeup Products',
    'category.sportswear': 'Sportswear',
    'category.accessories': 'Accessories',
    'category.living_room': 'Living Room',
    'category.kitchen': 'Kitchen & Dining',
    'footer.corporate': 'Corporate',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.support': 'Support',
    'footer.help': 'Help Center',
    'category.electronics': 'Electronics',
    'category.fashion': 'Fashion',
    'category.home': 'Home & Living',
    'category.supermarket': 'Supermarket',
    'category.beauty': 'Personal Care',
    'category.baby': 'Baby & Mother',
    'category.pet': 'Pet Shop',
    'category.pets': 'Pet Shop',
    'category.auto': 'Auto Parts',
    'category.books': 'Books & Music',
    'category.toys': 'Toys & Hobbies',
    'category.sport': 'Sports & Outdoor',
    'flash.deals': 'Limitless Opportunities',
    'flash.view': 'View Deals',
    'flash.remaining': 'Ends in',
    'nav.hub_active': 'Hub: Active',
    'nav.market_index': 'Market Index',
    'nav.tax_id': 'Tax ID',
    'nav.global_support': 'Global Support',
    'nav.switch_dark': 'Switch to Dark Mode',
    'nav.switch_light': 'Switch to Light Mode',
    'nav.market_dashboard': 'Market Dashboard',
    'nav.my_lists': 'My Lists',
    'nav.watchlist': 'Watchlist',
    'nav.saved_items': 'Saved Items',
    'nav.wallet': 'Global Wallet',
    'nav.seller_hub': 'Seller Hub',
    'nav.admin_hub': 'Admin Hub',
    'nav.logged_in_as': 'Signed in as',
    'nav.login_google': 'Sign In with Google',
    'nav.logout': 'Sign Out',
    'nav.mom_day': 'Mother\'s Day',
    'nav.super_price': 'Super Prices',
    'admin.promotions': 'Sales & Promotions',
    'admin.add_to_list': 'Add to Collection',
    'admin.featured': 'Featured Products',
    'admin.flash_deals': 'Flash Deals',
    'admin.low_stock': 'Low Stock Alerts',
    'admin.curate': 'Curate Catalog',
    'seller.inventory_mgmt': 'Inventory Control',
    'seller.request_feature': 'Promote Product',
    'location.select_title': 'Select Delivery Location',
    'location.city': 'City',
    'location.district': 'District',
    'location.confirm': 'Confirm Location',
    'search.popular': 'Popular Searches',
    'search.products': 'Matching Products',
    'search.featured_category': 'Featured Category',
    'nav.popular_brands': 'Popular Brands',
    'footer.tagline': 'The next-generation global commerce ecosystem connecting artisans to the world via AI-driven compliance and logistics.',
    'footer.commercial_intelligence': 'Commercial Intelligence',
    'footer.tax_avg': 'Global Tax Avg',
    'footer.fixed': 'Fixed',
    'footer.artisan_hub': 'Artisan Hub',
    'footer.fulfillment': 'Fulfillment by Mercora',
    'footer.global_taxes': 'Global Taxes',
    'footer.success_stories': 'Success Stories',
    'footer.trust_safety': 'Trust & Safety',
    'footer.escrow_protection': 'Escrow Protection',
    'footer.privacy_policy': 'Privacy Policy',
    'footer.cookie_policy': 'Cookie Policy',
    'footer.terms_of_service': 'Terms of Service',
    'footer.dispute_resolution': 'Dispute Resolution',
    'footer.rights_reserved': 'All rights reserved.',
    'product.description': 'Description',
    'product.specifications': 'Specifications',
    'product.reviews': 'Reviews',
    'product.you_might_also_like': 'You might also like',
    'product.bought_together': 'Frequently bought together',
    'product.everyone_looking': 'Everyone is looking at these',
    'product.seller_other_products': 'Other products from this seller',
    'product.most_compared': 'Most compared with this product',
    'product.questions_answers': 'Questions & Answers',
    'product.user_reviews': 'User Reviews',
    'product.verified_purchase': 'Verified Purchase',
    'product.useful': 'Useful',
    'cart.title': 'Shopping Global Artifacts',
    'cart.items_in_bay': 'Items in Bay',
    'cart.empty': 'Your bay is empty.',
    'cart.start_archiving': 'Start Archiving',
    'cart.global_fulfillment': 'Global Fulfillment',
    'cart.origin': 'Origin',
    'cart.unit_price': 'Unit Price',
    'cart.subtotal': 'Subtotal',
    'cart.global_tax': 'Global Tax (VAT)',
    'cart.customs_duties': 'Customs & Duties',
    'cart.shipping_factor': 'Shipping Factor',
    'cart.final_investment': 'Final Investment',
    'cart.free_returns': 'Free Returns',
    'cart.authorize_payment': 'Authorize Payment',
    'cart.authorizing': 'Authorizing...',
    'cart.secured_bay': 'Secured Bay',
    'cart.cert_export': 'Cert. Export',
    'cart.priority_support': 'Merchant Priority Support',
    'cart.support_desc': 'Chat with a Global logistics specialist.',
    'cart.included': 'Included',
    'cart.artifact_summary': 'Artifact Summary',
    'checkout.title': 'Secure Checkout',
    'checkout.delivery': 'Delivery',
    'checkout.payment': 'Payment',
    'checkout.confirmation': 'Confirmation',
    'checkout.shipping_address': 'Shipping Address',
    'checkout.first_name': 'First Name',
    'checkout.last_name': 'Last Name',
    'checkout.street_address': 'Street Address',
    'checkout.city': 'City',
    'checkout.zip_code': 'Zip Code',
    'checkout.continue_payment': 'Continue to Payment',
    'checkout.secure_payment': 'Secure Payment',
    'checkout.escrow_protection': 'Escrow Protection',
    'checkout.escrow_desc': 'Your funds are held securely until the artifact is delivered and verified by you.',
    'checkout.cardholder_name': 'Cardholder Name',
    'checkout.card_number': 'Card Number',
    'checkout.expiry_date': 'Expiry Date',
    'checkout.cvc': 'CVC',
    'checkout.back': 'Back',
    'checkout.pay_securely': 'Pay {total} Securely',
    'checkout.verifying': 'Verifying Neural Escrow...',
    'checkout.success_title': 'Payment Successful',
    'checkout.success_desc': 'Your order is confirmed and secured by our escrow network. The seller has been notified to construct the parcel.',
    'checkout.view_orders': 'View in My Orders',
    'checkout.order_summary': 'Order Summary',
    'checkout.logistics': 'Logistics',
    'checkout.taxes': 'Taxes',
    'checkout.total': 'Total',
    'checkout.encryption_notice': '256-bit Node Encryption active. Multi-sig escrow holding.',
  },
  tr: {
    'nav.deals': "Günün Fırsatları",
    'nav.customerservice': 'Müşteri Hizmetleri',
    'nav.registry': 'Liste',
    'nav.giftcards': 'Hediye Kartları',
    'nav.sell': 'Mercora\'da Sat',
    'nav.hello': 'Merhaba, Giriş yap',
    'nav.account': 'Hesap ve Listeler',
    'nav.orders': 'İadeler ve Siparişler',
    'nav.cart': 'Sepet',
    'nav.search_placeholder': "Küresel ürün ara: 'El yapımı SAAT'...",
    'nav.all_categories': 'Tüm Kategoriler',
    'nav.departments': 'Bölümler',
    'nav.deliver_to': 'Gönderim',
    'hero.badge': '2026 Sezon Fırsatları',
    'hero.title': 'Elektronik Artifacts',
    'hero.subtitle': 'Geleceği Keşfet',
    'hero.desc': 'Londra ve İstanbul depo çıkışlı, gümrük masrafları dahil artisan teknoloji koleksiyonu Mercora\'da.',
    'hero.cta': 'Hemen İncele',
    'hero.watch': 'Tanıtım İzle',
    'hero.spotlight1.title': 'Küresel Gönderim',
    'hero.spotlight1.desc': 'AB ve BK merkezlerine sabit £12.00 kargo ücreti.',
    'hero.spotlight2.title': 'Artisan Doğrulamalı',
    'hero.spotlight2.desc': 'Her eser küratörlerimiz tarafından denetlenir.',
    'product.origin': 'Menşei',
    'product.delivery': 'Teslimat Şartları',
    'product.buy_now': 'Hemen Al',
    'product.add_cart': 'Sepete Ekle',
    'home.best_sellers': 'En Çok Satanlar',
    'home.for_everyone': 'Bu Ürünler Herkese Göre',
    'home.new_arrivals': 'Yeni Gelenler',
    'global.discover': 'Dünya Pazarını Keşfet',
    'global.see_all': 'Tümünü Gör',
    'market.insight': 'Pazar Analizi',
    'market.trending': 'Yüksek Talep',
    'market.scarcity': 'Stok Alarmı',
    'market.opportunity': 'Küresel Fırsat',
    'logistics.timeline': 'Lojistik Stratejisi',
    'logistics.hub_processing': 'Merkez İşleme',
    'logistics.customs_clearance': 'Gümrük Onayı',
    'logistics.last_mile': 'Son Teslimat',
    'nav.location_select': 'Konum Seç',
    'nav.location_default': 'İstanbul, Kadıköy',
    'nav.my_account': 'Hesabım',
    'nav.login_or_sign_up': 'Giriş yap veya üye ol',
    'nav.cart_count': 'Sepetim',
    'nav.favorite': 'Favorilerim',
    'nav.orders_list': 'Siparişlerim',
    'nav.home_page': 'Ana Sayfa',
    'nav.categories_nav': 'Kategoriler',
    'badge.free_shipping': 'Kargo Bedava',
    'badge.tomorrow_at_door': 'Yarın Kapında',
    'home.popular_products': 'Popüler Ürünler',
    'home.special_for_you': 'Size Özel Seçtiklerimiz',
    'category.all': 'Tüm Kategoriler',
    'hero.deals_every_day': 'Her Gün Yenilenen',
    'hero.fearsome_deals': 'Fırsatlar',
    'hero.featured_campaign': 'ÖNE ÇIKAN KAMPANYA',
    'hero.slide1.title': 'TEKNOLOJİ',
    'hero.slide1.subtitle': 'DEV FIRSATLAR',
    'hero.slide1.desc': 'Lider markaların en yeni teknoloji ürünlerinde sepette ek %20 indirim.',
    'hero.slide2.title': 'EV & YAŞAM',
    'hero.slide2.subtitle': 'YENİ SEZON',
    'hero.slide2.desc': 'Evinizin havasını değiştirecek şık tasarımlar ve mobilyalarda süper fiyatlar.',
    'hero.slide3.title': 'OUTDOOR',
    'hero.slide3.subtitle': 'MACERA BAŞLIYOR',
    'hero.slide3.desc': 'Kamp ve doğa sporları ürünlerinde bahar kampanyasını kaçırma.',
    'mega.best_sellers': 'Sezonun En Çok Satanları',
    'mega.regional_deal': 'Bölgesel Fırsat',
    'mega.check_now': 'Şimdi İncele',
    'mega.select_category': 'Keşfetmek için bir kategori seçin',
    'mega.no_subgroups': 'Bu kategoride henüz alt grup tanımlanmadı.',
    'home.promo_fashion_title': 'YENİ SEZON FIRSATLARI!',
    'home.promo_sport_title': 'MACERA SENİ BEKLİYOR!',
    'home.hero_promo_discover': 'Kampanyalı Ürünleri Keşfet',
    'global.show_more': 'Daha Fazla Gör',
    'trust.today_at_door': 'Bugün Kapında',
    'trust.safe_payment': 'Güvenli Ödeme',
    'trust.easy_return': 'Kolay İade',
    'trust.original': '%100 Orijinal',
    'trust.today_at_door_desc': 'Saat 14:00\'e kadar',
    'trust.safe_payment_desc': 'Güvenli Alışveriş',
    'trust.easy_return_desc': '14 gün içinde',
    'trust.original_desc': 'Mercora Güvencesi',
    'category.electronics': 'Elektronik',
    'category.fashion': 'Moda Dünyası',
    'category.home': 'Ev & Yaşam',
    'category.supermarket': 'Süpermarket',
    'category.beauty': 'Kişisel Bakım',
    'category.baby': 'Anne & Bebek',
    'category.pet': 'Pet Shop',
    'category.pets': 'Pet Shop',
    'category.sport': 'Spor & Outdoor',
    'footer.corporate': 'Kurumsal',
    'footer.about': 'Hakkımızda',
    'footer.careers': 'Kariyer',
    'footer.support': 'Destek',
    'footer.help': 'Yardım Merkezi',
    'flash.deals': 'Limitli Süre',
    'flash.view': 'Fırsatları Gör',
    'flash.remaining': 'Sona Ermesine',
    'nav.hub_active': 'Merkezi: Aktif',
    'nav.market_index': 'Pazar Endeksi',
    'nav.tax_id': 'Vergi Kimlik No',
    'nav.global_support': 'Global Destek',
    'nav.switch_dark': 'Karanlık Moda Geç',
    'nav.switch_light': 'Aydınlık Moda Geç',
    'nav.market_dashboard': 'Pazar Paneli',
    'nav.my_lists': 'Listelerim',
    'nav.watchlist': 'Takip Listesi',
    'nav.saved_items': 'Kaydedilenler',
    'nav.wallet': 'Cüzdanım',
    'nav.seller_hub': 'Satıcı Paneli',
    'nav.admin_hub': 'Yönetici Paneli',
    'nav.logged_in_as': 'Olarak giriş yapıldı',
    'nav.login_google': 'Google ile Giriş Yap',
    'nav.logout': 'Çıkış Yap',
    'nav.mom_day': 'Anneler Günü',
    'nav.super_price': 'Süper Fiyatlar',
    'category.auto': 'Oto Aksesuar',
    'category.books': 'Kitap & Müzik',
    'category.toys': 'Oyuncak & Hobi',
    'admin.promotions': 'Satış ve Kampanyalar',
    'admin.add_to_list': 'Listeye Ekle',
    'admin.featured': 'Öne Çıkan Ürünler',
    'admin.flash_deals': 'Flaş Fırsatlar',
    'admin.low_stock': 'Düşük Stok Uyarıları',
    'admin.curate': 'Kataloğu Yönet',
    'seller.inventory_mgmt': 'Envanter Kontrolü',
    'seller.request_feature': 'Ürünü Öne Çıkar',
    'location.select_title': 'Teslimat Konumu Seçin',
    'location.city': 'Şehir',
    'location.district': 'İlçe',
    'location.confirm': 'Konumu Onayla',
    'search.popular': 'Popüler Aramalar',
    'search.products': 'Eşleşen Ürünler',
    'search.featured_category': 'Öne Çıkan Kategori',
    'nav.popular_brands': 'Popüler Markalar',
    'footer.tagline': 'Zanaatkarları yapay zeka destekli uyumluluk ve lojistik yoluyla dünyaya bağlayan yeni nesil küresel ticaret ekosistemi.',
    'footer.commercial_intelligence': 'Ticari Zeka',
    'footer.tax_avg': 'Küresel Vergi Ort.',
    'footer.fixed': 'Sabit',
    'footer.artisan_hub': 'Zanaatkar Merkezi',
    'footer.fulfillment': 'Mercora Lojistik',
    'footer.global_taxes': 'Küresel Vergiler',
    'footer.success_stories': 'Başarı Hikayeleri',
    'footer.trust_safety': 'Güven ve Güvenlik',
    'footer.escrow_protection': 'Emanet Koruması',
    'footer.privacy_policy': 'Gizlilik Politikası',
    'footer.cookie_policy': 'Çerez Politikası',
    'footer.terms_of_service': 'Kullanım Koşulları',
    'footer.dispute_resolution': 'Uyuşmazlık Çözümü',
    'footer.rights_reserved': 'Tüm hakları saklıdır.',
    'product.description': 'Ürün Açıklaması',
    'product.specifications': 'Ürün Özellikleri',
    'product.reviews': 'Değerlendirmeler',
    'product.you_might_also_like': 'Bunlar da ilginizi çekebilir',
    'product.bought_together': 'Birlikte alınan ürünler',
    'product.everyone_looking': 'Herkes bunlara bakıyor',
    'product.seller_other_products': 'Bu satıcının diğer ürünleri',
    'product.most_compared': 'En çok karşılaştırılanlar',
    'product.questions_answers': 'Soru & Cevap',
    'product.user_reviews': 'Kullanıcı Yorumları',
    'product.verified_purchase': 'Onaylanmış Alışveriş',
    'product.useful': 'Faydalı',
    'cart.title': 'Küresel Alışveriş',
    'cart.items_in_bay': 'Sepetteki Ürünler',
    'cart.empty': 'Sepetiniz boş.',
    'cart.start_archiving': 'Alışverişe Başla',
    'cart.global_fulfillment': 'Küresel Gönderim',
    'cart.origin': 'Menşei',
    'cart.unit_price': 'Birim Fiyat',
    'cart.subtotal': 'Ara Toplam',
    'cart.global_tax': 'Küresel Vergi (KDV)',
    'cart.customs_duties': 'Gümrük ve Vergiler',
    'cart.shipping_factor': 'Kargo Bedeli',
    'cart.final_investment': 'Genel Toplam',
    'cart.free_returns': 'Ücretsiz İade',
    'cart.authorize_payment': 'Ödemeyi Onayla',
    'cart.authorizing': 'Onaylanıyor...',
    'cart.secured_bay': 'Güvenli Sepet',
    'cart.cert_export': 'Sertifikalı İhracat',
    'cart.priority_support': 'Öncelikli Satıcı Desteği',
    'cart.support_desc': 'Küresel lojistik uzmanıyla görüşün.',
    'cart.included': 'Dahil',
    'cart.artifact_summary': 'Sipariş Özeti',
    'checkout.title': 'Güvenli Ödeme',
    'checkout.delivery': 'Teslimat',
    'checkout.payment': 'Ödeme',
    'checkout.confirmation': 'Onay',
    'checkout.shipping_address': 'Teslimat Adresi',
    'checkout.first_name': 'Ad',
    'checkout.last_name': 'Soyad',
    'checkout.street_address': 'Adres',
    'checkout.city': 'Şehir',
    'checkout.zip_code': 'Posta Kodu',
    'checkout.continue_payment': 'Ödemeye Geç',
    'checkout.secure_payment': 'Güvenli Ödeme',
    'checkout.escrow_protection': 'Emanet Koruması',
    'checkout.escrow_desc': 'Ürün teslim edilip tarafınızdan onaylanana kadar fonlarınız güvenle tutulur.',
    'checkout.cardholder_name': 'Kart Üzerindeki İsim',
    'checkout.card_number': 'Kart Numarası',
    'checkout.expiry_date': 'Son Kullanma Tarihi',
    'checkout.cvc': 'CVC',
    'checkout.back': 'Geri',
    'checkout.pay_securely': '{total} Güvenle Öde',
    'checkout.verifying': 'Güvenli Emanet Doğrulanıyor...',
    'checkout.success_title': 'Ödeme Başarılı',
    'checkout.success_desc': 'Siparişiniz onaylandı ve emanet ağımız tarafından güvence altına alındı. Satıcıya siparişin hazırlanması bildirildi.',
    'checkout.view_orders': 'Siparişlerim\'de Görüntüle',
    'checkout.order_summary': 'Sipariş Özeti',
    'checkout.logistics': 'Lojistik',
    'checkout.taxes': 'Vergiler',
    'checkout.total': 'Toplam',
    'checkout.encryption_notice': '256-bit Node Şifreleme aktif. Çoklu-imzalı emanet koruması.',
  },
  de: {
    'nav.deals': "Tagesangebote",
    'nav.customerservice': 'Kundenservice',
    'nav.registry': 'Liste',
    'nav.giftcards': 'Geschenkkarten',
    'nav.sell': 'Auf Mercora verkaufen',
    'nav.hello': 'Hallo, Anmelden',
    'nav.account': 'Konto & Listen',
    'nav.orders': 'Retouren & Bestellungen',
    'nav.cart': 'Einkaufswagen',
    'nav.search_placeholder': "Produkte weltweit suchen...",
    'nav.all_categories': 'Alle Kategorien',
    'hero.badge': '2026 Saisonangebote',
    'hero.title': 'Elektronische Artefakte',
    'hero.cta': 'Entdecken',
    'home.best_sellers': 'Bestseller',
    // We'll fallback to english/key for missing ones
  },
  ar: {
    'nav.deals': "عروض اليوم",
    'nav.customerservice': 'خدمة العملاء',
    'nav.registry': 'قائمة السجل',
    'nav.giftcards': 'بطاقات هدايا',
    'nav.sell': 'البيع على ميركورا',
    'nav.hello': 'مرحباً، تسجيل الدخول',
    'nav.account': 'الحساب والقوائم',
    'nav.orders': 'المرتجعات والطلبات',
    'nav.cart': 'عربة التسوق',
    'nav.search_placeholder': "ابحث عن المنتجات عالمياً...",
    'nav.all_categories': 'كل الفئات',
    'hero.badge': 'عروض موسم 2026',
    'hero.title': 'تحف إلكترونية',
    'hero.cta': 'اكتشف',
    'home.best_sellers': 'الأكثر مبيعاً',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('en');
  const [availableLanguages, setAvailableLanguages] = useState<LanguagePack[]>(initialAvailableLanguages);
  const [translations, setTranslations] = useState<Record<string, Record<string, string>>>(initialTranslations);

  const t = (key: string) => {
    return translations[lang]?.[key] || initialTranslations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, availableLanguages, setAvailableLanguages, translations, setTranslations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
