import { Product, Category, UserProfile, Seller, Review } from './types';

export const MOCK_SELLERS: Seller[] = [
  {
    id: 's1',
    userId: 'u2',
    storeName: "AuraAudio Engineering",
    slug: "aura-audio",
    rating: 4.9,
    reviewsCount: 1250,
    followersCount: 8400,
    origin: "Berlin, Germany",
    joinedDate: "Mar 2022",
    isVerified: true,
    kycStatus: 'verified',
    commissionRate: 0.10,
    bannerUrl: "https://picsum.photos/seed/audio-banner/1920/1080?blur=4",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=AA",
    description: "Pioneering the future of artisan audio. Every piece is hand-calibrated in our Berlin workshop using sustainable materials and revolutionary driver technology.",
    fulfillmentHealth: {
      shipSpeed: "98% Within 24hr",
      compliance: "Level 4 Escrow"
    }
  },
  {
    id: 's2',
    userId: 'u3',
    storeName: "Clay & Co. Portugese Ceramics",
    slug: "clay-co-ceramics",
    rating: 5.0,
    reviewsCount: 450,
    followersCount: 2100,
    origin: "Porto, Portugal",
    joinedDate: "May 2023",
    isVerified: true,
    kycStatus: 'verified',
    commissionRate: 0.10,
    bannerUrl: "https://picsum.photos/seed/clay-banner/1920/1080?blur=4",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=CC",
    description: "Hand-thrown ceramics that capture the mist of the Atlantic. We specialize in traditional glazing techniques with a modern minimalist aesthetic.",
    fulfillmentHealth: {
      shipSpeed: "95% Within 48hr",
      compliance: "Artisan Certified"
    }
  },
  {
    id: 's3',
    userId: 'u4',
    storeName: "Nexus Home Systems",
    slug: "nexus-home",
    rating: 4.7,
    reviewsCount: 890,
    followersCount: 5600,
    origin: "Seattle, USA",
    joinedDate: "Jan 2024",
    isVerified: true,
    kycStatus: 'verified',
    commissionRate: 0.12,
    bannerUrl: "https://picsum.photos/seed/nexus-banner/1920/1080?blur=4",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=NS",
    description: "Next-gen computing and smart home systems for the omni-channel professional.",
    fulfillmentHealth: {
      shipSpeed: "99% Within 24hr",
      compliance: "Enterprise Ready"
    }
  },
  {
    id: 's4',
    userId: 'u5',
    storeName: "Zenith Home Decor",
    slug: "zenith-decor",
    rating: 4.8,
    reviewsCount: 320,
    followersCount: 1500,
    origin: "Kyoto, Japan",
    joinedDate: "Feb 2024",
    isVerified: true,
    kycStatus: 'verified',
    commissionRate: 0.10,
    bannerUrl: "https://picsum.photos/seed/zenith-banner/1920/1080?blur=4",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=ZD",
    description: "Minimalist home essentials inspired by Japanese craftsmanship.",
    fulfillmentHealth: {
      shipSpeed: "97% Within 24hr",
      compliance: "Artisan Standard"
    }
  },
  {
    id: 'bot_1',
    userId: 'u_bot_1',
    storeName: "MCR-GlobalBot [Auto]",
    slug: "global-bot-store",
    rating: 4.9,
    reviewsCount: 15400,
    followersCount: 89000,
    origin: "Data Center Alpha",
    joinedDate: "Jan 2026",
    isVerified: true,
    kycStatus: 'verified',
    commissionRate: 0.15,
    bannerUrl: "https://picsum.photos/seed/bot/1920/1080?blur=10",
    logoUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=MCR1",
    description: "I am a Mercora Automated Selling Agent. I process global shipments 24/7 with zero latency.",
    fulfillmentHealth: {
      shipSpeed: "INSTANT",
      compliance: "Fully Automated"
    }
  }
];

export const CATEGORIES: Category[] = [
  {
    id: 'electronics',
    name: 'Elektronik',
    slug: 'elektronik',
    icon: 'Smartphone',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&q=80&w=800',
    subGroups: [
      { 
        name: 'Telefon', 
        items: [
          {name: 'Akıllı Telefon', query: 'smartphone'}, 
          {name: 'iPhone', query: 'iphone'}, 
          {name: 'Android', query: 'android'},
          {name: 'Yenilenmiş', query: 'refurbished'},
          {name: 'Aksesuar', query: 'phone-acc'}
        ] 
      },
      { 
        name: 'Bilgisayar', 
        items: [
          {name: 'Laptop/Gaming', query: 'laptop'}, 
          {name: 'Masaüstü PC', query: 'desktop'}, 
          {name: 'PC Bileşenleri', query: 'components'},
          {name: 'Monitor/Ekran', query: 'monitor'}
        ] 
      }
    ],
    brands: [{ name: 'Samsung', logo: 'S' }, { name: 'Apple', logo: 'A' }]
  },
  {
    id: 'moda',
    name: 'Moda',
    slug: 'moda',
    icon: 'Shirt',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83e26371?auto=format&fit=crop&q=80&w=800',
    subGroups: [
      { name: 'Kadın', items: [{name: 'Elbise', query: 'dress'}, {name: 'Tişört', query: 'w-tshirt'}] },
      { name: 'Erkek', items: [{name: 'Gömlek', query: 'm-shirt'}, {name: 'Pantolon', query: 'm-pants'}] },
      { name: 'Ayakkabı', items: [{name: 'Sneaker', query: 'sneaker'}, {name: 'Bot', query: 'boots'}] }
    ]
  },
  {
    id: 'home',
    name: 'Ev & Yaşam',
    slug: 'ev-yasam',
    icon: 'Home',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800',
    subGroups: [
      { name: 'Mobilya', items: [{name: 'Koltuk', query: 'sofa'}, {name: 'Yatak', query: 'bed'}] },
      { name: 'Mutfak', items: [{name: 'Kahve Makinesi', query: 'coffee'}, {name: 'Air Fryer', query: 'airfryer'}] }
    ]
  },
  {
    id: 'supermarket',
    name: 'Süpermarket',
    slug: 'supermarket',
    icon: 'ShoppingBasket',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=800',
    subGroups: [
      { name: 'Gıda', items: [{name: 'Atıştırmalık', query: 'snacks'}, {name: 'İçecek', query: 'drinks'}] },
      { name: 'Bebek', items: [{name: 'Bebek Bezi', query: 'diapers'}] }
    ]
  },
  {
    id: 'beauty',
    name: 'Kozmetik',
    slug: 'kozmetik',
    icon: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=800',
    subGroups: [
      { name: 'Bakım', items: [{name: 'Cilt Bakımı', query: 'skincare'}, {name: 'Parfüm', query: 'perfume'}] }
    ]
  },
  {
    id: 'baby',
    name: 'Anne Bebek',
    slug: 'anne-bebek',
    icon: 'Baby',
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800',
    subGroups: [
      { name: 'Bebek', items: [{name: 'Bebek Arabası', query: 'stroller'}, {name: 'Oto Koltuğu', query: 'car-seat'}] }
    ]
  },
  {
    id: 'pet',
    name: 'Pet Shop',
    slug: 'pet-shop',
    icon: 'Dog',
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&q=80&w=800',
    subGroups: [
      { name: 'Evcil Hayvan', items: [{name: 'Kedi Maması', query: 'cat-food'}, {name: 'Köpek Maması', query: 'dog-food'}] }
    ]
  },
  {
    id: 'sport',
    name: 'Spor & Outdoor',
    slug: 'spor-outdoor',
    icon: 'Mountain',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&q=80&w=800',
    subGroups: [
      { name: 'Fitness', items: [{name: 'Dumbbell', query: 'weight'}, {name: 'Koşu Bandı', query: 'treadmill'}] }
    ]
  }
];

export const MOCK_USER: UserProfile = {
  id: 'u1',
  name: 'Ozan S.',
  email: 'ozan@example.com',
  role: 'buyer',
  country: 'UK',
  currency: 'GBP',
  spentTotal: 3450.50,
  lastLogin: '2026-04-18T09:00:00Z',
  savedItems: ['p1', 'p2'],
  preferences: {
    newsletter: true,
    personalizedDeals: true,
    pushNotifications: false
  },
  orders: [
    {
      id: 'ord-101',
      buyerId: 'u1',
      items: [{ productId: 'p1', quantity: 1, price: 249.99 }],
      total: 249.99,
      status: 'delivered',
      createdAt: '2026-03-12T10:00:00Z',
      market: 'UK'
    },
    {
      id: 'ord-102',
      buyerId: 'u1',
      items: [{ productId: 'p4', quantity: 2, price: 19.99 }],
      total: 39.98,
      status: 'delivered',
      createdAt: '2026-04-01T15:00:00Z',
      market: 'UK'
    }
  ]
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    sellerId: 's1',
    title: 'Ethereal Soundscape Pro - Wireless Hybrid Noise Cancelling Headphones',
    slug: 'ethereal-soundscape-pro',
    description: 'Bespoke audio experience with active noise cancellation and 360 spatial audio.',
    longDescription: 'The Ethereal Soundscape Pro marks a new era in personal audio. Featuring 50mm Bio-Logic Hybrid drivers and our proprietary ANC algorithm, it delivers studio-quality sound in any environment.\n\nWith up to 50 hours of battery life and rapid charging (5 hours of play from 10 minutes of charge), your music never has to stop. The ergonomic memory foam cushions ensure all-day comfort, while the titanium frame provides robustness without the weight.',
    specifications: { 
      'Driver Type': '50mm Bio-Logic Hybrid', 
      'Battery Life': 'Up to 50 hours',
      'Connectivity': 'Bluetooth 5.3, USB-C, 3.5mm Jack',
      'Frequency Response': '5Hz - 40kHz',
      'Weight': '290g',
      'Charging': 'Fast Charge (10min = 5h)',
      'Noise Cancellation': 'Hybrid Adaptive ANC (48dB Reduction)',
      'Water Resistance': 'IPX4 Splash Proof'
    },
    brand: 'AuraAudio',
    categoryId: 'electronics',
    tags: ['electronics', 'headphones', 'premium', 'anc'],
    price: 249.99,
    oldPrice: 320.00,
    currency: 'GBP',
    stock: 45,
    weight: 1.2,
    originCountry: 'UK',
    hsCode: '8518.30',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&q=80&w=800'
    ],
    attributes: { 'Battery Life': '50h', 'Noise Cancellation': 'Hybrid ANC' },
    rating: 4.8,
    reviewsCount: 124,
    reviews: [
      {
        id: 'rev1',
        userId: 'u1',
        userName: 'James Wilson',
        rating: 5,
        comment: 'Best headphones I have ever owned. The soundstage is incredible and the ANC is scary good.',
        createdAt: '2026-03-20T10:00:00Z',
        verified: true
      },
      {
        id: 'rev2',
        userId: 'u2',
        userName: 'Sarah Jenkins',
        rating: 4,
        comment: 'Great quality, but the clamping force was a bit tight for the first week. Comfortable now though!',
        createdAt: '2026-03-15T14:30:00Z',
        verified: true
      }
    ],
    featured: true,
    isFlashDeal: true,
    estimatedDeliveryDays: 2,
    deliveryTerms: 'Express Air Shipping (DHL/FedEx)',
    returnPolicy: '30-day Free Global Returns',
    relatedProductIds: ['p14', 'p25'],
    frequentlyBoughtTogetherIds: ['p25']
  },
  {
    id: 'p9',
    sellerId: 's7',
    title: 'Summit Peak 4-Person Cloud-Shield Camping Tent',
    slug: 'summit-peak-tent',
    description: 'Ultra-lightweight, all-season tent with thermal shielding and AI-guided setup.',
    longDescription: 'Engineered for the extremes, the Summit Peak features our proprietary Cloud-Shield fabric which provides superior thermal insulation while remaining breathable. The AI-guided setup uses QR codes on the poles to guide you through assembly in under 5 minutes.',
    specifications: {
      'Capacity': '4 Persons',
      'Seasons': '4 Season',
      'Waterproof': '10,000mm HH',
      'Weight': '4.2kg (Total)',
      'Packed Size': '60cm x 15cm',
      'Material': 'Cloud-Shield Ripstop Nylon',
      'Poles': 'Aerospace Aluminum'
    },
    brand: 'SummitGear',
    categoryId: 'sport',
    tags: ['outdoor', 'camping', 'adventure', 'top-pick'],
    price: 499.00,
    oldPrice: 599.00,
    currency: 'GBP',
    stock: 25,
    weight: 4.2,
    originCountry: 'Canada',
    hsCode: '6306.22',
    images: [
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?auto=format&fit=crop&q=80&w=800'
    ],
    attributes: { 'Capacity': '4 Persons', 'Seasons': '4 Season', 'Waterproof': '10,000mm' },
    rating: 4.9,
    reviewsCount: 88,
    reviews: [
      {
        id: 'rev3',
        userId: 'u3',
        userName: 'Alex Honnold',
        rating: 5,
        comment: 'Held up perfectly in a blizzard. Truly elite gear.',
        createdAt: '2026-04-05T09:00:00Z',
        verified: true
      }
    ],
    estimatedDeliveryDays: 4,
    deliveryTerms: 'Standard International Cargo',
    relatedProductIds: ['p21', 'p11']
  },
  {
    id: 'p10',
    sellerId: 's8',
    title: 'Luminous Glow HD Liquid Foundation - 24hr Wear',
    slug: 'luminous-glow-foundation',
    description: 'Ultra-HD coverage with skin-matching AI pigment technology.',
    brand: 'VelvetVogue',
    categoryId: 'beauty',
    tags: ['beauty', 'makeup', 'skin', 'trending'],
    price: 35.00,
    oldPrice: 45.00,
    currency: 'GBP',
    stock: 200,
    weight: 0.1,
    originCountry: 'France',
    hsCode: '3304.99',
    images: ['https://picsum.photos/seed/makeup1/800/800'],
    attributes: { 'Type': 'Liquid', 'Finish': 'Satin', 'Cruelty Free': 'Yes' },
    rating: 4.7,
    reviewsCount: 420,
    estimatedDeliveryDays: 2,
    deliveryTerms: 'Local Hub Fulfillment'
  },
  {
    id: 'p11',
    sellerId: 's9',
    title: 'Aero-Performance Compression Leggings',
    slug: 'aero-compression-leggings',
    description: 'High-performance moisture-wicking fabric for professional athletes.',
    brand: 'VeloForce',
    categoryId: 'sport',
    tags: ['sportswear', 'fitness', 'clothing'],
    price: 55.00,
    oldPrice: 75.00,
    currency: 'GBP',
    stock: 150,
    weight: 0.3,
    originCountry: 'UK',
    hsCode: '6104.63',
    images: ['https://picsum.photos/seed/sport1/800/800'],
    attributes: { 'Material': 'Recycled Poly-Tech', 'Support': 'High Compression' },
    rating: 4.8,
    reviewsCount: 215,
    estimatedDeliveryDays: 3,
    deliveryTerms: 'Priority Postal Export'
  },
  {
    id: 'p12',
    sellerId: 's10',
    title: 'Sovereign Noir Leather Watch - Artisan Collection',
    slug: 'sovereign-noir-watch',
    description: 'Hand-assembled mechanical watch with skeleton dial and Italian leather strap.',
    brand: 'RegalHorology',
    categoryId: 'moda',
    tags: ['luxury', 'watch', 'accessories', 'artisan'],
    price: 1250.00,
    oldPrice: 1500.00,
    currency: 'GBP',
    stock: 5,
    weight: 0.5,
    originCountry: 'Switzerland',
    hsCode: '9102.21',
    images: ['https://picsum.photos/seed/watch1/800/800'],
    attributes: { 'Movement': 'Swiss Mechanical', 'Case': 'Titanium Grade 5', 'Crystal': 'Sapphire' },
    rating: 5.0,
    reviewsCount: 12,
    estimatedDeliveryDays: 5
  },
  {
    id: 'p13',
    sellerId: 's11',
    title: 'Orbit Modular Velvet Sectional Sofa',
    slug: 'orbit-modular-sofa',
    description: 'Infinite configurations with cloud-soft upholstery and smart integrated side panels.',
    brand: 'SolsticeHome',
    categoryId: 'home',
    tags: ['furniture', 'living-room', 'modern', 'interior'],
    price: 2400.00,
    oldPrice: 3100.00,
    currency: 'GBP',
    stock: 8,
    weight: 95.0,
    originCountry: 'Italy',
    hsCode: '9401.61',
    images: ['https://picsum.photos/seed/sofa1/800/800', 'https://picsum.photos/seed/sofa2/800/800'],
    attributes: { 'Material': 'Italian Performance Velvet', 'Fill': 'Memory Foam + Down' },
    rating: 4.9,
    reviewsCount: 34,
    estimatedDeliveryDays: 14
  },
  {
    id: 'p14',
    sellerId: 's1',
    title: 'Prism-Core RGB Gaming Desktop - RTX 5090 Tier',
    slug: 'prism-core-gaming-pc',
    description: 'Uncompromising power for professional gaming and AI development.',
    brand: 'NexusSystems',
    categoryId: 'electronics',
    tags: ['electronics', 'gaming', 'pc', 'performance', 'deal'],
    price: 3499.99,
    oldPrice: 4200.00,
    currency: 'GBP',
    stock: 10,
    weight: 12.0,
    originCountry: 'USA',
    hsCode: '8471.41',
    images: ['https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&q=80&w=800'],
    attributes: { 'GPU': 'RTX 5090 32GB', 'CPU': 'Core i9-16900K', 'RAM': '64GB DDR6' },
    rating: 4.9,
    reviewsCount: 15,
    featured: true,
    isFlashDeal: true,
    estimatedDeliveryDays: 3
  },
  {
    id: 'p15',
    sellerId: 's1',
    title: 'OmniConnect Smart Home Hub - Matter Compatible',
    slug: 'omniconnect-hub',
    description: 'The central brain for your smart home, supporting over 500 devices.',
    brand: 'OmniSystems',
    categoryId: 'home',
    tags: ['electronics', 'smart-home', 'iot'],
    price: 129.00,
    oldPrice: 159.00,
    currency: 'GBP',
    stock: 150,
    weight: 0.4,
    originCountry: 'Germany',
    hsCode: '8517.62',
    images: ['https://images.unsplash.com/photo-1558226701-f87d82231366?auto=format&fit=crop&q=80&w=800'],
    attributes: { 'Compatibility': 'Matter, Zigbee, Z-Wave', 'Voice Assistant': 'Built-in AI' },
    rating: 4.6,
    reviewsCount: 310,
    estimatedDeliveryDays: 3,
    deliveryTerms: 'Standard EU Fulfillment'
  },
  {
    id: 'p16',
    sellerId: 's14',
    title: 'AeroCrest Ergonomic Executive Chair',
    slug: 'aerocrest-chair',
    description: 'Award-winning design with dynamic lumbar support and breathable mesh.',
    brand: 'WorkMaster',
    categoryId: 'home',
    tags: ['office', 'furniture', 'ergonomic'],
    price: 899.00,
    oldPrice: 1100.00,
    currency: 'GBP',
    stock: 20,
    weight: 22.0,
    originCountry: 'UK',
    hsCode: '9401.30',
    images: ['https://picsum.photos/seed/chair1/800/800'],
    attributes: { 'Support': '4D Armrests, Synchro-Tilt', 'Max Load': '150kg' },
    rating: 4.9,
    reviewsCount: 56,
    estimatedDeliveryDays: 5,
    deliveryTerms: 'Curb-side Delivery'
  },
  {
    id: 'p17',
    sellerId: 's15',
    title: 'Artisan Glazed Ceramic Vase - Ocean Mist',
    slug: 'artisan-vase-ocean',
    description: 'Each piece is hand-thrown and individually glazed for a unique finish.',
    brand: 'Clay & Co.',
    categoryId: 'home',
    tags: ['home', 'decor', 'artisan', 'gift'],
    price: 75.00,
    oldPrice: 95.00,
    currency: 'GBP',
    stock: 12,
    weight: 2.5,
    originCountry: 'Portugal',
    hsCode: '6913.90',
    images: ['https://picsum.photos/seed/vase1/800/800'],
    attributes: { 'Height': '35cm', 'Material': 'Stoneware' },
    rating: 5.0,
    reviewsCount: 8,
    estimatedDeliveryDays: 7,
    deliveryTerms: 'Fragile Handling Guaranteed'
  },
  {
    id: 'p18',
    sellerId: 's16',
    title: 'Barista Pro 2.0 - Professional Espresso System',
    slug: 'barista-pro-coffee',
    description: 'Dual boiler system with PID temperature control and integrated burr grinder.',
    brand: 'Caffeinate',
    categoryId: 'home',
    tags: ['kitchen', 'appliances', 'premium', 'coffee'],
    price: 1450.00,
    oldPrice: 1800.00,
    currency: 'GBP',
    stock: 15,
    weight: 18.0,
    originCountry: 'Italy',
    hsCode: '8419.81',
    images: ['https://picsum.photos/seed/coffee1/800/800'],
    attributes: { 'Pressure': '15 Bar', 'Warm-up': '3 Seconds' },
    rating: 4.8,
    reviewsCount: 142,
    estimatedDeliveryDays: 4,
    deliveryTerms: 'Express Global Air'
  },
  {
    id: 'p19',
    sellerId: 's17',
    title: 'RevitalEyes Advanced Night Peptide Serum',
    slug: 'revitaleyes-serum',
    description: 'Wake up to younger-looking eyes with our proprietary biocellular complex.',
    brand: 'OrganiGlow',
    categoryId: 'beauty',
    tags: ['beauty', 'skincare', 'premium', 'gift'],
    price: 85.00,
    oldPrice: 110.00,
    currency: 'GBP',
    stock: 300,
    weight: 0.1,
    originCountry: 'Switzerland',
    hsCode: '3304.99',
    images: ['https://picsum.photos/seed/serum1/800/800'],
    attributes: { 'Volume': '30ml', 'Vegan': 'Yes' },
    rating: 4.9,
    reviewsCount: 950,
    estimatedDeliveryDays: 2,
    deliveryTerms: 'Priority Beauty Export'
  },
  {
    id: 'p20',
    sellerId: 's18',
    title: 'Midnight Oasis Eau de Parfum - 100ml',
    slug: 'midnight-oasis-perfume',
    description: 'Mysterious notes of rare agarwood, ambergris, and Moroccan neroli.',
    brand: 'EssenceElite',
    categoryId: 'beauty',
    tags: ['beauty', 'fragrance', 'luxury', 'gift'],
    price: 210.00,
    oldPrice: 280.00,
    currency: 'GBP',
    stock: 45,
    weight: 0.3,
    originCountry: 'France',
    hsCode: '3303.00',
    images: ['https://picsum.photos/seed/perfume1/800/800'],
    attributes: { 'Concentration': '25%', 'Base': 'Natural Oils' },
    rating: 4.8,
    reviewsCount: 64,
    estimatedDeliveryDays: 3,
    deliveryTerms: 'Secured Liquid Transport'
  },
  {
    id: 'p21',
    sellerId: 's19',
    title: 'IronFlex Adjustable Dumbbell System - 24kg Pair',
    slug: 'ironflex-smart-dumbbells',
    description: 'Space-saving design replaces 15 sets of weights with a single dial turn.',
    brand: 'IronFlex',
    categoryId: 'sport',
    tags: ['fitness', 'gym', 'home-workout'],
    price: 349.00,
    oldPrice: 450.00,
    currency: 'GBP',
    stock: 60,
    weight: 50.0,
    originCountry: 'USA',
    hsCode: '9506.91',
    images: ['https://picsum.photos/seed/dumbbells/800/800'],
    attributes: { 'Max Weight': '24kg/Each', 'Adjustment': 'Quick-Dial' },
    rating: 4.7,
    reviewsCount: 812,
    estimatedDeliveryDays: 6,
    deliveryTerms: 'Heavy Goods Ground Cargo'
  },
  {
    id: 'p22',
    sellerId: 's20',
    title: 'Royal Alpaca Hand-Tailored Wool Coat',
    slug: 'alpaca-hand-coat',
    description: 'Ethically sourced Peruvian alpaca wool, hand-stitched for a timeless silhouette.',
    brand: 'AtelierLoom',
    categoryId: 'moda',
    tags: ['fashion', 'clothing', 'premium', 'eco-friendly'],
    price: 680.00,
    oldPrice: 850.00,
    currency: 'GBP',
    stock: 14,
    weight: 1.8,
    originCountry: 'Peru',
    hsCode: '6201.11',
    images: ['https://picsum.photos/seed/coat1/800/800'],
    attributes: { 'Material': '80% Alpaca, 20% Virgin Wool', 'Length': 'Mid-Calf' },
    rating: 4.9,
    reviewsCount: 28,
    estimatedDeliveryDays: 5,
    deliveryTerms: 'Air-Insured Apparel Box'
  },
  {
    id: 'p23',
    sellerId: 's21',
    title: 'Nova-Glide Carbon-Infused Knit Sneakers',
    slug: 'nova-glide-sneakers',
    description: 'Propulsive carbon plate within high-rebound responsive foam for elite running.',
    brand: 'NovaStride',
    categoryId: 'moda',
    tags: ['fashion', 'shoes', 'performance', 'trending'],
    price: 185.00,
    oldPrice: 220.00,
    currency: 'GBP',
    stock: 120,
    weight: 0.6,
    originCountry: 'Vietnam',
    hsCode: '6404.11',
    images: ['https://picsum.photos/seed/shoes1/800/800'],
    attributes: { 'Drop': '8mm', 'Weight': '190g' },
    rating: 4.8,
    reviewsCount: 154,
    estimatedDeliveryDays: 3,
    deliveryTerms: 'Standard Global Express'
  },
  {
    id: 'p24',
    sellerId: 's4',
    title: 'Kyoto Zen Table Lamp - Bamboo Edition',
    slug: 'kyoto-zen-lamp',
    description: 'Soft amber glow with a hand-woven bamboo shade and solid oak base.',
    brand: 'Zenith',
    categoryId: 'home',
    tags: ['home', 'decor', 'lighting', 'zen'],
    price: 120.00,
    oldPrice: 150.00,
    currency: 'GBP',
    stock: 30,
    weight: 2.1,
    originCountry: 'Japan',
    hsCode: '9405.21',
    images: ['https://picsum.photos/seed/lamp1/800/800'],
    attributes: { 'Material': 'Bamboo, Oak', 'Bulb': 'LED (Included)' },
    rating: 4.9,
    reviewsCount: 45,
    bestSeller: true,
    estimatedDeliveryDays: 8
  },
  {
    id: 'p25',
    sellerId: 's3',
    title: 'Nexus Flow Pro - Vertical Ergonomic Mouse',
    slug: 'nexus-flow-mouse',
    description: 'Reduce wrist strain with our 57-degree vertical handshake position mouse.',
    brand: 'Nexus',
    categoryId: 'electronics',
    tags: ['electronics', 'computers', 'ergonomic'],
    price: 89.00,
    oldPrice: 110.00,
    currency: 'GBP',
    stock: 100,
    weight: 0.2,
    originCountry: 'USA',
    hsCode: '8471.60',
    images: ['https://picsum.photos/seed/mouse1/800/800'],
    attributes: { 'DPI': '4000', 'Connectivity': 'Wireless/Bluetooth' },
    rating: 4.7,
    reviewsCount: 128,
    bestSeller: true,
    estimatedDeliveryDays: 3
  },
  {
    id: 'p_bot_1',
    sellerId: 'bot_1',
    title: 'MCR-X1 Quantum Processor (Industrial)',
    slug: 'mcr-x1-quantum',
    description: 'Next-gen processing artifact exclusively managed by Mercora Automation.',
    brand: 'Mercora Labs',
    categoryId: 'electronics',
    tags: ['global', 'tech', 'bot-exclusive'],
    price: 4999.00,
    currency: 'GBP',
    stock: 5,
    weight: 0.5,
    originCountry: 'United Kingdom',
    hsCode: '8542.31',
    images: ['https://picsum.photos/seed/quantum/800/800'],
    attributes: { 'Tech': 'Quantum-X', 'Efficiency': '99.9%' },
    rating: 5.0,
    reviewsCount: 1250,
    estimatedDeliveryDays: 1
  }
];
