import { Product, Category, UserProfile } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'electronics',
    name: 'Electronics',
    slug: 'electronics',
    icon: 'Smartphone',
    subCategories: [
      { id: 'audio', name: 'Audio & Headphones', slug: 'audio' },
      { id: 'computers', name: 'Computers & Accessories', slug: 'computers' },
      { id: 'smart-home', name: 'Smart Home', slug: 'smart-home' }
    ]
  },
  {
    id: 'home',
    name: 'Home & Living',
    slug: 'home-living',
    icon: 'Home',
    subCategories: [
      { id: 'furniture', name: 'Furniture', slug: 'furniture' },
      { id: 'decor', name: 'Home Decor', slug: 'decor' },
      { id: 'kitchen', name: 'Kitchen & Dining', slug: 'kitchen' },
      { id: 'living-room', name: 'Living Room', slug: 'living-room' }
    ]
  },
  {
    id: 'beauty',
    name: 'Beauty',
    slug: 'beauty',
    icon: 'Sparkles',
    subCategories: [
      { id: 'skincare', name: 'Skin Care', slug: 'skincare' },
      { id: 'makeup', name: 'Makeup Products', slug: 'makeup' },
      { id: 'fragrance', name: 'Fragrance', slug: 'fragrance' }
    ]
  },
  {
    id: 'sport-outdoor',
    name: 'Sport & Outdoor',
    slug: 'sport-outdoor',
    icon: 'Mountain',
    subCategories: [
      { id: 'camping', name: 'Camping & Outdoors', slug: 'camping' },
      { id: 'sportswear', name: 'Sportswear', slug: 'sportswear' },
      { id: 'fitness', name: 'Fitness Gear', slug: 'fitness' }
    ]
  },
  {
    id: 'fashion',
    name: 'Fashion & Accessories',
    slug: 'fashion',
    icon: 'Shirt',
    subCategories: [
      { id: 'clothing', name: 'Clothing', slug: 'clothing' },
      { id: 'accessories', name: 'Accessories', slug: 'accessories' },
      { id: 'shoes', name: 'Shoes', slug: 'shoes' }
    ]
  }
];

export const MOCK_USER: UserProfile = {
  id: 'u1',
  name: 'Ozan S.',
  email: 'ozan@example.com',
  role: 'buyer',
  country: 'UK',
  currency: 'GBP',
  spentTotal: 3450.50,
  lastLogin: '2026-04-18T09:00:00Z',
  savedItems: ['p1', 'p2'],
  preferences: ['electronics', 'modern-office', 'eco-living'],
  orders: [
    {
      id: 'ord-101',
      buyerId: 'u1',
      items: [{ productId: 'p1', quantity: 1, price: 249.99 }],
      total: 249.99,
      status: 'delivered',
      createdAt: '2026-03-12T10:00:00Z',
      market: 'UK'
    },
    {
      id: 'ord-102',
      buyerId: 'u1',
      items: [{ productId: 'p4', quantity: 2, price: 19.99 }],
      total: 39.98,
      status: 'delivered',
      createdAt: '2026-04-01T15:00:00Z',
      market: 'UK'
    }
  ]
};

export const MOCK_PRODUCTS: Product[] = [
  // ... (Existing p1 to p8 items kept but ID-shifted for consistency if needed, or just added below)
  {
    id: 'p1',
    sellerId: 's1',
    title: 'Ethereal Soundscape Pro - Wireless Hybrid Noise Cancelling Headphones',
    slug: 'ethereal-soundscape-pro',
    description: 'Bespoke audio experience with active noise cancellation and 360 spatial audio.',
    longDescription: 'The Ethereal Soundscape Pro marks a new era in personal audio...',
    specifications: { 'Driver Type': '50mm Bio-Logic Hybrid', 'Battery Life': 'Up to 50 hours' },
    brand: 'AuraAudio',
    categoryId: 'audio',
    tags: ['electronics', 'headphones', 'premium', 'anc'],
    price: 249.99,
    oldPrice: 320.00,
    currency: 'GBP',
    stock: 45,
    weight: 1.2,
    originCountry: 'UK',
    hsCode: '8518.30',
    images: ['https://placehold.co/800x800/1a1a2e/ffffff?text=Headphones'],
    attributes: { 'Battery Life': '50h', 'Noise Cancellation': 'Hybrid ANC' },
    rating: 4.8,
    reviewsCount: 124,
    estimatedDeliveryDays: 2,
    deliveryTerms: 'Express Air Shipping (DHL/FedEx)',
    returnPolicy: '30-day Free Global Returns'
  },
  {
    id: 'p9',
    sellerId: 's7',
    title: 'Summit Peak 4-Person Cloud-Shield Camping Tent',
    slug: 'summit-peak-tent',
    description: 'Ultra-lightweight, all-season tent with thermal shielding and AI-guided setup.',
    brand: 'SummitGear',
    categoryId: 'camping',
    tags: ['outdoor', 'camping', 'adventure', 'top-pick'],
    price: 499.00,
    oldPrice: 599.00,
    currency: 'GBP',
    stock: 25,
    weight: 4.2,
    originCountry: 'Canada',
    hsCode: '6306.22',
    images: ['https://placehold.co/800x800/2d4a22/ffffff?text=Tent', 'https://placehold.co/800x800/2d4a22/ffffff?text=Tent+2'],
    attributes: { 'Capacity': '4 Persons', 'Seasons': '4 Season', 'Waterproof': '10,000mm' },
    rating: 4.9,
    reviewsCount: 88,
    estimatedDeliveryDays: 4,
    deliveryTerms: 'Standard International Cargo'
  },
  {
    id: 'p10',
    sellerId: 's8',
    title: 'Luminous Glow HD Liquid Foundation - 24hr Wear',
    slug: 'luminous-glow-foundation',
    description: 'Ultra-HD coverage with skin-matching AI pigment technology.',
    brand: 'VelvetVogue',
    categoryId: 'makeup',
    tags: ['beauty', 'makeup', 'skin', 'trending'],
    price: 35.00,
    oldPrice: 45.00,
    currency: 'GBP',
    stock: 200,
    weight: 0.1,
    originCountry: 'France',
    hsCode: '3304.99',
    images: ['https://placehold.co/800x800/6b2d5e/ffffff?text=Foundation'],
    attributes: { 'Type': 'Liquid', 'Finish': 'Satin', 'Cruelty Free': 'Yes' },
    rating: 4.7,
    reviewsCount: 420,
    estimatedDeliveryDays: 2,
    deliveryTerms: 'Local Hub Fulfillment'
  },
  {
    id: 'p11',
    sellerId: 's9',
    title: 'Aero-Performance Compression Leggings',
    slug: 'aero-compression-leggings',
    description: 'High-performance moisture-wicking fabric for professional athletes.',
    brand: 'VeloForce',
    categoryId: 'sportswear',
    tags: ['sportswear', 'fitness', 'clothing'],
    price: 55.00,
    oldPrice: 75.00,
    currency: 'GBP',
    stock: 150,
    weight: 0.3,
    originCountry: 'UK',
    hsCode: '6104.63',
    images: ['https://placehold.co/800x800/0d47a1/ffffff?text=Leggings'],
    attributes: { 'Material': 'Recycled Poly-Tech', 'Support': 'High Compression' },
    rating: 4.8,
    reviewsCount: 215,
    estimatedDeliveryDays: 3,
    deliveryTerms: 'Priority Postal Export'
  },
  {
    id: 'p12',
    sellerId: 's10',
    title: 'Sovereign Noir Leather Watch - Artisan Collection',
    slug: 'sovereign-noir-watch',
    description: 'Hand-assembled mechanical watch with skeleton dial and Italian leather strap.',
    brand: 'RegalHorology',
    categoryId: 'accessories',
    tags: ['luxury', 'watch', 'accessories', 'artisan'],
    price: 1250.00,
    oldPrice: 1500.00,
    currency: 'GBP',
    stock: 5,
    weight: 0.5,
    originCountry: 'Switzerland',
    hsCode: '9102.21',
    images: ['https://placehold.co/800x800/212121/ffffff?text=Watch'],
    attributes: { 'Movement': 'Swiss Mechanical', 'Case': 'Titanium Grade 5', 'Crystal': 'Sapphire' },
    rating: 5.0,
    reviewsCount: 12,
    estimatedDeliveryDays: 5
  },
  {
    id: 'p13',
    sellerId: 's11',
    title: 'Orbit Modular Velvet Sectional Sofa',
    slug: 'orbit-modular-sofa',
    description: 'Infinite configurations with cloud-soft upholstery and smart integrated side panels.',
    brand: 'SolsticeHome',
    categoryId: 'living-room',
    tags: ['furniture', 'living-room', 'modern', 'interior'],
    price: 2400.00,
    oldPrice: 3100.00,
    currency: 'GBP',
    stock: 8,
    weight: 95.0,
    originCountry: 'Italy',
    hsCode: '9401.61',
    images: ['https://placehold.co/800x800/4a148c/ffffff?text=Sofa', 'https://placehold.co/800x800/4a148c/ffffff?text=Sofa+2'],
    attributes: { 'Material': 'Italian Performance Velvet', 'Fill': 'Memory Foam + Down' },
    rating: 4.9,
    reviewsCount: 34,
    estimatedDeliveryDays: 14
  },
  {
    id: 'p14',
    sellerId: 's12',
    title: 'Prism-Core RGB Gaming Desktop - RTX 5090 Tier',
    slug: 'prism-core-gaming-pc',
    description: 'Uncompromising power for professional gaming and AI development.',
    brand: 'NexusSystems',
    categoryId: 'computers',
    tags: ['electronics', 'gaming', 'pc', 'performance', 'deal'],
    price: 3499.99,
    oldPrice: 4200.00,
    currency: 'GBP',
    stock: 10,
    weight: 12.0,
    originCountry: 'USA',
    hsCode: '8471.41',
    images: ['https://placehold.co/800x800/b71c1c/ffffff?text=Gaming+PC'],
    attributes: { 'GPU': 'RTX 5090 32GB', 'CPU': 'Core i9-16900K', 'RAM': '64GB DDR6' },
    rating: 4.9,
    reviewsCount: 15,
    estimatedDeliveryDays: 3
  },
  {
    id: 'p15',
    sellerId: 's13',
    title: 'OmniConnect Smart Home Hub - Matter Compatible',
    slug: 'omniconnect-hub',
    description: 'The central brain for your smart home, supporting over 500 devices.',
    brand: 'OmniSystems',
    categoryId: 'smart-home',
    tags: ['electronics', 'smart-home', 'iot'],
    price: 129.00,
    oldPrice: 159.00,
    currency: 'GBP',
    stock: 150,
    weight: 0.4,
    originCountry: 'Germany',
    hsCode: '8517.62',
    images: ['https://placehold.co/800x800/004d40/ffffff?text=Smart+Hub'],
    attributes: { 'Compatibility': 'Matter, Zigbee, Z-Wave', 'Voice Assistant': 'Built-in AI' },
    rating: 4.6,
    reviewsCount: 310,
    estimatedDeliveryDays: 3,
    deliveryTerms: 'Standard EU Fulfillment'
  },
  {
    id: 'p16',
    sellerId: 's14',
    title: 'AeroCrest Ergonomic Executive Chair',
    slug: 'aerocrest-chair',
    description: 'Award-winning design with dynamic lumbar support and breathable mesh.',
    brand: 'WorkMaster',
    categoryId: 'furniture',
    tags: ['office', 'furniture', 'ergonomic'],
    price: 899.00,
    oldPrice: 1100.00,
    currency: 'GBP',
    stock: 20,
    weight: 22.0,
    originCountry: 'UK',
    hsCode: '9401.30',
    images: ['https://placehold.co/800x800/263238/ffffff?text=Chair'],
    attributes: { 'Support': '4D Armrests, Synchro-Tilt', 'Max Load': '150kg' },
    rating: 4.9,
    reviewsCount: 56,
    estimatedDeliveryDays: 5,
    deliveryTerms: 'Curb-side Delivery'
  },
  {
    id: 'p17',
    sellerId: 's15',
    title: 'Artisan Glazed Ceramic Vase - Ocean Mist',
    slug: 'artisan-vase-ocean',
    description: 'Each piece is hand-thrown and individually glazed for a unique finish.',
    brand: 'Clay & Co.',
    categoryId: 'decor',
    tags: ['home', 'decor', 'artisan', 'gift'],
    price: 75.00,
    oldPrice: 95.00,
    currency: 'GBP',
    stock: 12,
    weight: 2.5,
    originCountry: 'Portugal',
    hsCode: '6913.90',
    images: ['https://placehold.co/800x800/e65100/ffffff?text=Vase'],
    attributes: { 'Height': '35cm', 'Material': 'Stoneware' },
    rating: 5.0,
    reviewsCount: 8,
    estimatedDeliveryDays: 7,
    deliveryTerms: 'Fragile Handling Guaranteed'
  },
  {
    id: 'p18',
    sellerId: 's16',
    title: 'Barista Pro 2.0 - Professional Espresso System',
    slug: 'barista-pro-coffee',
    description: 'Dual boiler system with PID temperature control and integrated burr grinder.',
    brand: 'Caffeinate',
    categoryId: 'kitchen',
    tags: ['kitchen', 'appliances', 'premium', 'coffee'],
    price: 1450.00,
    oldPrice: 1800.00,
    currency: 'GBP',
    stock: 15,
    weight: 18.0,
    originCountry: 'Italy',
    hsCode: '8419.81',
    images: ['https://placehold.co/800x800/3e2723/ffffff?text=Espresso'],
    attributes: { 'Pressure': '15 Bar', 'Warm-up': '3 Seconds' },
    rating: 4.8,
    reviewsCount: 142,
    estimatedDeliveryDays: 4,
    deliveryTerms: 'Express Global Air'
  },
  {
    id: 'p19',
    sellerId: 's17',
    title: 'RevitalEyes Advanced Night Peptide Serum',
    slug: 'revitaleyes-serum',
    description: 'Wake up to younger-looking eyes with our proprietary biocellular complex.',
    brand: 'OrganiGlow',
    categoryId: 'skincare',
    tags: ['beauty', 'skincare', 'premium', 'gift'],
    price: 85.00,
    oldPrice: 110.00,
    currency: 'GBP',
    stock: 300,
    weight: 0.1,
    originCountry: 'Switzerland',
    hsCode: '3304.99',
    images: ['https://placehold.co/800x800/880e4f/ffffff?text=Serum'],
    attributes: { 'Volume': '30ml', 'Vegan': 'Yes' },
    rating: 4.9,
    reviewsCount: 950,
    estimatedDeliveryDays: 2,
    deliveryTerms: 'Priority Beauty Export'
  },
  {
    id: 'p20',
    sellerId: 's18',
    title: 'Midnight Oasis Eau de Parfum - 100ml',
    slug: 'midnight-oasis-perfume',
    description: 'Mysterious notes of rare agarwood, ambergris, and Moroccan neroli.',
    brand: 'EssenceElite',
    categoryId: 'fragrance',
    tags: ['beauty', 'fragrance', 'luxury', 'gift'],
    price: 210.00,
    oldPrice: 280.00,
    currency: 'GBP',
    stock: 45,
    weight: 0.3,
    originCountry: 'France',
    hsCode: '3303.00',
    images: ['https://placehold.co/800x800/311b92/ffffff?text=Parfum'],
    attributes: { 'Concentration': '25%', 'Base': 'Natural Oils' },
    rating: 4.8,
    reviewsCount: 64,
    estimatedDeliveryDays: 3,
    deliveryTerms: 'Secured Liquid Transport'
  },
  {
    id: 'p21',
    sellerId: 's19',
    title: 'IronFlex Adjustable Dumbbell System - 24kg Pair',
    slug: 'ironflex-smart-dumbbells',
    description: 'Space-saving design replaces 15 sets of weights with a single dial turn.',
    brand: 'IronFlex',
    categoryId: 'fitness',
    tags: ['fitness', 'gym', 'home-workout'],
    price: 349.00,
    oldPrice: 450.00,
    currency: 'GBP',
    stock: 60,
    weight: 50.0,
    originCountry: 'USA',
    hsCode: '9506.91',
    images: ['https://placehold.co/800x800/424242/ffffff?text=Dumbbells'],
    attributes: { 'Max Weight': '24kg/Each', 'Adjustment': 'Quick-Dial' },
    rating: 4.7,
    reviewsCount: 812,
    estimatedDeliveryDays: 6,
    deliveryTerms: 'Heavy Goods Ground Cargo'
  },
  {
    id: 'p22',
    sellerId: 's20',
    title: 'Royal Alpaca Hand-Tailored Wool Coat',
    slug: 'alpaca-hand-coat',
    description: 'Ethically sourced Peruvian alpaca wool, hand-stitched for a timeless silhouette.',
    brand: 'AtelierLoom',
    categoryId: 'clothing',
    tags: ['fashion', 'clothing', 'premium', 'eco-friendly'],
    price: 680.00,
    oldPrice: 850.00,
    currency: 'GBP',
    stock: 14,
    weight: 1.8,
    originCountry: 'Peru',
    hsCode: '6201.11',
    images: ['https://placehold.co/800x800/1b5e20/ffffff?text=Coat'],
    attributes: { 'Material': '80% Alpaca, 20% Virgin Wool', 'Length': 'Mid-Calf' },
    rating: 4.9,
    reviewsCount: 28,
    estimatedDeliveryDays: 5,
    deliveryTerms: 'Air-Insured Apparel Box'
  },
  {
    id: 'p23',
    sellerId: 's21',
    title: 'Nova-Glide Carbon-Infused Knit Sneakers',
    slug: 'nova-glide-sneakers',
    description: 'Propulsive carbon plate within high-rebound responsive foam for elite running.',
    brand: 'NovaStride',
    categoryId: 'shoes',
    tags: ['fashion', 'shoes', 'performance', 'trending'],
    price: 185.00,
    oldPrice: 220.00,
    currency: 'GBP',
    stock: 120,
    weight: 0.6,
    originCountry: 'Vietnam',
    hsCode: '6404.11',
    images: ['https://placehold.co/800x800/f57f17/000000?text=Sneakers'],
    attributes: { 'Drop': '8mm', 'Weight': '190g' },
    rating: 4.8,
    reviewsCount: 154,
    estimatedDeliveryDays: 3,
    deliveryTerms: 'Standard Global Express'
  }
];
