import { Product, Category, UserProfile } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'electronics',
    name: 'Electronics',
    slug: 'electronics',
    icon: 'Smartphone',
    description: 'Cutting-edge tech for every lifestyle',
    subCategories: [
      { id: 'audio', name: 'Audio & Headphones', slug: 'audio' },
      { id: 'computers', name: 'Computers & Accessories', slug: 'computers' },
      { id: 'smart-home', name: 'Smart Home', slug: 'smart-home' },
      { id: 'cameras', name: 'Cameras & Photography', slug: 'cameras' },
      { id: 'mobile', name: 'Mobile & Tablets', slug: 'mobile' },
      { id: 'gaming', name: 'Gaming', slug: 'gaming' },
    ]
  },
  {
    id: 'home',
    name: 'Home & Living',
    slug: 'home-living',
    icon: 'Home',
    description: 'Curated pieces for the modern home',
    subCategories: [
      { id: 'furniture', name: 'Furniture', slug: 'furniture' },
      { id: 'decor', name: 'Home Decor', slug: 'decor' },
      { id: 'kitchen', name: 'Kitchen & Dining', slug: 'kitchen' },
      { id: 'living-room', name: 'Living Room', slug: 'living-room' },
      { id: 'bedroom', name: 'Bedroom', slug: 'bedroom' },
      { id: 'lighting', name: 'Lighting', slug: 'lighting' },
    ]
  },
  {
    id: 'beauty',
    name: 'Beauty & Wellness',
    slug: 'beauty',
    icon: 'Sparkles',
    description: 'Premium beauty from the world\'s top labs',
    subCategories: [
      { id: 'skincare', name: 'Skin Care', slug: 'skincare' },
      { id: 'makeup', name: 'Makeup', slug: 'makeup' },
      { id: 'fragrance', name: 'Fragrance', slug: 'fragrance' },
      { id: 'haircare', name: 'Hair Care', slug: 'haircare' },
      { id: 'wellness', name: 'Wellness & Supplements', slug: 'wellness' },
    ]
  },
  {
    id: 'sport-outdoor',
    name: 'Sport & Outdoor',
    slug: 'sport-outdoor',
    icon: 'Mountain',
    description: 'Gear for athletes and adventurers',
    subCategories: [
      { id: 'camping', name: 'Camping & Outdoors', slug: 'camping' },
      { id: 'sportswear', name: 'Sportswear', slug: 'sportswear' },
      { id: 'fitness', name: 'Fitness Gear', slug: 'fitness' },
      { id: 'cycling', name: 'Cycling', slug: 'cycling' },
      { id: 'yoga', name: 'Yoga & Pilates', slug: 'yoga' },
    ]
  },
  {
    id: 'fashion',
    name: 'Fashion & Accessories',
    slug: 'fashion',
    icon: 'Shirt',
    description: 'Global artisan fashion and accessories',
    subCategories: [
      { id: 'clothing', name: 'Clothing', slug: 'clothing' },
      { id: 'accessories', name: 'Accessories', slug: 'accessories' },
      { id: 'shoes', name: 'Shoes', slug: 'shoes' },
      { id: 'bags', name: 'Bags & Luggage', slug: 'bags' },
      { id: 'jewellery', name: 'Jewellery', slug: 'jewellery' },
    ]
  },
  {
    id: 'food-gourmet',
    name: 'Food & Gourmet',
    slug: 'food-gourmet',
    icon: 'UtensilsCrossed',
    description: 'Premium ingredients from artisan producers',
    subCategories: [
      { id: 'oils-vinegars', name: 'Oils & Vinegars', slug: 'oils-vinegars' },
      { id: 'teas-coffees', name: 'Teas & Coffees', slug: 'teas-coffees' },
      { id: 'chocolates', name: 'Fine Chocolates', slug: 'chocolates' },
      { id: 'spices', name: 'Spices & Condiments', slug: 'spices' },
    ]
  },
  {
    id: 'books-digital',
    name: 'Books & Digital',
    slug: 'books-digital',
    icon: 'BookOpen',
    description: 'Knowledge, creativity, and digital tools',
    subCategories: [
      { id: 'books', name: 'Books', slug: 'books' },
      { id: 'software', name: 'Software & Licences', slug: 'software' },
      { id: 'courses', name: 'Online Courses', slug: 'courses' },
    ]
  },
  {
    id: 'toys-games',
    name: 'Toys & Games',
    slug: 'toys-games',
    icon: 'Gamepad2',
    description: 'For curious minds of all ages',
    subCategories: [
      { id: 'board-games', name: 'Board Games', slug: 'board-games' },
      { id: 'building', name: 'Building & STEM', slug: 'building' },
      { id: 'outdoor-toys', name: 'Outdoor Play', slug: 'outdoor-toys' },
    ]
  },
];

export const MOCK_USER: UserProfile = {
  id: 'u1',
  name: 'Ozan S.',
  email: 'ozan@example.com',
  role: 'buyer',
  country: 'UK',
  currency: 'GBP',
  spentTotal: 3450.50,
  lastLogin: '2026-04-18T09:00:00Z',
  savedItems: ['p1', 'p12', 'p19'],
  preferences: ['electronics', 'modern-office', 'eco-living'],
  orders: [
    {
      id: 'ord-101',
      buyerId: 'u1',
      items: [{ productId: 'p1', quantity: 1, price: 249.99 }],
      total: 249.99,
      status: 'delivered',
      createdAt: '2026-03-12T10:00:00Z',
      market: 'UK'
    },
    {
      id: 'ord-102',
      buyerId: 'u1',
      items: [{ productId: 'p21', quantity: 1, price: 349.00 }],
      total: 349.00,
      status: 'shipped',
      createdAt: '2026-04-15T15:00:00Z',
      market: 'UK'
    }
  ]
};

export const MOCK_PRODUCTS: Product[] = [
  // ─── ELECTRONICS / AUDIO ─────────────────────────────────────────────────
  {
    id: 'p1',
    sellerId: 's1',
    title: 'Ethereal Soundscape Pro — Wireless Hybrid ANC Headphones',
    slug: 'ethereal-soundscape-pro',
    description: 'Bespoke audio with active noise cancellation and 360 spatial audio.',
    longDescription: 'The Ethereal Soundscape Pro marks a new era in personal audio. Dual-driver hybrid architecture delivers studio-grade frequency response from 5Hz to 40kHz.',
    specifications: { 'Driver Type': '50mm Bio-Logic Hybrid', 'Battery Life': 'Up to 50 hours', 'Bluetooth': '5.4 multipoint' },
    brand: 'AuraAudio',
    categoryId: 'audio',
    tags: ['electronics', 'headphones', 'premium', 'anc', 'deal'],
    price: 249.99,
    oldPrice: 320.00,
    currency: 'GBP',
    stock: 45,
    weight: 1.2,
    originCountry: 'UK',
    hsCode: '8518.30',
    images: ['https://placehold.co/800x800/1a1a2e/ffffff?text=ANC+Headphones'],
    attributes: { 'Battery Life': '50h', 'Noise Cancellation': 'Hybrid ANC', 'Colors': 'Midnight / Ivory' },
    rating: 4.8,
    reviewsCount: 124,
    estimatedDeliveryDays: 2,
    deliveryTerms: 'Express Air (DHL/FedEx)',
    returnPolicy: '30-day Free Global Returns',
    relatedProductIds: ['p2', 'p3'],
  },
  {
    id: 'p2',
    sellerId: 's2',
    title: 'Studio One Pro — Open-Back Reference Headphones',
    slug: 'studio-one-pro-headphones',
    description: 'Professional reference headphones for mixing engineers and audiophiles.',
    brand: 'SoundForge',
    categoryId: 'audio',
    tags: ['electronics', 'headphones', 'studio', 'audiophile'],
    price: 399.00,
    currency: 'GBP',
    stock: 22,
    weight: 0.9,
    originCountry: 'Germany',
    hsCode: '8518.30',
    images: ['https://placehold.co/800x800/1a1a2e/e0e0e0?text=Studio+Headphones'],
    attributes: { 'Impedance': '300Ω', 'Frequency': '10Hz–40kHz', 'Cable': 'Detachable OFC' },
    rating: 4.9,
    reviewsCount: 87,
    estimatedDeliveryDays: 3,
  },
  {
    id: 'p3',
    sellerId: 's3',
    title: 'SoundBubble X3 — True Wireless Earbuds',
    slug: 'soundbubble-x3-earbuds',
    description: 'Hi-Res wireless earbuds with 8mm planar drivers and 32h total battery.',
    brand: 'SoundBubble',
    categoryId: 'audio',
    tags: ['electronics', 'earbuds', 'wireless', 'trending'],
    price: 129.00,
    oldPrice: 159.00,
    currency: 'GBP',
    stock: 180,
    weight: 0.05,
    originCountry: 'China',
    hsCode: '8518.30',
    images: ['https://placehold.co/800x800/0d47a1/ffffff?text=TWS+Earbuds'],
    attributes: { 'Driver': '8mm Planar', 'Battery': '8h+24h case', 'IP Rating': 'IPX5' },
    rating: 4.6,
    reviewsCount: 2840,
    estimatedDeliveryDays: 2,
  },
  // ─── ELECTRONICS / COMPUTERS ──────────────────────────────────────────────
  {
    id: 'p14',
    sellerId: 's12',
    title: 'Prism-Core RGB Gaming Desktop — RTX 5090 Tier',
    slug: 'prism-core-gaming-pc',
    description: 'Uncompromising power for professional gaming and AI development.',
    brand: 'NexusSystems',
    categoryId: 'computers',
    tags: ['electronics', 'gaming', 'pc', 'performance', 'deal'],
    price: 3499.99,
    oldPrice: 4200.00,
    currency: 'GBP',
    stock: 10,
    weight: 12.0,
    originCountry: 'USA',
    hsCode: '8471.41',
    images: ['https://placehold.co/800x800/b71c1c/ffffff?text=Gaming+PC'],
    attributes: { 'GPU': 'RTX 5090 32GB', 'CPU': 'Core i9-16900K', 'RAM': '64GB DDR6', 'Storage': '4TB NVMe' },
    rating: 4.9,
    reviewsCount: 15,
    estimatedDeliveryDays: 3,
  },
  {
    id: 'p4',
    sellerId: 's4',
    title: 'UltraClear 27" 4K OLED Monitor — 144Hz Pro Display',
    slug: 'ultraclear-27-oled-monitor',
    description: '27-inch OLED panel with 0.03ms response, DCI-P3 99% coverage.',
    brand: 'ClearVision',
    categoryId: 'computers',
    tags: ['electronics', 'monitor', 'oled', 'top-pick'],
    price: 899.00,
    oldPrice: 1100.00,
    currency: 'GBP',
    stock: 30,
    weight: 6.2,
    originCountry: 'South Korea',
    hsCode: '8528.52',
    images: ['https://placehold.co/800x800/212121/ffffff?text=4K+OLED+Monitor'],
    attributes: { 'Panel': 'OLED 4K', 'Refresh Rate': '144Hz', 'HDR': 'DisplayHDR 1000', 'Ports': 'USB-C 90W, 2×HDMI 2.1' },
    rating: 4.8,
    reviewsCount: 412,
    estimatedDeliveryDays: 4,
  },
  {
    id: 'p5',
    sellerId: 's5',
    title: 'ArcFlow Wireless Mechanical Keyboard — 75% Layout',
    slug: 'arcflow-wireless-keyboard',
    description: 'Hot-swappable wireless mechanical keyboard with gasket mount and PBT keycaps.',
    brand: 'ArcFlow',
    categoryId: 'computers',
    tags: ['electronics', 'keyboard', 'mechanical', 'wireless'],
    price: 149.00,
    oldPrice: 189.00,
    currency: 'GBP',
    stock: 75,
    weight: 1.1,
    originCountry: 'China',
    hsCode: '8471.60',
    images: ['https://placehold.co/800x800/263238/ffffff?text=Mech+Keyboard'],
    attributes: { 'Switch': 'Gateron G Pro 3.0 Red', 'Layout': '75%', 'Connectivity': 'BT 5.1 / USB-C / 2.4GHz' },
    rating: 4.7,
    reviewsCount: 634,
    estimatedDeliveryDays: 3,
  },
  // ─── ELECTRONICS / SMART HOME ──────────────────────────────────────────────
  {
    id: 'p15',
    sellerId: 's13',
    title: 'OmniConnect Smart Home Hub — Matter 1.3 Compatible',
    slug: 'omniconnect-hub',
    description: 'Central brain for your smart home — supports 500+ devices.',
    brand: 'OmniSystems',
    categoryId: 'smart-home',
    tags: ['electronics', 'smart-home', 'iot'],
    price: 129.00,
    oldPrice: 159.00,
    currency: 'GBP',
    stock: 150,
    weight: 0.4,
    originCountry: 'Germany',
    hsCode: '8517.62',
    images: ['https://placehold.co/800x800/004d40/ffffff?text=Smart+Hub'],
    attributes: { 'Compatibility': 'Matter, Zigbee, Z-Wave, Thread', 'Voice': 'Built-in AI assistant' },
    rating: 4.6,
    reviewsCount: 310,
    estimatedDeliveryDays: 3,
  },
  {
    id: 'p6',
    sellerId: 's6',
    title: 'LumoStrip Pro — AI Adaptive RGBIC Smart Light Strip 5m',
    slug: 'lumostrip-pro-smart-light',
    description: 'Music-reactive, AI-adaptive smart lighting with 16M colors.',
    brand: 'LumoTech',
    categoryId: 'smart-home',
    tags: ['electronics', 'smart-home', 'lighting', 'gaming'],
    price: 59.00,
    oldPrice: 79.00,
    currency: 'GBP',
    stock: 500,
    weight: 0.3,
    originCountry: 'China',
    hsCode: '9405.40',
    images: ['https://placehold.co/800x800/4a148c/ffffff?text=Smart+Light+Strip'],
    attributes: { 'Length': '5m', 'Colors': '16M RGBIC', 'App': 'iOS/Android', 'Control': 'Voice + App' },
    rating: 4.5,
    reviewsCount: 1820,
    estimatedDeliveryDays: 2,
  },
  // ─── ELECTRONICS / CAMERAS ────────────────────────────────────────────────
  {
    id: 'p7',
    sellerId: 's7',
    title: 'ActionShot Ultra 4K — Waterproof Action Camera',
    slug: 'actionshot-ultra-4k',
    description: '4K/120fps action camera with HyperSmooth 6.0 stabilization, 10m waterproof.',
    brand: 'ActionShot',
    categoryId: 'cameras',
    tags: ['electronics', 'camera', 'action', 'outdoor'],
    price: 329.00,
    oldPrice: 399.00,
    currency: 'GBP',
    stock: 60,
    weight: 0.15,
    originCountry: 'USA',
    hsCode: '8525.80',
    images: ['https://placehold.co/800x800/1b5e20/ffffff?text=Action+Camera'],
    attributes: { 'Resolution': '4K/120fps', 'Waterproof': '10m', 'Stabilization': 'HyperSmooth 6.0', 'Battery': '2.5h continuous' },
    rating: 4.8,
    reviewsCount: 922,
    estimatedDeliveryDays: 3,
  },
  // ─── HOME / FURNITURE ─────────────────────────────────────────────────────
  {
    id: 'p13',
    sellerId: 's11',
    title: 'Orbit Modular Velvet Sectional Sofa — 5-Piece',
    slug: 'orbit-modular-sofa',
    description: 'Infinite configurations with cloud-soft upholstery and smart integrated side panels.',
    brand: 'SolsticeHome',
    categoryId: 'living-room',
    tags: ['furniture', 'living-room', 'modern', 'interior'],
    price: 2400.00,
    oldPrice: 3100.00,
    currency: 'GBP',
    stock: 8,
    weight: 95.0,
    originCountry: 'Italy',
    hsCode: '9401.61',
    images: ['https://placehold.co/800x800/4a148c/ffffff?text=Sectional+Sofa'],
    attributes: { 'Material': 'Italian Performance Velvet', 'Fill': 'Memory Foam + Down', 'Pieces': '5 modular' },
    rating: 4.9,
    reviewsCount: 34,
    estimatedDeliveryDays: 14,
  },
  {
    id: 'p16',
    sellerId: 's14',
    title: 'AeroCrest Ergonomic Executive Chair — 4D Armrests',
    slug: 'aerocrest-chair',
    description: 'Award-winning design with dynamic lumbar support and breathable mesh.',
    brand: 'WorkMaster',
    categoryId: 'furniture',
    tags: ['office', 'furniture', 'ergonomic', 'top-pick'],
    price: 899.00,
    oldPrice: 1100.00,
    currency: 'GBP',
    stock: 20,
    weight: 22.0,
    originCountry: 'UK',
    hsCode: '9401.30',
    images: ['https://placehold.co/800x800/263238/ffffff?text=Ergonomic+Chair'],
    attributes: { 'Support': '4D Armrests, Synchro-Tilt', 'Max Load': '150kg', 'Back': 'Breathable Mesh' },
    rating: 4.9,
    reviewsCount: 56,
    estimatedDeliveryDays: 5,
  },
  {
    id: 'p8',
    sellerId: 's8',
    title: 'Zen Platform Bed — Solid Oak with Integrated Storage',
    slug: 'zen-platform-bed-oak',
    description: 'Minimalist solid oak platform bed with 4 hydraulic storage drawers. King size.',
    brand: 'NordicCraft',
    categoryId: 'bedroom',
    tags: ['furniture', 'bedroom', 'storage', 'oak'],
    price: 1299.00,
    oldPrice: 1599.00,
    currency: 'GBP',
    stock: 12,
    weight: 85.0,
    originCountry: 'Denmark',
    hsCode: '9403.50',
    images: ['https://placehold.co/800x800/795548/ffffff?text=Oak+Platform+Bed'],
    attributes: { 'Material': 'Solid European Oak', 'Size': 'King (150×200cm)', 'Storage': '4 hydraulic drawers' },
    rating: 4.8,
    reviewsCount: 48,
    estimatedDeliveryDays: 10,
  },
  // ─── HOME / DECOR & KITCHEN ───────────────────────────────────────────────
  {
    id: 'p17',
    sellerId: 's15',
    title: 'Artisan Glazed Ceramic Vase — Ocean Mist',
    slug: 'artisan-vase-ocean',
    description: 'Hand-thrown and individually glazed for a unique finish.',
    brand: 'Clay & Co.',
    categoryId: 'decor',
    tags: ['home', 'decor', 'artisan', 'gift'],
    price: 75.00,
    oldPrice: 95.00,
    currency: 'GBP',
    stock: 12,
    weight: 2.5,
    originCountry: 'Portugal',
    hsCode: '6913.90',
    images: ['https://placehold.co/800x800/e65100/ffffff?text=Ceramic+Vase'],
    attributes: { 'Height': '35cm', 'Material': 'Hand-thrown Stoneware', 'Finish': 'Reactive glaze' },
    rating: 5.0,
    reviewsCount: 8,
    estimatedDeliveryDays: 7,
  },
  {
    id: 'p18',
    sellerId: 's16',
    title: 'Barista Pro 2.0 — Dual Boiler Espresso System',
    slug: 'barista-pro-coffee',
    description: 'Dual boiler with PID temperature control and integrated burr grinder.',
    brand: 'Caffeinate',
    categoryId: 'kitchen',
    tags: ['kitchen', 'appliances', 'premium', 'coffee'],
    price: 1450.00,
    oldPrice: 1800.00,
    currency: 'GBP',
    stock: 15,
    weight: 18.0,
    originCountry: 'Italy',
    hsCode: '8419.81',
    images: ['https://placehold.co/800x800/3e2723/ffffff?text=Espresso+Machine'],
    attributes: { 'Pressure': '15 Bar', 'Warm-up': '3 Seconds', 'Grinder': 'Integrated 60mm burr' },
    rating: 4.8,
    reviewsCount: 142,
    estimatedDeliveryDays: 4,
  },
  {
    id: 'p9',
    sellerId: 's9',
    title: 'Ember Luna Smart Candle Set — 3-Pack Signature Scents',
    slug: 'ember-luna-candle-set',
    description: 'Hand-poured soy wax candles with app-controlled LED flame ambiance.',
    brand: 'EmberCo',
    categoryId: 'decor',
    tags: ['home', 'decor', 'gift', 'wellness'],
    price: 65.00,
    oldPrice: 85.00,
    currency: 'GBP',
    stock: 200,
    weight: 1.2,
    originCountry: 'UK',
    hsCode: '3406.00',
    images: ['https://placehold.co/800x800/f57f17/000000?text=Candle+Set'],
    attributes: { 'Wax': '100% Natural Soy', 'Burn Time': '50h each', 'Scents': 'Oud, Vetiver, Neroli' },
    rating: 4.7,
    reviewsCount: 381,
    estimatedDeliveryDays: 2,
  },
  // ─── BEAUTY / SKINCARE & MAKEUP ───────────────────────────────────────────
  {
    id: 'p19',
    sellerId: 's17',
    title: 'RevitalEyes Advanced Night Peptide Serum — 30ml',
    slug: 'revitaleyes-serum',
    description: 'Proprietary biocellular complex reduces dark circles by 78% in 28 days.',
    brand: 'OrganiGlow',
    categoryId: 'skincare',
    tags: ['beauty', 'skincare', 'premium', 'gift', 'top-pick'],
    price: 85.00,
    oldPrice: 110.00,
    currency: 'GBP',
    stock: 300,
    weight: 0.1,
    originCountry: 'Switzerland',
    hsCode: '3304.99',
    images: ['https://placehold.co/800x800/880e4f/ffffff?text=Night+Serum'],
    attributes: { 'Volume': '30ml', 'Vegan': 'Yes', 'Dermatologist Tested': 'Yes' },
    rating: 4.9,
    reviewsCount: 950,
    estimatedDeliveryDays: 2,
  },
  {
    id: 'p10',
    sellerId: 's8',
    title: 'Luminous Glow HD Foundation — 24hr Wear',
    slug: 'luminous-glow-foundation',
    description: 'Ultra-HD coverage with AI skin-matching pigment technology. 40 shades.',
    brand: 'VelvetVogue',
    categoryId: 'makeup',
    tags: ['beauty', 'makeup', 'skin', 'trending'],
    price: 35.00,
    oldPrice: 45.00,
    currency: 'GBP',
    stock: 200,
    weight: 0.1,
    originCountry: 'France',
    hsCode: '3304.99',
    images: ['https://placehold.co/800x800/6b2d5e/ffffff?text=HD+Foundation'],
    attributes: { 'Type': 'Liquid', 'Finish': 'Satin', 'Cruelty Free': 'Yes', 'Shades': '40' },
    rating: 4.7,
    reviewsCount: 420,
    estimatedDeliveryDays: 2,
  },
  {
    id: 'p20',
    sellerId: 's18',
    title: 'Midnight Oasis Eau de Parfum — 100ml',
    slug: 'midnight-oasis-perfume',
    description: 'Rare agarwood, ambergris, and Moroccan neroli. Long-lasting 24h projection.',
    brand: 'EssenceElite',
    categoryId: 'fragrance',
    tags: ['beauty', 'fragrance', 'luxury', 'gift'],
    price: 210.00,
    oldPrice: 280.00,
    currency: 'GBP',
    stock: 45,
    weight: 0.3,
    originCountry: 'France',
    hsCode: '3303.00',
    images: ['https://placehold.co/800x800/311b92/ffffff?text=Eau+de+Parfum'],
    attributes: { 'Concentration': 'EDP 25%', 'Longevity': '24h', 'Base': 'Agarwood + Ambergris' },
    rating: 4.8,
    reviewsCount: 64,
    estimatedDeliveryDays: 3,
  },
  {
    id: 'p24',
    sellerId: 's24',
    title: 'ProGlide Ionic Hair Dryer — 3200W Salon Series',
    slug: 'proglide-ionic-hair-dryer',
    description: 'Salon-grade ionic dryer with 4 heat settings and magnetic attachments.',
    brand: 'SalonPro',
    categoryId: 'haircare',
    tags: ['beauty', 'haircare', 'appliance'],
    price: 199.00,
    oldPrice: 259.00,
    currency: 'GBP',
    stock: 90,
    weight: 0.7,
    originCountry: 'Italy',
    hsCode: '8516.31',
    images: ['https://placehold.co/800x800/880e4f/e0e0e0?text=Hair+Dryer'],
    attributes: { 'Power': '3200W', 'Technology': 'Ionic + Far Infrared', 'Attachments': '3 magnetic' },
    rating: 4.7,
    reviewsCount: 287,
    estimatedDeliveryDays: 2,
  },
  // ─── SPORT & OUTDOOR ──────────────────────────────────────────────────────
  {
    id: 'p21',
    sellerId: 's19',
    title: 'IronFlex Adjustable Dumbbell System — 24kg Pair',
    slug: 'ironflex-smart-dumbbells',
    description: 'Replaces 15 sets with a single dial turn. Space-saving home gym essential.',
    brand: 'IronFlex',
    categoryId: 'fitness',
    tags: ['fitness', 'gym', 'home-workout', 'trending'],
    price: 349.00,
    oldPrice: 450.00,
    currency: 'GBP',
    stock: 60,
    weight: 50.0,
    originCountry: 'USA',
    hsCode: '9506.91',
    images: ['https://placehold.co/800x800/424242/ffffff?text=Adj+Dumbbells'],
    attributes: { 'Max Weight': '24kg Each', 'Adjustment': 'Quick-Dial 1kg steps', 'Material': 'Cast iron + rubber' },
    rating: 4.7,
    reviewsCount: 812,
    estimatedDeliveryDays: 6,
  },
  {
    id: 'p9b',
    sellerId: 's7',
    title: 'Summit Peak 4-Person Cloud-Shield Camping Tent',
    slug: 'summit-peak-tent',
    description: 'Ultra-lightweight 4-season tent with thermal shielding and AI-guided setup.',
    brand: 'SummitGear',
    categoryId: 'camping',
    tags: ['outdoor', 'camping', 'adventure', 'top-pick'],
    price: 499.00,
    oldPrice: 599.00,
    currency: 'GBP',
    stock: 25,
    weight: 4.2,
    originCountry: 'Canada',
    hsCode: '6306.22',
    images: ['https://placehold.co/800x800/2d4a22/ffffff?text=Camping+Tent'],
    attributes: { 'Capacity': '4 Persons', 'Seasons': '4-Season', 'Waterproof': '10,000mm HH' },
    rating: 4.9,
    reviewsCount: 88,
    estimatedDeliveryDays: 4,
  },
  {
    id: 'p11',
    sellerId: 's9',
    title: 'Aero-Performance Compression Leggings — Women\'s',
    slug: 'aero-compression-leggings',
    description: 'High-performance moisture-wicking recycled fabric for professional athletes.',
    brand: 'VeloForce',
    categoryId: 'sportswear',
    tags: ['sportswear', 'fitness', 'clothing', 'eco-friendly'],
    price: 55.00,
    oldPrice: 75.00,
    currency: 'GBP',
    stock: 150,
    weight: 0.3,
    originCountry: 'UK',
    hsCode: '6104.63',
    images: ['https://placehold.co/800x800/0d47a1/ffffff?text=Compression+Leggings'],
    attributes: { 'Material': 'Recycled Poly-Tech 78%', 'Support': 'High Compression', 'Sizes': 'XS–3XL' },
    rating: 4.8,
    reviewsCount: 215,
    estimatedDeliveryDays: 3,
  },
  {
    id: 'p25',
    sellerId: 's25',
    title: 'FlowMat Pro 6mm — Natural Cork Yoga Mat',
    slug: 'flowmat-pro-cork-yoga',
    description: 'Antimicrobial natural cork surface with non-slip natural rubber base.',
    brand: 'ZenFlow',
    categoryId: 'yoga',
    tags: ['yoga', 'fitness', 'eco-friendly', 'wellness'],
    price: 89.00,
    oldPrice: 115.00,
    currency: 'GBP',
    stock: 200,
    weight: 2.8,
    originCountry: 'Portugal',
    hsCode: '9506.91',
    images: ['https://placehold.co/800x800/2d4a22/e0e0e0?text=Cork+Yoga+Mat'],
    attributes: { 'Thickness': '6mm', 'Surface': 'Natural Cork', 'Base': 'Natural Rubber', 'Size': '183×68cm' },
    rating: 4.8,
    reviewsCount: 543,
    estimatedDeliveryDays: 3,
  },
  {
    id: 'p26',
    sellerId: 's26',
    title: 'VeloShield Aero Helmet — MIPS Certified',
    slug: 'veloshield-aero-helmet',
    description: 'Wind-tunnel optimised aerodynamic helmet with MIPS rotational protection.',
    brand: 'VeloShield',
    categoryId: 'cycling',
    tags: ['cycling', 'sport', 'safety', 'performance'],
    price: 229.00,
    oldPrice: 289.00,
    currency: 'GBP',
    stock: 45,
    weight: 0.24,
    originCountry: 'Italy',
    hsCode: '6506.10',
    images: ['https://placehold.co/800x800/b71c1c/ffffff?text=Aero+Helmet'],
    attributes: { 'Protection': 'MIPS', 'Vents': '28 aerodynamic', 'Sizes': 'S/M/L', 'Weight': '240g' },
    rating: 4.9,
    reviewsCount: 129,
    estimatedDeliveryDays: 3,
  },
  // ─── FASHION ──────────────────────────────────────────────────────────────
  {
    id: 'p12',
    sellerId: 's10',
    title: 'Sovereign Noir Mechanical Watch — Artisan Collection',
    slug: 'sovereign-noir-watch',
    description: 'Hand-assembled skeleton dial watch with Italian leather strap.',
    brand: 'RegalHorology',
    categoryId: 'accessories',
    tags: ['luxury', 'watch', 'accessories', 'artisan'],
    price: 1250.00,
    oldPrice: 1500.00,
    currency: 'GBP',
    stock: 5,
    weight: 0.5,
    originCountry: 'Switzerland',
    hsCode: '9102.21',
    images: ['https://placehold.co/800x800/212121/ffffff?text=Luxury+Watch'],
    attributes: { 'Movement': 'Swiss Mechanical', 'Case': 'Titanium Grade 5', 'Crystal': 'Sapphire', 'WR': '50m' },
    rating: 5.0,
    reviewsCount: 12,
    estimatedDeliveryDays: 5,
  },
  {
    id: 'p22',
    sellerId: 's20',
    title: 'Royal Alpaca Hand-Tailored Wool Coat',
    slug: 'alpaca-hand-coat',
    description: 'Ethically sourced Peruvian alpaca wool, hand-stitched timeless silhouette.',
    brand: 'AtelierLoom',
    categoryId: 'clothing',
    tags: ['fashion', 'clothing', 'premium', 'eco-friendly'],
    price: 680.00,
    oldPrice: 850.00,
    currency: 'GBP',
    stock: 14,
    weight: 1.8,
    originCountry: 'Peru',
    hsCode: '6201.11',
    images: ['https://placehold.co/800x800/1b5e20/ffffff?text=Alpaca+Coat'],
    attributes: { 'Material': '80% Alpaca, 20% Virgin Wool', 'Length': 'Mid-Calf', 'Lining': 'Silk' },
    rating: 4.9,
    reviewsCount: 28,
    estimatedDeliveryDays: 5,
  },
  {
    id: 'p23',
    sellerId: 's21',
    title: 'Nova-Glide Carbon Knit Running Sneakers',
    slug: 'nova-glide-sneakers',
    description: 'Carbon plate + high-rebound foam for elite race-day performance.',
    brand: 'NovaStride',
    categoryId: 'shoes',
    tags: ['fashion', 'shoes', 'performance', 'trending'],
    price: 185.00,
    oldPrice: 220.00,
    currency: 'GBP',
    stock: 120,
    weight: 0.6,
    originCountry: 'Vietnam',
    hsCode: '6404.11',
    images: ['https://placehold.co/800x800/e65100/000000?text=Carbon+Sneakers'],
    attributes: { 'Drop': '8mm', 'Weight': '190g', 'Midsole': 'ZoomX foam + carbon plate' },
    rating: 4.8,
    reviewsCount: 154,
    estimatedDeliveryDays: 3,
  },
  {
    id: 'p27',
    sellerId: 's27',
    title: 'Heritage Full-Grain Leather Backpack — 30L',
    slug: 'heritage-leather-backpack',
    description: 'Full-grain Italian leather backpack with laptop compartment and brass hardware.',
    brand: 'LeatherLoft',
    categoryId: 'bags',
    tags: ['fashion', 'bags', 'leather', 'premium', 'gift'],
    price: 450.00,
    oldPrice: 580.00,
    currency: 'GBP',
    stock: 18,
    weight: 1.5,
    originCountry: 'Italy',
    hsCode: '4202.12',
    images: ['https://placehold.co/800x800/3e2723/ffffff?text=Leather+Backpack'],
    attributes: { 'Material': 'Full-Grain Vachetta', 'Capacity': '30L', 'Laptop': 'Fits up to 16"' },
    rating: 4.9,
    reviewsCount: 67,
    estimatedDeliveryDays: 5,
  },
  {
    id: 'p28',
    sellerId: 's28',
    title: 'Soleil Shield Polarised Titanium Sunglasses',
    slug: 'soleil-shield-sunglasses',
    description: 'Italian-made titanium frames with polarised CR-39 lenses. UV400.',
    brand: 'SoleilOpt',
    categoryId: 'accessories',
    tags: ['fashion', 'accessories', 'luxury', 'summer'],
    price: 320.00,
    oldPrice: 420.00,
    currency: 'GBP',
    stock: 35,
    weight: 0.02,
    originCountry: 'Italy',
    hsCode: '9004.10',
    images: ['https://placehold.co/800x800/f57f17/000000?text=Titanium+Sunglasses'],
    attributes: { 'Frame': 'Titanium', 'Lens': 'CR-39 Polarised', 'UV': 'UV400', 'Bridge': 'Adjustable' },
    rating: 4.7,
    reviewsCount: 48,
    estimatedDeliveryDays: 4,
  },
  {
    id: 'p29',
    sellerId: 's29',
    title: 'Lumière 18K Gold-Plated Freshwater Pearl Necklace',
    slug: 'lumiere-pearl-necklace',
    description: 'AAA-grade freshwater pearls on 18k gold-plated sterling silver chain.',
    brand: 'LumièreJewels',
    categoryId: 'jewellery',
    tags: ['jewellery', 'luxury', 'gift', 'pearl'],
    price: 185.00,
    oldPrice: 240.00,
    currency: 'GBP',
    stock: 30,
    weight: 0.05,
    originCountry: 'Japan',
    hsCode: '7117.19',
    images: ['https://placehold.co/800x800/f5f5dc/212121?text=Pearl+Necklace'],
    attributes: { 'Pearl Grade': 'AAA Freshwater', 'Chain': '18K Gold-plated 925 Silver', 'Length': '45cm' },
    rating: 4.9,
    reviewsCount: 93,
    estimatedDeliveryDays: 4,
  },
  // ─── FOOD & GOURMET ───────────────────────────────────────────────────────
  {
    id: 'p30',
    sellerId: 's30',
    title: 'Villa Reale Extra Virgin Olive Oil — 1L Cold Pressed',
    slug: 'villa-reale-olive-oil',
    description: 'Single-estate Sicilian EVOO, first cold-press, polyphenol certified. DOP.',
    brand: 'Villa Reale',
    categoryId: 'oils-vinegars',
    tags: ['food', 'gourmet', 'italian', 'premium', 'gift'],
    price: 28.00,
    oldPrice: 38.00,
    currency: 'GBP',
    stock: 400,
    weight: 1.2,
    originCountry: 'Italy',
    hsCode: '1509.10',
    images: ['https://placehold.co/800x800/1b5e20/ffffff?text=Olive+Oil'],
    attributes: { 'Volume': '1L', 'Certification': 'PDO Sicilia', 'Polyphenols': '400mg/kg', 'Harvest': '2025–2026' },
    rating: 4.9,
    reviewsCount: 612,
    estimatedDeliveryDays: 3,
  },
  {
    id: 'p31',
    sellerId: 's31',
    title: 'Uji Ceremonial Grade Matcha — 40g Tin',
    slug: 'uji-ceremonial-matcha',
    description: 'First-flush shade-grown Uji matcha. Stone-milled to 5 microns.',
    brand: 'Kyoto Zen Tea',
    categoryId: 'teas-coffees',
    tags: ['food', 'gourmet', 'japanese', 'wellness', 'gift'],
    price: 45.00,
    oldPrice: 60.00,
    currency: 'GBP',
    stock: 150,
    weight: 0.08,
    originCountry: 'Japan',
    hsCode: '0902.10',
    images: ['https://placehold.co/800x800/2d4a22/ffffff?text=Matcha+Tin'],
    attributes: { 'Grade': 'Ceremonial A', 'Weight': '40g', 'Harvest': 'First Flush 2026', 'Caffeine': '68mg per serving' },
    rating: 4.8,
    reviewsCount: 874,
    estimatedDeliveryDays: 4,
  },
  {
    id: 'p32',
    sellerId: 's32',
    title: 'Maison Blanc 72% Dark Chocolate Collection — 6 Bars',
    slug: 'maison-blanc-dark-chocolate',
    description: 'Single-origin bars: Madagascar, Ecuador, São Tomé, Peru, Vietnam, Colombia.',
    brand: 'Maison Blanc',
    categoryId: 'chocolates',
    tags: ['food', 'gourmet', 'chocolate', 'gift', 'premium'],
    price: 55.00,
    oldPrice: 72.00,
    currency: 'GBP',
    stock: 250,
    weight: 0.6,
    originCountry: 'Belgium',
    hsCode: '1806.32',
    images: ['https://placehold.co/800x800/3e2723/ffffff?text=Chocolate+Collection'],
    attributes: { 'Cacao': '72%', 'Origins': '6 single-origin', 'Weight': '100g per bar', 'Vegan': 'Yes' },
    rating: 4.9,
    reviewsCount: 441,
    estimatedDeliveryDays: 3,
  },
  // ─── BOOKS & DIGITAL ──────────────────────────────────────────────────────
  {
    id: 'p33',
    sellerId: 's33',
    title: 'The Art of Commerce — Collector\'s Hardcover Edition',
    slug: 'art-of-commerce-book',
    description: 'Definitive guide to building global digital commerce businesses. 680 pages.',
    brand: 'MercoraPub',
    categoryId: 'books',
    tags: ['books', 'business', 'ecommerce', 'learning'],
    price: 49.00,
    oldPrice: 65.00,
    currency: 'GBP',
    stock: 500,
    weight: 1.4,
    originCountry: 'UK',
    hsCode: '4901.99',
    images: ['https://placehold.co/800x800/1a1a2e/ffffff?text=Commerce+Book'],
    attributes: { 'Pages': '680', 'Format': 'Hardcover', 'Language': 'English', 'Edition': 'Collector\'s 2026' },
    rating: 4.7,
    reviewsCount: 234,
    estimatedDeliveryDays: 2,
  },
  // ─── TOYS & GAMES ─────────────────────────────────────────────────────────
  {
    id: 'p34',
    sellerId: 's34',
    title: 'Architects of Mars — Strategy Board Game',
    slug: 'architects-of-mars-game',
    description: '2–5 player colony-building euro game. BGG Top 50. 90–180 min.',
    brand: 'CosmicBoard',
    categoryId: 'board-games',
    tags: ['board-games', 'strategy', 'family', 'gift'],
    price: 65.00,
    oldPrice: 79.00,
    currency: 'GBP',
    stock: 80,
    weight: 2.8,
    originCountry: 'Germany',
    hsCode: '9504.90',
    images: ['https://placehold.co/800x800/b71c1c/ffffff?text=Board+Game'],
    attributes: { 'Players': '2–5', 'Duration': '90–180 min', 'Age': '14+', 'BGG Rating': '8.4' },
    rating: 4.8,
    reviewsCount: 312,
    estimatedDeliveryDays: 3,
  },
  {
    id: 'p35',
    sellerId: 's35',
    title: 'BrainBot STEM Coding Robot — Ages 8+',
    slug: 'brainbot-stem-coding-robot',
    description: 'Teach kids Python and block coding through 150 progressive challenges.',
    brand: 'BrainBot',
    categoryId: 'building',
    tags: ['toys', 'stem', 'coding', 'education', 'gift'],
    price: 129.00,
    oldPrice: 159.00,
    currency: 'GBP',
    stock: 120,
    weight: 0.8,
    originCountry: 'USA',
    hsCode: '9503.00',
    images: ['https://placehold.co/800x800/004d40/ffffff?text=Coding+Robot'],
    attributes: { 'Age': '8+', 'Languages': 'Python + Block', 'Challenges': '150', 'App': 'iOS/Android' },
    rating: 4.7,
    reviewsCount: 567,
    estimatedDeliveryDays: 3,
  },
];
